### ISSUE TITLE
Update raspbian/debian apt-get version

### ISSUE THREAD

**Issue by OverHash** [ddclient/ddclient#100]
Currently, using
```bash
sudo apt-get install ddclient
```

will install a very old ddclient version, and certainly not the latest 3.9.1.

Perhaps update this package over there,
Thanks!

**Comment by DaveSophoServices** [comment]
Overhash, we aren’t responsible for the old version in Debian. We have the latest one available to everyone. Debian chooses a version they’re comfortable with. If you want to contact the Debian project, they may appreciate your help keeping it current :-)

Dave

**Comment by OverHash** [comment]
Hi Dave,

I think it's best if you guys email them, as you are the maintainers, it would certainly make life easy for everyone running a Debian system.

Thanks for your contributions!

**Comment by wimpunk** [comment]
Hi @OverHash,

I know we're a bit late with this but @SuperSandro2000 is working on this, or at least he's trying to contact the debian maintainers.  We are also preparing a ppa version of ddcilent.  Check #130 if you want to follow this up.

**Comment by SuperSandro2000** [comment]
I must admit I totally forgot to write that email. I think a good plan would be to get the ppa up and running and then try to sort out the debian package. I think @rhansen [was also working on that](https://github.com/ddclient/ddclient/pull/116#issuecomment-634112079) (Please correct me if that is wrong.) so I would leave precedence to him.

**Comment by rhansen** [comment]
Yup, I'm working on this. I now have commit access to https://salsa.debian.org/debian/ddclient so I will be pushing updates there soon. I will still need a Debian Developer to actually upload the package to the official repositories, and then it will take some time to propagate into downstream distributions (e.g., Ubuntu).

For Ubuntu I'm working on creating some PPAs that users will be able to use to get the latest version. See #130 for details.

**Comment by SuperSandro2000** [comment]
Going to close this because we have no direct influence over Raspian and if we get 4.0.0 to debian it will be in Raspbian eventually.
