### ISSUE TITLE
Criteria to update IP only on home network

### ISSUE THREAD

**Issue by Bramzor** [ddclient/ddclient#103]
Let's say that we want to run the client on a laptop and only update the IP when it detects that it's on the home network. This would require us to specify a criteria for it to update.
Easiest way in my point of view would be to add a criteria= parameter to the config file to any file and use exec to execute that criteria. If exit code is 0, it should update the IP, if it returns anything else, it should skip the update.
This would allow any script to be used to check if you want to update the IP or not. This could be a WIFI network SSID name for example.

**Comment by SuperSandro2000** [comment]
I don't really thinks that fits into ddclient to well. A better solution for your problem would be to wrap ddclient in some script and let it check that.

**Comment by wimpunk** [comment]
I also follow @SuperSandro2000 on this.  It should not be handled by ddclient.
