### ISSUE TITLE
sourceforge artifact is outdated with v3.9.0?

### ISSUE THREAD

**Issue by chenrui333** [ddclient/ddclient#106]
I wonder if you are going to keep sourceforge artifact up to date with the most recent release.

**Comment by wimpunk** [comment]
Normally they should update automatically, they are linked to github.  I'll check why it is still outdated.

**Comment by SuperSandro2000** [comment]
3.9.1 is also missing. I don't know how many people use sourceforge but we should think about if we want to continue this mirror or not if it requires manual upload.

**Comment by wimpunk** [comment]
Fixed, 3.9.1 is available now. Normally it should now be updated automaticly when creating a release.
