### ISSUE TITLE
Support for Azure DNS

### ISSUE THREAD

**Issue by huedo86** [ddclient/ddclient#107]
Please add support for Azure DNS dyndns service.

https://docs.microsoft.com/en-us/rest/api/dns/recordsets/createorupdate

**Comment by wimpunk** [comment]
Feel free to provide a merge request for the Azure DNS. We currently don't have time to implement this.

**Comment by hauserkristof** [comment]
Dear @wimpunk !

This issue is open for two years, have you considered to add this feature? It would be very useful!

Thank you!

**Comment by SuperSandro2000** [comment]
> have you considered to add this feature?

No, someone would need to create a PR with that feature otherwise it will not get implemented.

**Comment by imightbelosthere** [comment]
Is this ever coming back to the drawing board? Or... DDClient just doxed Azure DNS for wtv reason?

**Comment by hauserkristof** [comment]
Yeah, it would be really nice, to have this.

Until then, @imightbelosthere I'm currently using a dockerized python script for updating my domains.

You can find it here: [immdata/azure-dns-updater](https://github.com/immdata/azure-dns-updater)

**Comment by SuperSandro2000** [comment]
> Is this ever coming back to the drawing board? Or... DDClient just doxed Azure DNS for wtv reason?

No, I am currently focusing on other projects, mainly NixOS, and not planning to spend major time on ddclient.
