### ISSUE TITLE
Dynamic DNS service "Secure Point at https://www.spdyn.de/"

### ISSUE THREAD

**Issue by jmassisi** [ddclient/ddclient#110]
Good morning, thanks for developing ddclient, it is very useful for many people.
Could you please include Secure Point as DDNS provider "https://www.spdyn.de/", can I collaborate in any way to help include it?
I'm new to GNU / Linux and it may take me longer to get something, but I don't stop.
At this moment I am seeing how to install ddclient v3.9.1 and I am going to create an account in one of the supported DDNS providers.
Thanks in advance!

**Comment by SuperSandro2000** [comment]
spdyn.de already support ddlclient. Take a look at https://wiki.securepoint.de/SPDyn/Hostverwenden for the documentation how to do it. If you encounter any problems feel free to open an issue.
