### ISSUE TITLE
Cloudflare - API-Token:  Failed - No DNS-record ID found

### ISSUE THREAD

**Issue by Tiemichael** [ddclient/ddclient#112]
I tried the new approach a couple of hours, ago and am not able to get if working.
The debug shows:
```
DEBUG:    url    = https://api.cloudflare.com/client/v4/zones/89de6f41d90716f308a2079776f60fe5/dns_records?type=A&name=\
DEBUG:    server = api.cloudflare.com
CONNECT:  api.cloudflare.com
CONNECTED:  using SSL
SENDING:  GET /client/v4/zones/89de6f41d90716f308a2079776f60fe5/dns_records?type=A&name=\ HTTP/1.0
SENDING:   Host: api.cloudflare.com
SENDING:   User-Agent: ddclient/3.9.1
SENDING:   Connection: close
SENDING:   Content-Type: application/json
SENDING:   Authorization: Bearer nddddddYgVcj5tFexxxxxxxxM0cPeIQJ4eQYYR91
```
and 
```
RECEIVE:  Server: cloudflare
RECEIVE:  cf-request-id: 0252b697cb0000dcfa4826a200000001
RECEIVE:  
RECEIVE:  {"result":[],"result_info":{"page":1,"per_page":20,"total_pages":0,"count":0,"total_count":0},"success":true,"errors":[],"messages":[]}
FAILED:   updating \: No DNS record ID found.
```
If I compare the GET-line with the API-Documentation, it seems that the DNS-Record Name (example.com) is missing.

The A-record is defined as xxxxxxxx.com.

Thanks for the tool, and your help!

_Originally posted by @Tiemichael in https://github.com/ddclient/ddclient/pull/102#issuecomment-619369354_

**Comment by Tiemichael** [comment]
My ddclient.conf:

protocol=cloudflare,        \
zone=micxxxx.com,            \
ttl=1,                      \
#login=token,     \ # Only needed if you are using your global API key.
password=nfoJ.....xx            \ my API-Token
micxxxx.com, www.micxxxx.com

If I change to `login: token `- I cannot see any data-traffic in the debug-log

My API-Token: `All zones - Zone:Read, DNS:Edit`

**Comment by R-Adrian** [comment]
are you configuring the API Token on a primary account or on a delegated Cloudflare administrator user account?
 I think it might only work for the primary account, but not for secondary delegated administrator userss. (not tested this theory though)

**Comment by R-Adrian** [comment]
update: i have tested with a delegated administrator API Token, it works for me that way too.

when i delete/revoke the delegated API Token and try to update the zone i get this message:
`RECEIVE:  {"success":false,"errors":[{"code":9109,"message":"Invalid access token"}],"messages":[],"result":null}
`
in ddclient.conf you are supposed to use the **exact** keywords `login=token` for the API Token to be used. If you are not using this keyword then the code defaults to using the token as if it were an API Key and not an API Token... and it errors out.

quote from the current ddclient source code:
```
 if ($config{$key}{'login'} eq 'token') {
      $headers .= "Authorization: Bearer $config{$key}{'password'}";
    } else {
      $headers .= "X-Auth-Email: $config{$key}{'login'}\n";
      $headers .= "X-Auth-Key: $config{$key}{'password'}";
    }
```

**Comment by R-Adrian** [comment]
oh, and also: i'm using Cloudflare as DNS-only provider.
Maybe they blocked API updates for Cloudflare Proxied hosts but they allow it for regular simple DNS A records.

**Comment by SuperSandro2000** [comment]
I am running the same setup as @R-Adrian where cloudflare is only my DNS provider and I plan to switch that in the future. So far I do not experience the issue and I don't really have the time to test it with a proxied DNS right now.

**Comment by Tiemichael** [comment]
For me Cloudflare is a DNS-only provider (as far as I would understand) and I assume it's a primary account (no idea what it means).
Here is a API-reply (from the debug-log) which should/could explain:
`RECEIVE:  {"result":[{"id":"89de6f41xxxxxxxxxxxxxxx79776f60fe5","name":"mixxxx.com","status":"active","paused":false,"type":"full","development_mode":-139148325,"name_servers":["alex.ns.cloudflare.com","tori.ns.cloudflare.com"],"original_name_servers":["ns73.domaincontrol.com","ns74.domaincontrol.com"],"original_registrar":null,"original_dnshost":"godaddy","modified_on":"2020-04-25T08:45:58.140045Z","created_on":"2015-11-28T02:38:45.862773Z","activated_on":"2015-11-28T02:49:57.568418Z","meta":{"step":4,"wildcard_proxiable":false,"custom_certificate_quota":0,"page_rule_quota":3,"phishing_detected":false,"multiple_railguns_allowed":false},"owner":{"id":"e688a492795ec5xxxxxxxxxdbf1fdd9b2","type":"user","email":"xxxxxxx@gmail.com"},"account":{"id":"eafab475c2abf2xxxxxxxxxxxe4e1b9cfe","name":"xxxxxxx@gmail.com"},"permissions":["#access:edit","#access:read","#analytics:read","#app:edit","#auditlogs:read","#billing:edit","#billing:read","#cache_purge:edit","#dns_records:edit","#dns_records:read","#lb:edit","#lb:read","#legal:edit","#legal:read","#logs:edit","#logs:read","#member:edit","#member:read","#organization:edit","#organization:read","#ssl:edit","#ssl:read","#stream:edit","#stream:read","#subscription:edit","#subscription:read","#teams:edit","#teams:read","#teams:report","#waf:edit","#waf:read","#webhooks:edit","#webhooks:read","#worker:edit","#worker:read","#zone:edit","#zone:read","#zone_settings:edit","#zone_settings:read"],"plan":{"id":"0feeeeeeeeeeeeeeeeeeeeeeeeeeeeee","name":"Free Website","price":0,"currency":"USD","frequency":"","is_subscribed":true,"can_subscribe":false,"legacy_id":"free","legacy_discount":false,"externally_managed":false}}],"result_info":{"page":1,"per_page":20,"total_pages":1,"count":1,"total_count":1},"success":true,"errors":[],"messages":[]}
`

**Comment by Tiemichael** [comment]
Hope this helps:
I tried to repeat the communication with the CF-api by using Postman.

If I use: `GET https://api.cloudflare.com/client/v4/zones/89de6f41d90716f308a2079776f60fe5/dns_records?type=A&name=`  (as shown in my 1st message) the reply is: `{"result":[],"result_info":{"page":1,"per_page":20,"total_pages":0,"count":0,"total_count":0},"success":true,"errors":[],"messages":[]}`

If I append my domain (mixxxx.com) to the GET request to `GET https://api.cloudflare.com/client/v4/zones/89de6f41d90716f308a2079776f60fe5/dns_records?type=A&name=mixxxx.com`  , I receive `{"result":[{"id":"5316fbb589axxxxxxx8bc0a8fcbcdc4","type":"A","name":"mixxxx.com","content":"139.77.70.88","proxiable":true,"proxied":false,"ttl":1,"locked":false,"zone_id":"89de6f41d9xxxxxxxa2079776f60fe5","zone_name":"mixxxxx.com","modified_on":"2020-04-25T08:45:58.140045Z","created_on":"2020-04-25T08:45:58.140045Z","meta":{"auto_added":false,"managed_by_apps":false,"managed_by_argo_tunnel":false}}],"result_info":{"page":1,"per_page":20,"total_pages":1,"count":1,"total_count":1},"success":true,"errors":[],"messages":[]}`   with `content` as my currently saved external IP.

I did not try further to update my IP ....

**Comment by R-Adrian** [comment]
the slashes at the end of the lines seem to be essential and if you leave them out then the lines are considered parts of a different configuration set...  your example configuration above has some slashes missing.

DDClient can be used to update multiple services at once and the separation between multiple service configurations is exactly those line endings.

Can you please check your ddclient.conf and make sure that all lines (except the last one) that are supposed to be part of the same configuration are ending in a `\` ?

**Comment by Tiemichael** [comment]
This is my config:
##
## CloudFlare (www.cloudflare.com)
##
protocol=cloudflare, \
ttl=1, \
login=token, \
zone=mixxxx.com, \
password=nfoJSSM2YgVxxxxxxxxxxxxxxxxxxxx91 \ # This is either your global API key, or an API token. If you are using an API token, it must have the permissions "Zone - DNS - Edit" and "Zone - Zone - Read". The Zone resources must be "Include - All zones".
mixxxx.com, www.mixxxx.com

**Comment by R-Adrian** [comment]
please make it like this:

```
protocol=cloudflare, \
ttl=1, \
login=token, \
zone=mixxxx.com, \
password=nfoJSSM2YgVxxxxxxxxxxxxxxxxxxxx91 \
mixxxx.com, www.mixxxx.com
```
see the added slashes (with spaces) at the end of each line except the last?

**Comment by Tiemichael** [comment]
Is the same!
Did not display properly before ...

**Comment by R-Adrian** [comment]
silly idea but bear with me...  is that comment that starts with `# This is either your global API`
actually part of your config file in exactly that spot?
if so, then maybe thats the problem.. that line doesn't end in a slash.
try removing that comment from the config file.

**Comment by Tiemichael** [comment]
Removing the comment does not change anything ...

**Comment by vrtareg** [comment]
I have been in similar situation.
Which version of client is in use?
sometimes system package installed one is a bit old version and it doesn't access right API URL for Cloudflare. 
Downloading latest  version from here solves problem.
Regards, 
Areg

**Comment by Tiemichael** [comment]
I am using the latest version, just installed 2 days ago
Thanks!

**Comment by Tiemichael** [comment]
Not sure if it's related:
After successfully updating (with my 'repair'), I receive the following:
```
Use of uninitialized value in string ne at /usr/sbin/ddclient line 953. (several times)
FAILED:   mixxxx.com was not updated because protocol <undefined> is not supported.
```

**Comment by R-Adrian** [comment]
another theory: does /etc/ddclient.conf happen to have MS-DOS-style line endings? 
if you run the command `file /etc/ddclient.conf`
is the output saying something along the lines of "CRLF line terminators"?

**Comment by Tiemichael** [comment]
I am using ddclient on an Ubuntu 16.04 server.
```
file /etc/ddclient/ddclient.conf
/etc/ddclient/ddclient.conf: ASCII text
```

**Comment by 110560** [comment]
Can ddclient be used for .TK domain names?

The cloudflare free plan API cannot be used to update .TK domain names

**Comment by SuperSandro2000** [comment]
> Can ddclient be used for .TK domain names?

I don't believe that ddclient has any limitations about this and does not really care about it but it depends on your provider if they allow it. For example cloudflare does not.

**Comment by Weiers** [comment]
> Hope this helps:
> I tried to repeat the communication with the CF-api by using Postman.
> 
> If I use: `GET https://api.cloudflare.com/client/v4/zones/89de6f41xxxxxxxxxxf308a2079776f60fe5/dns_records?type=A&name=`
> the reply is: `{"result":[],"result_info":{"page":1,"per_page":20,"total_pages":0,"count":0,"total_count":0},"success":true,"errors":[],"messages":[]}`
> 
> If I append my domain (mixxxx.com) to the GET request to `GET https://api.cloudflare.com/client/v4/zones/89de6f41xxxxxxxxxxf308a2079776f60fe5/dns_records?type=A&name=mixxxx.com` ,
> I receive `{"result":[{"id":"5316fbb589axxxxxxx8bc0a8fcbcdc4","type":"A","name":"mixxxx.com","content":"139.77.70.88","proxiable":true,"proxied":false,"ttl":1,"locked":false,"zone_id":"89de6f41d9xxxxxxxa2079776f60fe5","zone_name":"mixxxxx.com","modified_on":"2020-04-25T08:45:58.140045Z","created_on":"2020-04-25T08:45:58.140045Z","meta":{"auto_added":false,"managed_by_apps":false,"managed_by_argo_tunnel":false}}],"result_info":{"page":1,"per_page":20,"total_pages":1,"count":1,"total_count":1},"success":true,"errors":[],"messages":[]}` with `content` as my currently saved external IP.
> 
> I did not try further to update my IP ...
> 
> -- Update --
> Digging a little deeper, it seems that `$domain` in not defined in ln 4580 of ddclient, although `zone` is defined correctly and used successfully in ln 4588.
> I am able to 'repair' it by adding `$domain = $config{$key}{'zone'};` at line 4582.
> `

The bug is caused by the \ in the line end of the password. Try to remove \ in  your ddclient.conf, just like:
`protocol=cloudflare, \
ttl=1, \
login=token, \
zone=mixxxx.com, \
password=nfoJSSM2YgVxxxxxxxxxxxxxxxxxxxx91  # This is either your global API key, or an API token. If you are using an API token, it must have the permissions "Zone - DNS - Edit" and "Zone - Zone - Read". The Zone resources must be "Include - All zones".
mixxxx.com, www.mixxxx.com`

**Comment by rhansen** [comment]
> The bug is caused by the `\` in the line end of the password.

No, that `\` character is significant. Deleting it could potentially introduce a bug if there is something following the `mixxxx.com, www.mixxxx.com` line.

A backslash at the end of a line is a *line continuation*: it tells ddclient that the next line should be treated as part of this line. Without it, the `protocol`, `ttl`, `login`, `zone`, and `password` settings become globals (they set defaults for future host entries) when they should instead only affect the `mixxx.com, www.mixxx.com` hosts.

There is a bug in how ddclient processes comments and line continuations. The comment after the line continuation confuses ddclient, and it doesn't interpret the backslash as a line continuation. Instead, it thinks the backslash is your hostname.

To work around the bug, you can either move the comment to its own line:

```
protocol=cloudflare, \
ttl=1, \
login=token, \
zone=mixxxx.com, \
# This is either your global API key, or an API token. If you are using an API token, it must have the permissions "Zone - DNS - Edit" and "Zone - Zone - Read". The Zone resources must be "Include - All zones".
password=nfoJSSM2YgVxxxxxxxxxxxxxxxxxxxx91 \
mixxxx.com, www.mixxxx.com
```

or you can delete the space between the `\` and the `#`:

```
protocol=cloudflare, \
ttl=1, \
login=token, \
zone=mixxxx.com, \
password=nfoJSSM2YgVxxxxxxxxxxxxxxxxxxxx91 \# This is either your global API key, or an API token. If you are using an API token, it must have the permissions "Zone - DNS - Edit" and "Zone - Zone - Read". The Zone resources must be "Include - All zones".
mixxxx.com, www.mixxxx.com
```

**Comment by Weiers** [comment]
> > The bug is caused by the `\` in the line end of the password.
> 
> No, that `\` character is significant. Deleting it could potentially introduce a bug if there is something following the `mixxxx.com, www.mixxxx.com` line.
> 
> A backslash at the end of a line is a _line continuation_: it tells ddclient to combine the next line with this line (after removing the backslash). Without it, the `protocol`, `ttl`, `login`, `zone`, and `password` settings become globals (they set defaults for future host entries) when they should instead only affect the `mixxx.com, www.mixxx.com` hosts. (If there are no other hosts further down the config file then it doesn't matter.)
> 
> The bug is the comment after the backslash. The backslash **must** be the last character on the line for it to act as a line continuation. Adding a comment after the backslash confuses ddclient, causing it to interpret the backslash as your hostname.
> 
> To fix it, move the comment to its own line:
> 
> ```
> protocol=cloudflare, \
> ttl=1, \
> login=token, \
> zone=mixxxx.com, \
> # This is either your global API key, or an API token. If you are using an API token, it must have the permissions "Zone - DNS - Edit" and "Zone - Zone - Read". The Zone resources must be "Include - All zones".
> password=nfoJSSM2YgVxxxxxxxxxxxxxxxxxxxx91 \
> mixxxx.com, www.mixxxx.com
> ```

Yup, you're right~ I know that the backslash means the line continuation. Just found a way to make it work. However, your solution is much more better.
