### ISSUE TITLE
ddclient partialy work with a Netgear 4G router

### ISSUE THREAD

**Issue by pierrot10** [ddclient/ddclient#113]
Good day everyone.

I successful install ddclient and use dyni with the router/WiFi of my neighbour, but I use temporary and I do not have access of the admin panel od the router.

I now switch to my routers. I have a Raspberry with a sixfab 3/4G/Wifi routezr and a netgear 4G router (AC785) : [url=https://www.netgear.fr/home/products/mobile-broadband/hotspots/ac785.aspx]Your text to link here...[/url]

On both router, I can not access ,y Raspberry Zero whihc is connected to the WiFi.
Actually, I need to make working and be able to remote ssh access to my Raspberry Zero which is connected to the netgear AC 785.

The first test, I ran the command (from the Raspberry Zero) : sudo ddclient -daemon=0 -debug -verbose -noquiet, and it return me a successful reply from dynu.

but when I try to access my raspberry with ss user@domain.ddnsfree.com, I got a error regarding the port 22.

What is funny, from my neighbour router it did nothing else than configuring ddclient and it's works. With my netgear 785 router, it never work, even if I tried to redirect the port 22 (port forwarding) on my Raspberry Zero.

I really wonder what I can do to be able to remote access my Raspberry zero with dynu through my netgear Ac 785 4G router.

Many thanks fro your help, if you have any suggestion

**Comment by wimpunk** [comment]
Sorry for the late answer but did you tried to connect to the system using the IP address.  I guess your problem isn't related to ddclient but related to the configuration of your routers.
