### ISSUE TITLE
Document Perl and module compatibility policy

### ISSUE THREAD

**Issue by rhansen** [ddclient/ddclient#122]
Currently ddclient only requires Perl 5.8.0 (released 2002) and very few Perl modules. As time goes on, contributors will inevitably open pull requests that add new module dependencies or rely on newer features.

There's a trade-off to make: Limiting ourselves to old modules and old Perl versions means that ddclient can run on more systems, but it makes it harder to add new features, clean up old code, and test compatibility of changes. What is the right cut-off for this project? The cut-off should be documented in a contributor guide to help contributors make decisions.

Here's my first-draft attempt at the policy:
  * ddclient should work with the version of Perl distributed with Debian oldstable (currently Perl 5.24.1) and the oldest supported Ubuntu release (currently Ubuntu 16.04, which uses Perl 5.22.1).
  * Core ddclient functionality should not depend on any modules or module features that are not available in Debian oldstable or the oldest supported Ubuntu release.
  * A new dependency can be added for a new feature as long as the rest of ddclient continues to work well on old systems that do not support the dependency.

Thoughts?

**Comment by wimpunk** [comment]
Don't forget Fedora, Redhat and Centos.

**Comment by rhansen** [comment]
Fedora releases are maintained for about 13 months: https://fedoraproject.org/wiki/Fedora_Release_Life_Cycle
RHEL releases are maintained for 10 years: https://access.redhat.com/support/policy/updates/errata/
CentOS releases are based on RHEL and will have similar lifecycles.

Given the stability of Perl, it probably won't be a problem to support Perl and Perl modules from 10 years ago. This is especially true if we use something like [PAR Packager](https://metacpan.org/pod/pp) to copy module source code into the ddclient script.

Debian has https://packages.debian.org and Ubuntu has https://packages.ubuntu.com for discovering versions and module availability. I couldn't find any official public package search engines for RHEL, CentOS, or Fedora. https://pkgs.org looks like a good resource for CentOS and Fedora, but not for RHEL (though we can probably assume that RHEL has the same packages as CentOS).

**Comment by rhansen** [comment]
Fixed by #144.
