### ISSUE TITLE
Change GitHub repo description (this is not a fork)

### ISSUE THREAD

**Issue by rhansen** [ddclient/ddclient#123]
At the top of https://github.com/ddclient/ddclient it says, "Fork of the original ddclient code". But this is the new home of ddclient, not a fork, right? Perhaps it should say something like "Dynamic DNS update script written in Perl" instead.

Also the URL should be updated from http://ddclient.sf.net to https://ddclient.net.

**Comment by wimpunk** [comment]
Fixed.
