### ISSUE TITLE
Ubuntu PPAs with nightly and stable release packages

### ISSUE THREAD

**Issue by rhansen** [ddclient/ddclient#130]
Maintaining Ubuntu PPAs of nightly and stable release packages provides some benefits to the project:
  * Users can easily install the latest version to get newer features. This encourages new contributions.
  * Contributors can easily dogfood the latest changes to quickly uncover bugs.
  * New changes will be tested by the PPA users before being widely released via official distribution packages.

I [requested access](https://answers.launchpad.net/launchpad/+question/690990) to https://launchpad.net/ddclient so that I can set up "official" PPAs. If I understand correctly, we can set up Launchpad to automatically build new nightly packages and new stable release packages, so the maintenance burden should be low. I'm willing to take this on if nobody objects.

**Comment by SuperSandro2000** [comment]
@wimpunk @DaveSophoServices I would be totally for that if you have no objections.

**Comment by DaveSophoServices** [comment]
I wouldn’t object. Thank you Richard for the offer!

**Comment by wimpunk** [comment]
Me neither.
Any objections about giving @rhansen the acccess as the rest of the team?
Meanwhile I search for my lauchpad password.

**Comment by DaveSophoServices** [comment]
No objections.

**Comment by pappacena** [comment]
Hi! Thiago from Launchpad.net here.

Just to let you all know, we are transfering the ownership of [ddclient project at Launchpad](https://launchpad.net/ddclient) to [rhansen](https://launchpad.net/~rhansen), as requested at https://answers.launchpad.net/launchpad/+question/690990 .

Let me know if you have any problem.

**Comment by rhansen** [comment]
Thank you Thiago!

I created [a group for us](https://launchpad.net/~ddclient); added myself, @SuperSandro2000, and @wimpunk to it; and set it as the maintainer for [the project](https://launchpad.net/ddclient). @DaveSophoServices: let me know your Launchpad username (if you have one) and I'll add it to the group as well.

**Comment by wimpunk** [comment]
Great. Good work @rhansen. Btw, I've added you as a maintainer of the ddclient project.

**Comment by rhansen** [comment]
New Debian packaging is getting close to ready (see https://salsa.debian.org/debian/ddclient). I have submitted it to Debian devs (see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=962159); they will review it and give me feedback. Once the dust starts to settle on that I can start working on automating PPA builds

**Comment by rhansen** [comment]
Packages for v3.9.1 are now available for all supported Ubuntu releases except for 16.04 (Xenial):  https://code.launchpad.net/~ddclient/+archive/ubuntu/ppa. These packages are automatically built from the Debian package repository (https://salsa.debian.org/debian/ddclient), so whenever the Debian package repository changes the packages in the stable PPA will be automatically updated.

I'm still working on a Xenial stable package, and on daily packages.

**Comment by rhansen** [comment]
Daily builds are now set up: https://code.launchpad.net/~ddclient/+archive/ubuntu/daily
I haven't yet tried using that PPA, so it could be broken in horrible ways. But that's what daily builds are for, right? :wink:
If you notice any problems, please let me know (you can open an issue here).

I gave up on building packages for Ubuntu 16.04 (Xenial)—its debhelper version is too old and busted.
