### ISSUE TITLE
-ssl flag ignored for dyndns2 (and others) -- http: hard-coded

### ISSUE THREAD

**Issue by jimbo1969** [ddclient/ddclient#139]
When using ddclient to update a dnydns2 server, I have "ssl=yes" specified in the /etc/ddclient/ddclient_eth0.conf file.  However, the URL it uses appears to be plain-old http://, as evidenced by the debug session (specifying -ssl here too, just 'cause): 
`sudo ddclient -file /etc/ddclient/ddclient_eth0.conf -ssl -daemon=0 -debug`
yields:
`DEBUG:    url    = http://ipv4.nsupdate.info/nic/update?system=dyndns&hostname=[my_subdomain].dnsupdate.info&myip=[x.x.x.x]`
I spent the better part of a day reading the code and experimenting, and I noticed line 2727:
`        my $url = "http://$config{$h}{'server'}$config{$h}{'script'}?system=";`
"http://" is hard-coded for dyndns, as it is for several others (while several are hard-coded "https://")

Perhaps I'm missing something.  Or is the DEBUG message just a red herring?  I've not gone to the trouble of connecting a switch, port mirroring, and sniffing the actual connection to be certain.

**Comment by SuperSandro2000** [comment]
If you turn on ``verbose`` mode you can see that it actually connects via https. I also think the URL shown is quite confusing.

**Comment by jimbo1969** [comment]
Wow.  Submit a question, three (3) hours later there is a fix committed to a branch.  That's pretty impressive.  :)

Thanks!
