### ISSUE TITLE
Require daemonization with a non-zero interval

### ISSUE THREAD

**Issue by rhansen** [ddclient/ddclient#149]
Command line arguments currently override settings in the config file, so there is no way to pass an argument to ddclient that means "daemonize with an interval of 10m unless the config file wants a different non-zero interval." This makes it difficult to write a robust init script (see the [tricky config file parsing in the example init script](https://github.com/ddclient/ddclient/blob/5cd21f7c7eafd2351940c7b0d01230160e4fa3ef/sample-etc_rc.d_init.d_ddclient#L37-L49)) or systemd service unit config.

One way around this is to run ddclient with `$0` set to something like `ddclientd`. If `$0` ends with the letter `d` there is [special logic that sets `-daemon=1m` by default](https://github.com/ddclient/ddclient/blob/5cd21f7c7eafd2351940c7b0d01230160e4fa3ef/ddclient#L42-L45). I'm not a fan of this magical behavior because it's not discoverable, it's not documented, users are likely to be confused by the `d` that appears in `ps`, and there's no way to change the 1m to something else (other than via the config file).

Can we do better? What do you think about these possibilities:

  * Add special `-default-foo=bar` flags that act like `-foo=bar` except they are overridden by the config file. If we did this, the init script could simply pass `-default-daemon=10m`. We can automatically create these extra flags inside `process_args`. A `daemon=0` line in the config file would thwart `-default-daemon`, which isn't ideal but probably not a problem in practice.
  * Add a new `-require-daemon` flag that causes ddclient to error out if the config file (or other flags) does not set daemon to a positive value.
  * Invert the priority: the config file overrides the flags, not the other way around.
  * Other ideas?

**Comment by SuperSandro2000** [comment]
Can't we call ddclient with ``daemon=yes``from the init script and change the default wait time? The user wouldn't be able to override the daemon mode but still configure the interval.

**Comment by rhansen** [comment]
That's a good idea. The init script wouldn't be able to change the default interval, but that should be ok as long as the default is sensible.

**Comment by rhansen** [comment]
I'm going to reopen this because I want to modify `-daemon` to accept a boolean. If set to "true" or "yes" (rather than a duration) it would use a default interval unless the interval is specified in another `-daemon` flag or in the config file.
