### ISSUE TITLE
Docs table formatting broken

### ISSUE THREAD

**Issue by andig** [ddclient/ddclient#157]
See https://ddclient.net/routers, this should probably be rendered as markdown?

**Comment by wimpunk** [comment]
Thanks for reporting.  It should be rendered as markdown and it needs an update.

**Comment by wimpunk** [comment]
It's a bit strange, it renders correctly here: https://github.com/ddclient/ddclient.github.io/blob/master/routers.md  I'll try to find out what's going wrong.

**Comment by wimpunk** [comment]
Fixed. Seems like it needed some extra newlines.
