### ISSUE TITLE
Unable to read WAN IP from my Actiontek router

### ISSUE THREAD

**Issue by answerpoet** [ddclient/ddclient#162]
But, it does end up working.. sortof :)

-query output:

use=if, if=enp2s0 address is 192.168.1.9
use=if, if=lo address is 127.0.0.1
use=if, if=virbr0 address is 192.168.122.1
use=if, if=virbr0-nic address is NOT FOUND
use=fw, fw=192.168.1.1/index.cgi address is NOT FOUND
use=web, web=dnspark address is NOT FOUND
use=web, web=dyndns address is ww.xxx.yyy.zzz
use=web, web=loopia address is ww.xxx.yyy.zzz
use=web, web=dynamicdns.park-your-domain.com/getip address is ww.xxx.yyy.zzz

Also tried fw with :443, still no read.
Actual router URL where the IP Address string should be is:
https://192.168.1.1/index.cgi?active%5fpage=9132&active%5fpage%5fstr=page%5fhome%5fact%5fvz&req%5fmode=0&mimic%5fbutton%5ffield=submit%5fbutton%5flogin%5fsubmit%3a+%2e%2e&strip%5fpage%5ftop=0&button%5fvalue=%2e

Do I have to put that _whole_ thing in the fw?

No idea what those other use=web lines are coming from.
Kinda useless for it to get the IP from namecheap, as that's what I'm trying to update!

Is using fw and web redundant? Not clear from the docs or the config comments.

**Comment by rhansen** [comment]
> Do I have to put that _whole_ thing in the fw?

Yes, if that's what your router expects. Does it work if you set `fw` to that full URL?

> No idea what those other use=web lines are coming from.

The `query` option causes ddclient to attempt several different ways to get your current IP address:
  * by looking at your interfaces,
  * by querying the `fw` URL (if you provided one),
  * by querying the `web` URL (if you provided one),
  * by querying some built-in `web` services,
  * etc.

> Kinda useless for it to get the IP from namecheap, as that's what I'm trying to update!

By "get the IP from namecheap" I assume you mean `use=web,web=dynamicdns.park-your-domain.com/getip`. That isn't pointless—the https://dynamicdns.park-your-domain.com/getip page always returns the IP address you currently have, not the IP address that is currently saved in your hostname.example.com record.

> Is using fw and web redundant? Not clear from the docs or the config comments.

It depends on the value of `use`. If you set `use=fw` then it will use your `fw` setting and ignore the `web` setting. If you set `use=web` then it will use your `web` setting and ignore the `fw` setting. If `use` is not set to anything, then ddclient attempts to figure out what you actually want. In this case it will assume you meant `use=web`.
