### ISSUE TITLE
Move check for header ok inside geturl()

### ISSUE THREAD

**Issue by dkerr64** [ddclient/ddclient#170]
The `header_ok()` function is called by many protocols.  This should be moved inside `geturl()` function and the return code from that signal whether the request was successful or not.  It adds complexity to require every protocol function to test the headers after returning from `geturl`.

**Comment by dkerr64** [comment]
I've been looking at this further and think that current implementation is flawed.  `geturl()` function should be changed not to return the HTTP header as it is not required by any of the protocols.

Those that test for it don't need to test because if something failed in `geturl()` it would have returned an empty string.  If the error is reported in the HTTP header, some protocols try and handle it with `header_ok()` which returns ok only on a 200 and while it prints out a somewhat helpful error on a 401, that is all it does... no further action is taken on it.

Protocols handle non-200 returns by proceeding to parse the contents of the body of the response, usually expecting JSON formatted page.  They start with a line of code that looks like...
```
$resp =~ s/^.*?\n\n//s;  # Strip header
```
Except that it doesn't strip the header.  I think this is trying to remove everything before the first blank line, but in my testing it does not.  For example...
```
HTTP/1.1 200 OK
Content-Type: text/html
Server: DynDNS-CheckIP/1.0.1
Connection: close
Cache-Control: no-cache
Pragma: no-cache
Content-Length: 106

<html><head><title>Current IP Check</title></head><body>Current IP Address: 192.168.100.1</body></html>
```
The expected output from striping the header would be..
```
<html><head><title>Current IP Check</title></head><body>Current IP Address: 192.168.100.1</body></html>
```
But that regex expression is not doing what is intended.  Example, test with this code...
```
# Test striping header from reply
my $resp = `curl -4 -i -s http://checkip.dyndns.org/`;
printf("%s\n\r", $resp);
$resp =~ s/^.*?\n\n//s;  # Strip header
printf("==========\n\r");
printf("%s\n\r", $resp);
```

I propose fixing this inside geturl() by striping out the header before returning from the function and removing all header checks from all protocols -- they will identify an error by parsing the body of the returned page as they already do today.

**Comment by rhansen** [comment]
> I propose fixing this inside geturl() by striping out the header before returning from the function

Yup, that's the approach I've taken in my work-in-progress commits. I'm working on adding unit tests right now, and that's proving to be more obnoxious than I thought it would be, so it may take me a while.

**Comment by dkerr64** [comment]
`geturl()` is probably THE most important function in the whole app.  It needs to handle IPv4/IPv6/SSL/authentication/headers/you-name-it.  Very important to get right.  As you do this, please keep in mind that some systems do not have the Perl IPv6 network functions... we need the option to substitute in `curl` (as an alternate option) in those cases.  But I agree to get the basics working in Perl and curl can come later.

**Comment by dkerr64** [comment]
I have found the reason `/\n\n/` is failing on my system.  At least with the output from curl that I am using for testing, newlines are represented by `\r\n` and so to strip off the header we need to look for two of those in a row... `/\r\n\r\n/`.  We probably need code that works with either simply a `\n` or a both `\r\n`.

David

**Comment by dkerr64** [comment]
Okay, ignore my previous grumbles.  The more I look at the code the more I learn.  `geturl()` actually strips out all the `\r`'s so the regex that separates the header would work just fine... my small test script missed that step, hence my confusion.  Of course removing the header still needs to be done inside `geturl()` rather than left to every protocol function in my opinion.  And it is somewhat interesting that PR #173 actually puts `\r`'s into headers that we send up and we remove them on returned data (but that does make for easier processing).

Sorry for all the above comments that turn out to be my own errors.
