### ISSUE TITLE
freedns.afraid.org not working

### ISSUE THREAD

**Issue by th3gr33n** [ddclient/ddclient#176]
```
protocol=freedns
server=freedns.afraid.org
login=username
password='password'
domain1,domain2,domain3


DEBUG:
DEBUG:     nic_freedns_update -------------------
DEBUG:    proxy  =
DEBUG:    url    = http://freedns.afraid.org/api/?action=getdyndns&sha=XXXXXXXXXXXX
DEBUG:    server = freedns.afraid.org
CONNECT:  freedns.afraid.org
CONNECTED:  using SSL
SENDING:  GET /api/?action=getdyndns&sha=XXXXXXXXXXX
HTTP/1.0
SENDING:   Host: freedns.afraid.org
SENDING:   User-Agent: ddclient/3.9.1
SENDING:   Connection: close
SENDING:
SENDING:
RECEIVE:  HTTP/1.1 200 OK
RECEIVE:  Server: nginx
RECEIVE:  Date: Sat, 13 Jun 2020 21:27:26 GMT
RECEIVE:  Content-Type: text/html; charset=UTF-8
RECEIVE:  Connection: close
RECEIVE:  Vary: Accept-Encoding
RECEIVE:  X-Cache: MISS
RECEIVE:
RECEIVE:  ERROR: Could not authenticate.
FAILED:   Could not get freedns update URLs from freedns.afraid.org
```

**Comment by rhansen** [comment]
How did you install ddclient? Did you install a package from your distribution? If so, which? If you cloned the Git repository and ran it from there, which Git revision are you running?

**Comment by rhansen** [comment]
From the `ERROR: Could not authenticate.` line it looks like your username and/or password was rejected. Can you manually log in to make sure they work?

Also, has it ever worked for you?

**Comment by th3gr33n** [comment]
1st i had a distributor package which was version 3.8.1 i guess with the same problem.
i google about that issue and found thats it is a known issue.
i deinstalled and purged it and found this maintaned version here.

currently running
ddclient version 3.9.1

username/password are fine i can login

**Comment by th3gr33n** [comment]
i might have found the problem..
the api state:
Password is maximum length of 16 characters.

mine is longer

**Comment by rhansen** [comment]
I sent an email to freedns.afraid.org to ask for clarification. In the meantime, would you mind trying #179 for me?

**Comment by rhansen** [comment]
I got a reply from Josh at afraid.org:

> The site will not allow them to set a password of greater length presently, so they shouldn't be using one of greater length in a dynamic update context.  I wouldn't "force" any behavior at the client, since the limit may be removed, or greatly enlarged.

So maybe your password is actually just 16 characters long?

**Comment by SuperSandro2000** [comment]
Closing because there was no answer in 17 days. Feel free to reopen the discussion and then we can reopen the issue.
