### ISSUE TITLE
Does ddclient really need Data::Validate::IP

### ISSUE THREAD

**Issue by dkerr64** [ddclient/ddclient#177]
Is it really necessary to require module Data::Validate::IP.  This is not installed by default and I think that ddclient should be as lightweight as possible.  Requiring this is going to cause ddclient to fail on many systems, especially lightweight embedded systems.  I ran into this myself on Ubuntu 20.04.

The only thing this is used for is to check for a valid IPv6.  There is already a check_value() function in ddclient and it could easily be enhanced to validate a IPv6 address, as implemented here... https://github.com/astlinux-project/ddclient-curl/blob/55c623b6fa4686af620871c48bdbcd70048c65f6/ddclient#L1964

If all we need this is to validate an IP address then we should do it ourselves.

David.

**Comment by rhansen** [comment]
I was wondering the same thing. There is no official Data::Validate::IP RPM for CentOS 6 or 7 and their RHEL counterparts, so requiring that dependency immediately rules out those platforms without extra effort on the part of the packager.

**Comment by dkerr64** [comment]
I vote for removing this dependency ASAP.

**Comment by rhansen** [comment]
Sounds good to me. Mind putting together a pull request?
