### ISSUE TITLE
Don't log secret information

### ISSUE THREAD

**Issue by rhansen** [ddclient/ddclient#185]
We log URLs that contain tokens or passwords and HTTP messages that contain basic auth information. We should censor the secret bits so that users pasting log messages don't accidentally disclose credentials.

**Comment by rhansen** [comment]
Clarification: It's OK to log sensitive information in debug logs because those are meant for local debugging. Verbose log messages should not contain sensitive information.

**Comment by SuperSandro2000** [comment]
This is a feature request and feature requests in the form of issues are no longer accepted.
