### ISSUE TITLE
Support more standard config file format.

### ISSUE THREAD

**Issue by dkerr64** [ddclient/ddclient#189]
Years ago I discovered that the config file format is kind of weird and not at all robust when it comes to including multiple services.  Take this example...
```
ssl=yes
protocol=cloudflare
server=api.cloudflare.com/client/v4
zone=example.com
login=user@example.com
password=secret
use=if
if=eth0
myserver.example.com

protocol=freedns
use=if
if=eth0
login=user
password=secret
myserver.example.com
```
Now I might have expected this to work, but it fails because the FreeDNS protocol attempts to access `api.cloudflare.com/client/v4` despite ddclient documenting that the default is `freedns.afraid.org`.  So to make the above work you have to add the line.
```
server=freedns.afraid.org
```
and if you don't want ssl for FreeDNS then would have to explicitly set that to no.

I suspect that when ddclient was originally written multiple services were not anticipated.  If possible I think we should implement support for a more standard conf/ini file format along the lines of...
```
[defaults]
use=if
if=eth0

[service]
protocol=cloudflare
server=api.cloudflare.com/client/v4
zone=example.com
login=user@example.com
password=secret
ssl=yes
domain=myserver.example.com

[service]
protocol=freedns
login=user
password=secret
domain=myserver.example.com
```
Each `[service]` would inherit from `[defaults]` but would never inherit from another service definition.

An alternative would be YAML but I think that is probably overkill and far more difficult to parse.

**Comment by SuperSandro2000** [comment]
This is a feature request and feature requests in the form of issues are no longer accepted.
