### ISSUE TITLE
ClouDNS dyndns

### ISSUE THREAD

**Issue by reetp** [ddclient/ddclient#190]
You can a get a free zone https://www.cloudns.net (I have no relationship with them - was just looking at different providers)

The URL is in this format:

https://ipv4.cloudns.net/api/dynamicURL/?q=Mjg3MzMxM..... etc

Their perl script suggests this but not sure how you would implement this in ddclient:

```
#!/usr/bin/perl
	my $uri = 'https://ipv4.cloudns.net/api/dynamicURL/?q=Mjg3MzMxM.....etc';
	use HTTP::Tiny;
	eval { HTTP::Tiny->can_ssl }
	or die "Please ensure you have HTTP::Tiny (>= 0.055) and IO::Socket::SSL";
	my $res = HTTP::Tiny->new()->get($uri);
	$res->{success} or die "$res->{status} $res->{reason}";
	print {*STDERR} "notification sent successfully" if $ENV{DEBUG};
```

Not sure I have the skills to code this one :-(

**Comment by rhansen** [comment]
More info can be found here: https://www.cloudns.net/dynamic-dns/

I don't see a documented way to pass the desired IP address. https://www.cloudns.net/wiki/article/36/ says, "If you are behind a proxy and your real IP is set in the header X-Forwarded-For you need to add `&proxy=1` at the end of the DynamicURL." We could abuse that feature to supply the desired IP address, but it won't work if the user is actually using a proxy.

**Comment by reetp** [comment]
Thanks for looking - so it is probably a non starter.
