### ISSUE TITLE
DinaHosting

### ISSUE THREAD

**Issue by reetp** [ddclient/ddclient#203]
After someone kindly added ClouDNS I've been trying to add DinaHosting.

I used this as a basis but had to move a few bits about:

https://github.com/alexandregz/ddclient-dh

It updates the IP at the DNS hoster but throws an error right at the end that I can't figure out.

`Can't locate object method "get" via package "URL" (perhaps you forgot to load "URL"?) at ./ddclient line 5212.`

I was going to do a PR and then realised I wasn't sure where the ddclient file is to actually do that....

I've added it as a rough patch if anyone wants to take a look.

Thanks.

[ddclient-3.9.1.dinahosting.txt](https://github.com/ddclient/ddclient/files/4846761/ddclient-3.9.1.dinahosting.txt)

**Comment by rhansen** [comment]
Line 5212 is  missing a comment character:

    Try to get URL

should be:

    # Try to get URL

**Comment by reetp** [comment]
Ahhhh damn... happened as I was testing conversion to 3.9.1

Grrrr....!!!!!

I'll fix that & test again thanks.

**Comment by reetp** [comment]
Yup, that fixed it thanks. Updates without an error.

[ddclient-3.9.1.dinahosting.txt](https://github.com/ddclient/ddclient/files/4851663/ddclient-3.9.1.dinahosting.txt)

**Comment by rhansen** [comment]
Cool! Would you feel like sending us a pull request with your changes?

**Comment by reetp** [comment]
I can - but can you confirm the patch is against `ddclient.in` ? 

Not used to this structure!

**Comment by rhansen** [comment]
Yes, the patch should be against `ddclient.in`.

Thanks!
