### ISSUE TITLE
Put back ddclient file?

### ISSUE THREAD

**Issue by dkerr64** [ddclient/ddclient#206]
Okay, I may have missed this when it was proposed as a PR but now that it is committed I'm running into issues.  Why have you got rid of `ddclient` file and replaced it with `ddclient.template`?  And why has the template file got rid of the `#!/usr/bin/perl` shebang.  The template file is no longer automatically recognized as a Perl file by text editors (for syntax highlighting).  And what about all existing pull requests on the original ddclient file.  I think this is going to cause major disruption for platforms that have adopted ddclient for its simplicity and install simply by copying ddclient file.

**Comment by rhansen** [comment]
> Why have you got rid of `ddclient` file and replaced it with `ddclient.template`?

See 8cbcecba99324c000662badc160784c3011cfb64 and PR #161. The `ddclient` file is now "built" from the template file.

> The template file is no longer automatically recognized as a Perl file by text editors (for syntax highlighting).

Yeah, we need to add some magic strings to teach Emacs and Vim that this is a Perl file. In the meantime you'll have to manually tell your editor.

I had expected `perl ./ddclient.template` to work, but it looks like Perl itself is attempting to interpret `#!@PERL@`. I need to figure out how to disable that or work around it.

>  And what about all existing pull requests on the original ddclient file.

As [stated in the contributor guide](https://github.com/ddclient/ddclient/blob/master/CONTRIBUTING.md#git-hygiene), contributors are expected to keep their pull requests rebased on top of `master`. Git's rename detection should detect the rename and do the right thing. If `master` has diverged too much from your branch, you may need to lower the detection threshold via `-Xfind-renames=n`.

>  I think this is going to cause major disruption for platforms that have adopted ddclient for its simplicity and install simply by copying ddclient file.

It is unfortunate that users can no longer copy the script file to install it, but the long-term benefits outweigh the costs. It's not difficult to run `./configure && make`, and having a build system both makes it easier for packagers to create distribution packages and allows us to implement some important features.

**Comment by dkerr64** [comment]
Just ran into another issue... the `.template `file name is interpreted by MacOS as being a Pages file (their word processor).  So it has a pages icon in finder and default open action is to open pages.  Isn't there a better way?

Same for the `.conf.template` file.  For that could we use .sample?  or just leave it as .conf?

**Comment by rhansen** [comment]
Both the `ddclient` template file and the `ddclient.conf` template file need to have the same extension, but it doesn't need to be `.template`. It's common to use `.in`; I avoided that because it's also used for Autoconf templates.
