### ISSUE TITLE
Mention that you can run the github actions locally

### ISSUE THREAD

**Issue by SuperSandro2000** [ddclient/ddclient#217]
I think we should recommend https://github.com/nektos/act in the contributions guide.

If you are heavily testing stuff it is faster to run the tests locally instead of pushing all the time. This also allows you to debug them in a broader way and test your changes while developing with all supported distros.

**Comment by rhansen** [comment]
A quick "how-to" would be nice too.

**Comment by SuperSandro2000** [comment]
``sudo act -j test-centos6``
