### ISSUE TITLE
Add repology badge?

### ISSUE THREAD

**Issue by SuperSandro2000** [ddclient/ddclient#226]
Do we want to add a badge like the one below to the readme? They also have several other badges available here https://repology.org/project/ddclient/badges.

![](https://repology.org/badge/vertical-allrepos/ddclient.svg)

**Comment by rhansen** [comment]
I like it!

**Comment by SuperSandro2000** [comment]
Now is the question where to put it because it is so large.

**Comment by rhansen** [comment]
At the top of the installation section?
