### ISSUE TITLE
Add support for curl as an option in geturl()

### ISSUE THREAD

**Issue by dkerr64** [ddclient/ddclient#232]
ddclient currently uses Perl modules for network access.  As support for SSL and IPv6 is added this places additional requirements on host systems to have the necessary modules that are not always installed by default or even available.  An alternate method for network access would be to use curl.

This off loads the intricacies to another package and gives the user choice based on their requirements or system capabilities.  This would be an additional option and not remove current network code (at least initially)

**Comment by rhansen** [comment]
PR #233 runs the curl binary, but I'm not convinced that is the appropriate way to go. [WWW::Curl](https://metacpan.org/pod/WWW::Curl) is available even on old distributions, and using it might avoid hassles such as escaping metacharacters or keeping error codes in sync.

[LWP](https://metacpan.org/pod/LWP) is also ubiquitous, and integrates well with other Perl modules such as HTTP::Request. I believe it is also pure Perl (no C extensions).

**Comment by dkerr64** [comment]
> PR #233 runs the curl binary, but I'm not convinced that is the appropriate way to go. [WWW::Curl](https://metacpan.org/pod/WWW::Curl) is available even on old distributions, and using it might avoid hassles such as escaping metacharacters or keeping error codes in sync.
> 
> [LWP](https://metacpan.org/pod/LWP) is also ubiquitous, and integrates well with other Perl modules such as HTTP::Request. I believe it is also pure Perl (no C extensions).

WWW::Curl is not installed by default on any system I tried.

The primary issue is maintaining compatibility with the simplest of systems, and specifically router/gateway devices that might be running things like DD-WRT or similar.  These systems cannot easily add Perl modules but they do typically have curl (or wget) as cmd-line tools.  So my goal is not to replace IO::System with something more elegant, it is to provide something that will work on the most basic of systems. @abelbeck FYI.

**Comment by SuperSandro2000** [comment]
> even on old distributions

Centos 6 has a package for it and it usually has no package for anything we want to use.

https://centos.pkgs.org/6/centos-x86_64/perl-WWW-Curl-4.09-4.el6.x86_64.rpm.html

> WWW::Curl is not installed by default on any system I tried.

If you are going to install ddclient with your package manager this is not a problem.

> DD-WRT

Has a [package system](https://wiki.dd-wrt.com/wiki/index.php/Quick_list_of_Optware_packages) and then the devs need to add one package for ddclient. I think this shouldn't be to much extra work.

> Perl modules but they do typically have curl (or wget) as cmd-line tools

We could include them in the ddclient script. Also we do not know if this is a fully featured curl/wget or only a busybox applet or a stripped down version or some horrible out of date curl binary. Worst case we need to vendor some files for those systems.

> more elegant, it is to provide something that will work on the most basic of systems

It is not about elegance per se. It is about maintaining an interface to curl without doing it completely ourselves.

**Comment by rhansen** [comment]
OpenWRT has a package for WWW::Curl: https://openwrt.org/packages/pkgdata/perl-www-curl

I don't know if DD-WRT is still active, but it looks like [Entware](https://github.com/Entware/Entware/wiki) is the newest way to install packages on DD-WRT. There is a WWW::Curl package: http://bin.entware.net/armv7sf-k3.2/Packages.html

**Comment by dkerr64** [comment]
Fixed in PR #233
