### ISSUE TITLE
cloudflare special characters in zone name: No zone ID found

### ISSUE THREAD

**Issue by Enteerman** [ddclient/ddclient#259]
when the domain name contains a special character (in my case it was U+0335), it exits with error 
```
RECEIVE:  {"result":[{"id":"***","name":"zone.name","status":"active"
...
FAILED:   updating zone.name: No zone ID found.
```

**Comment by rhansen** [comment]
It exits? It doesn't just log an error and try again later?

**Comment by Enteerman** [comment]
I'm unsure, it might try again later, but the error should persist. I also tried to pass a punycode encoded zone name, but it looks like it compares the encoded name with the response, which was decoded raw name.

**Comment by rhansen** [comment]
I still don't understand the problem you are experiencing and need more information before I can help:
  * What is your configuration?
  * What do you expect ddclient to do?
  * What is it actually doing? (Please paste `verbose=yes debug=yes` logs with sensitive information censored out.)

**Comment by Enteerman** [comment]
It seems to be working now.
