### ISSUE TITLE
ddclient should not create directories during runtime

### ISSUE THREAD

**Issue by dkerr64** [ddclient/ddclient#260]
I may be late to the party but I just got bit by PR #242 which addressed Issue #76 and I do see a lot of discussion there.  But I thought the resolution to the issue was to require that the directory was created during install and not do it during runtime.  But #242 does exactly that.

The reason I am hurt by it is because the code now requires `File::Path` which is not available on our Astlinux platform.  At a minimum we should make that an optional load only if it is needed.  Or could just use `mkdir` ?

**Comment by rhansen** [comment]
File::Path is a core module. We expect all core modules to be available, and we will be continually adding and removing dependencies on core modules as needed without warning or hesitation. As stated in the [Compatibility section of the contributor guide](https://github.com/ddclient/ddclient/blob/master/CONTRIBUTING.md#compatibility), "We are not interested in supporting platforms that lack some core Perl modules, unless doing so is trivial."

**Comment by dkerr64** [comment]
@rhansen Yes that is what I expected, but you know... I had to weigh in with my grievance.  Now what is the definition of trivial... would you for example accept a PR that tested if File::Path was available and if not just reverted to previous behavior?  I can't think of anything more simple than that?
@abelbeck FYI.

**Comment by rhansen** [comment]
> would you for example accept a PR that tested if File::Path was available and if not just reverted to previous behavior? I can't think of anything more simple than that?

That is conceptually simple, but non-trivial from a code maintenance perspective. It's more lines to maintain, and more branches that should be covered by unit tests. There's also a cold-path case—an execution path that is almost never taken. Bugs love to hide in code-path code.

But beyond those technical issues, there are much bigger problems with supporting systems that lack core modules:
  * It takes time away from feature development and code cleanup that most users value far more.
  * I don't enjoy debating what core modules I am allowed to use. Working on ddclient is something I do in my spare time, and the less fun it becomes, the less I will work on it.
  * It should be easy for random people to understand the code and contribute to ddclient. Conditional import logic impairs readability, which scares away potential contributors. Telling them to wrap their core module imports in conditional logic also scares them away. It's not good for the long-term health of the project.

The time I've spent typing this response is probably much greater than the time it would take to just add File::Temp to AstLinux. It's not a good trade-off. Until there a compelling use case arises, I don't want to have this debate again.
