### ISSUE TITLE
Generic protocol

### ISSUE THREAD

**Issue by maichai** [ddclient/ddclient#270]
I have by now spent so much time on finding out how I could cover a dynamic dns provider that is not yet in the current release (such as mydns.jp, yes, I saw it might be coming in another release, but hey, who has the time?) that it would have probably been quicker making a small curl-based script.

I do not understand why ddclient does not offer a generic protocol in the form of a format string that lets you set the http(s) URL as the DDNS provider expects it and fill in the proper information using placeholder variables. It would be very helpful for those who know to use this and who don't want to wait for the next release and to provide all the information to update ddclient just to integrate this provider.

Is something like this planned?

**Comment by SuperSandro2000** [comment]
Nothing like this is planned because it is usually not that easy. Some provider allow this but others require you to get some kind of token first and then submit it later or that you don't use query parameter but something in the body and the rabbit hole down we go.

**Comment by maichai** [comment]
The token you usually get one-off during registration, why would that be a problem for address refresh? it can just be put literally in the URL...

I see that you think it is too complex. We can agree that we disagree on this issue and that I have to do this for myself.

**Comment by SuperSandro2000** [comment]
I just wanted to say that it is not always as easy as you describe and there are certainly cases which would be harder. We use a similar approach for getting the IP from routers but it does not work for all.

**Comment by kovachwt** [comment]
My provider (Zonomi) doesn't even require me to send anything, I can just literally do a HTTP GET to a specific URL (which has the hostname and token embedded in it), and it will automatically update the host with the IP address of the device that called it.

So I just need to be able to specify a static URL, and have ddclient call that URL when the IP changes. It doesn't have to do anything else, like replace tokens or set headers or do authentication, just literally call a simple static HTTP GET and that's it.

Can we get a protocol=generichttpget please?

**Comment by DarthGandalf** [comment]
I'd like something like `protocol=cmd`, which would call an external script. Then I can put to that script whatever I want, e.g. a call to `curl`. DDclient could pass the IPs to it either via environment, or via command line.

**Comment by yearski** [comment]
A simple HTTP method would also cover internet.bs DNS through their "reseller API". This would need a POST with a template string. I understand "it's not always as easy as..." but it might be easy enough to cover the majority of the use cases. Having said that, I would second @DarthGandalf idea to simply put the burden on the end user to write their own script
> I'd like something like `protocol=cmd`, which would call an external script.
This would enable a solution for every corner case.

**Comment by Podden** [comment]
I would second this. Our Hoster wint.global just want me to call this kind of URL
https://api.org-dns.com/dyndns/?user=******&key=*******&domain=*******
and gives back different strings for success or failure.

The old ddns plugin of opnsense would allow this with ease and I really don't understand why you feel the need to restrict this. I understand this is an effort to safety in the UI but you could just hide this better from newbies. Experienced IT staff like me feel patronized with this kind of decisions.

Apart from this, thank you all for the hard work on there projects!

**Comment by dbell37** [comment]
> My provider (Zonomi) doesn't even require me to send anything, I can just literally do a HTTP GET to a specific URL (which has the hostname and token embedded in it), and it will automatically update the host with the IP address of the device that called it.
> 
> So I just need to be able to specify a static URL, and have ddclient call that URL when the IP changes. It doesn't have to do anything else, like replace tokens or set headers or do authentication, just literally call a simple static HTTP GET and that's it.
> 
> Can we get a protocol=generichttpget please?

Ditto. My provider (Ionos) only supports Dynamic DNS updates via a static HTTP request too. They use the IP the request is coming from to update my Dynamic DNS IP. 
I use OpnSense as my router and they have now dropped support for the legacy DynDNS plugin which supported Update URLs. They now only allow ddclient. I’m going to hack together a janky Cronjob for now. 
With more providers switching to the static HTTP request update method, can we reconsider adding this feature?
:)

**Comment by SuperSandro2000** [comment]
This is a feature request and feature requests in the form of issues are no longer accepted.

**Comment by gitwittidbit** [comment]
How should a feature request be submitted now?

**Comment by LenardHess** [comment]
Please open a new issue for discussions of new feature requests
