### ISSUE TITLE
Non Standard Ports

### ISSUE THREAD

**Issue by martinkeat** [ddclient/ddclient#271]
Sorry for raising this as an issue but I cannot for the life of me, find the answer anywhere else.

With respect to ddclient on google domains using a CENTOS 7 system, I am having to use a non-standard port (rather than 80) for HTTP traffic. How do I update the port on google through ddclient, or does it just do it automatically.

Martin

**Comment by SuperSandro2000** [comment]
ddclient only handles DNS and on that level ports do not matter.
