### ISSUE TITLE
Support for mydns.jp

### ISSUE THREAD

**Issue by maichai** [ddclient/ddclient#273]
I have seen that there was already some code for mydns.jp. I am wondering why it has not been merged into the release.
Actually it is not difficult to support:

https://www.mydns.jp/directip.html?MID=<userid>&PWD=<password>&IPV4ADDR=<ipv4 address>&IPV6ADDR=<ipv6 address>
you may omit either IPV4ADDRESS or IPV6ADDRESS

Is it possibly to say where on the road map it is (for what release)?

**Comment by sanpei3** [comment]
This requests related to https://github.com/ddclient/ddclient/pull/81.

**Comment by SuperSandro2000** [comment]
Site no longer exists
