### ISSUE TITLE
Why are defaults defined twice?

### ISSUE THREAD

**Issue by dkerr64** [ddclient/ddclient#276]
Looking at `%variables` we have `global-defaults`, `service-common-defaults` and `dyndns-common-defaults`.  And some entries like `use`, `if`, `web`, etc are defined in both global and service-common... with the same values.  Is there a good reason for this?  I'm thinking that they need only be defined in one place?

And why is `dyndns-common-defaults` part of `%variables` rather than in `%services` ?

Thanks

**Comment by SuperSandro2000** [comment]
This is a feature request and feature requests in the form of issues are no longer accepted.
