### ISSUE TITLE
Cannot update multiple domains via OVH

### ISSUE THREAD

**Issue by Azratosh** [ddclient/ddclient#277]
I've got a pretty standard configuration with multiple domains corresponding to one login. All domains point to the same host and have the same IP for various purposes. Using the same configuration with a single domain works perfectly fine, but updating multiple domains fails. 

### ddclient.conf (version 3.8.3, debian buster)
daemon=305
protocol=dyndns2
server=www.ovh.com
use=web,web=ifconfig.me/ip
ssl=yes

login=example.com-myusername
password='password'
sub1.example.com
sub2.example.com
sub3.example.com

### logs
```
DEBUG:    proxy  =
DEBUG:    url    = ifconfig.me/ip
DEBUG:    server = ifconfig.me
CONNECT:  ifconfig.me
CONNECTED:  using HTTP
SENDING:  GET /ip HTTP/1.0
SENDING:   Host: ifconfig.me
SENDING:   User-Agent: ddclient/3.8.3
SENDING:   Connection: close
SENDING:
RECEIVE:  HTTP/1.0 200 OK
RECEIVE:  Date: Sat, 15 Aug 2020 19:08:03 GMT
RECEIVE:  Content-Type: text/plain; charset=utf-8
RECEIVE:  Content-Length: 12
RECEIVE:  X-Powered-By: Express
RECEIVE:  Access-Control-Allow-Origin: *
RECEIVE:  Via: 1.1 google
RECEIVE:
RECEIVE:  123.456.789.0
DEBUG:    get_ip: using web, ifconfig.me/ip reports 123.456.789.0
SUCCESS:  sub1.example.com: skipped: IP address was already set to 123.456.789.0.
DEBUG:
DEBUG:     nic_dyndns2_update -------------------
INFO:     setting IP address to 123.456.789.0 for sub2.example.com,sub3.example.com
UPDATE:   updating sub2.example.com,sub3.example.com
DEBUG:    proxy  =
DEBUG:    url    = http://www.ovh.com/nic/update?system=dyndns&hostname=sub2.example.com,sub3.example.com&myip=123.456.789.0
DEBUG:    server = www.ovh.com
CONNECT:  www.ovh.com
CONNECTED:  using SSL
SENDING:  GET /nic/update?system=dyndns&hostname=sub2.example.com,sub3.example.com&myip=123.456.789.0 HTTP/1.0
SENDING:   Host: www.ovh.com
SENDING:   Authorization: Basic YXpyYXRvLnNoLWRkbnM6cjNzZXRfbXlfMXA0ZGRyZXNzIQ==
SENDING:   User-Agent: ddclient/3.8.3
SENDING:   Connection: close
SENDING:
RECEIVE:  HTTP/1.1 200 OK
RECEIVE:  Date: Sat, 15 Aug 2020 19:08:04 GMT
RECEIVE:  Content-Type: text/plain; charset=UTF-8
RECEIVE:  Cache-Control: max-age=60
RECEIVE:  Expires: Sat, 15 Aug 2020 19:09:04 GMT
RECEIVE:  Vary: Accept-Encoding
RECEIVE:  Content-Language: fr
RECEIVE:  X-IPLB-Instance: 28081
RECEIVE:  X-CDN-Pop: sbg
RECEIVE:  X-CDN-Pop-IP:
RECEIVE:  X-Request-ID: 700514538
RECEIVE:  X-Cacheable: Not cacheable: no cache
RECEIVE:  Accept-Ranges: bytes
RECEIVE:  Connection: close
RECEIVE:
RECEIVE:  badfqdn
Missing argument in sprintf at /usr/sbin/ddclient line 1706.
FAILED:   updating sub2.example.com: badfqdn: unexpected status ()
```

`sub1.example.com` was updated on its own in a previous run, it has got nothing to do with this one.

To me it seems that ddclient uses OVH's URL to update all domains at once, instead of one URL per domain. Frankly, I had assumed OVH supported updating multiple domains like that, but apparently not; seems like you need to make a separate request for every domain.

I apologize if this issue had already been fixed in a different version of ddclient, I wasn't able to find anything on that unfortunately.

**Comment by Azratosh** [comment]
### Also posting my workaround here which allowed me to update all my domains:
In your OVH web manager, create a separate dynhost user for each dynhost you have. Then, fill out your `ddclient.conf` correspondingly:
```
# /etc/ddclient.conf

daemon=360
protocol=dyndns2
server=www.ovh.com
use=web,web=ifconfig.me/ip
ssl=yes

login=example.com-ddns-01
password='password!'
sub1.example.com

login=example.com-ddns-02
password='password!'
sub2.example.com

login=example.com-ddns-03
password='password!'
sub3.example.com
```

This correctly updates the IP for all domains. Not really elegant since you need a separate user for each domain, but does what it says on the box.

**Comment by SuperSandro2000** [comment]
This is a feature request and feature requests in the form of issues are no longer accepted.
