### ISSUE TITLE
Update EPEL 7 distribution

### ISSUE THREAD

**Issue by msgerbs** [ddclient/ddclient#278]
The current EPEL 7 version (3.8.3) does not contain support for cloudflare's v4 API which is now required. In effect, anyone using Centos 7/RHEL 7 and Cloudflare needs to manually install which is not ideal. I would like to politely ask that if possible the EPEl 7 repo gets updated with a newer release which supports the v4 API.

**Comment by SuperSandro2000** [comment]
We have no control over EPEL7. Ask the maintainers politely to update their version.

**Comment by msgerbs** [comment]
Sorry, I assumed you guys were the maintainers. EPEL doesn't make it easy for an outsider to figure this stuff out...
