### ISSUE TITLE
please add support for ddns-services ddnss.de + dnshome.de + freedns.afraid.org

### ISSUE THREAD

**Issue by RichardBeisser** [ddclient/ddclient#279]
specs:

https://www.ddnss.de/ua/help.php

https://www.dnshome.de/einrichtung.php

https://freedns.afraid.org/scripts/freedns.clients.php
You can also (alternatively) perform updates like this:
http://[USERNAME]:[PASSWORD]@freedns.afraid.org/nic/update?hostname=[DOMAIN]&myip=[IP]
(https/SSL is also optionally supported/available)

Thanks

**Comment by dkerr64** [comment]
FreeDNS is already supported.

**Comment by teplydat** [comment]
FreeDNS works for me. Here is the config: https://github.com/ddclient/ddclient/issues/283#issuecomment-986252971
