### ISSUE TITLE
Error freedns.afraid.org

### ISSUE THREAD

**Issue by RichardBeisser** [ddclient/ddclient#283]
Hello,

when I check syslog, I get errors for freedns.afraid.org from ddclient:

WARNING:  file /var/cache/ddclient/ddclient.cache, line 3: Invalid Value for keyword 'ip' = ''
WARNING:  file /var/cache/ddclient/ddclient.cache, line 15: Invalid Value for keyword 'ip' = ''
FAILED:   Could not get freedns update URLs from freedns.afraid.org

ddclient.conf:
protocol=freedns \
server=freedns.afraid.org \
login=secretUser \
password='secretPass' \
xx1.chickenkiller.com,xx2.mooo.com

ddclient.cache:
ddclient-3.9.1
...
atime=1598347169,host=xx1.chickenkiller.com,ip=,mtime=0,status=noconnect,warned-min-error-interval=0,warned-min-interval=0,wtime=0 xx1.chickenkiller.com
...
atime=1598347169,host=xx2.mooo.com,ip=,mtime=0,status=noconnect,warned-min-error-interval=0,warned-min-interval=0,wtime=0 xx2.mooo.com

Where is the error, and what can i do?

Thanks

**Comment by dkerr64** [comment]
Do you personally own chickenkiller.com and mooo.com?  If these are shared domains and you are just "borrowing" xx1 and xx2 then you will not be able to use the FreeDNS API to update them.  The reason it fails is because sometimes (but I think not always), FreeDNS presents a captcha for a human to respond to which an automated updater like ddclient cannot handle.  I never see this for domains that I personally own, but I regularly see it for top level domains owned by others that FreeDNS lets you create a subdomain on.

**Comment by RichardBeisser** [comment]
No, i am not the owner / registrar of these 2 TLDs.
I registered 2 subdomains at freedns.afraid.org
https://freedns.afraid.org/domain/registry/

I never heard of a DDNS-Service which uses captchas at the updating url. Everybody uses a client-tool to update the ip to the DDNS-Service.

Have you contacted FreeDNS about this?

On their website, they wrote something about a new API.
Is this a solution for the problem?

**Comment by teplydat** [comment]
I have the same issue.

Has somebody a solution for that?

**Comment by dkerr64** [comment]
@teplydat can you run with debug and verbose and see if that provides any clues please.

**Comment by teplydat** [comment]
I run it on ubuntu 20.04 LTS. Hence it is still version 3.8.3. But I compared the code and for freedns it seems there is no difference.

I deleted uninteresting parts.
'my-subdomain' and '<...>' blackened:
```
sudo ddclient -daemon=0 -debug -verbose -noquiet

WARNING:  file /var/cache/ddclient/ddclient.cache, line 3: Invalid Value for keyword 'ip' = ''
DEBUG:    get_ip: using web, http://dns.loopia.se/checkip/checkip.php reports <...>.
WARNING:  skipping update of my-subdomain.mooo.com from <nothing> to <...>.
WARNING:   last updated <never> but last attempt on Mon Apr 19 07:00:48 2021 failed.
WARNING:   Wait at least 5 minutes between update attempts.
```

my config:
```
sudo vi /etc/ddclient.conf

protocol=freedns
use=web, web=loopia
server=freedns.afraid.org
login=username #also tried with email
password='password'
my-subdomain.mooo.com
```

**Comment by MartinX3** [comment]
Still happening with ddclient 3.9.1
The project example is outdated since

```
Updated interface is now available.
Check out: dynamic update interface (version 2)!
Features: Shorter URLs, native IPv6
Released: February 17, 2016
```

**Comment by teplydat** [comment]
After spending some hours, I found a solution. It was only a misconfiguration.

OS: Ubuntu 21.10
ddclient: 3.9.1 (`ddclient -help | grep version`) - but I guess it works also for other versions

```
sudo vi /etc/ddclient.conf
ssl=yes
protocol=freedns
use=web, web=https://freedns.afraid.org/dynamic/check.php
server=freedns.afraid.org
login=myfreednsuser #user not email! lowercase! 
password='myFreednsPW'
somedomain.mooo.com
```

I think the ssl part did the trick.

Can someone confirm? @RichardBeisser @MartinX3

**Comment by ostridge** [comment]
> web=https://freedns.afraid.org/dynamic/check.php
Thanks for that -

I have ddclient latest armhf version 3.8.3 on raspbian (debian10) buster 
I edited the /usr/sbin/ddclient script to
[code=perl] #comment out lies 
#   'dnspark'    => { 'url' => 'http://ipdetect.dnspark.com/', 'skip' =>  'Current Address:', },  #line52
#  'dnspark'=> 1,                                                                                                                     #line316[/code]

Tried to edit in your https line for freedns without success.
Then copied your code into /etc/ddclient.conf [code]  ssl=yes,
  use=web, web-skip='dnspark', web='https://freedns.afraid.org/dynamic/check.php'[/code]
Results in:[code]#from# ddclient -query -verbose -noquiet
RECEIVE:
RECEIVE:  Detected IP : xxx.xx.xxx.xxx
RECEIVE:  HTTP_CLIENT_IP :
RECEIVE:  HTTP_X_FORWARDED_FOR :
RECEIVE:  REMOTE_ADDR : xxx.xx.xxx.xxx
use=web, web=https://freedns.afraid.org/dynamic/check.php address is xxx.xx.xxx.xxx[/code]
There is your confirmation.   I will check later if the daemon  does the updates.

**Comment by AntonioSun** [comment]
> Can someone confirm?

Not working for me. I use the following, while subsititude my login info:

```
ssl=yes
protocol=freedns
use=web, web=https://freedns.afraid.org/dynamic/check.php
server=freedns.afraid.org
login=myfreednsuser #user not email! lowercase! 
password='myFreednsPW'
mydomain.myserver
```

and this is what I get (`FAILED:   Could not get freedns update URLs from freedns.afraid.org`):

```
RECEIVE:  
RECEIVE:  Detected IP : 132....
RECEIVE:  HTTP_CLIENT_IP : 
RECEIVE:  HTTP_X_FORWARDED_FOR : 
RECEIVE:  REMOTE_ADDR : 132....
INFO:     forcing update of mydomain.myserver.
CONNECT:  freedns.afraid.org
CONNECTED:  using SSL
SENDING:  GET /api/?action=getdyndns&sha=c0c7...17 HTTP/1.0
SENDING:   Host: freedns.afraid.org
SENDING:   User-Agent: ddclient/3.9.1
SENDING:   Connection: close
SENDING:   
RECEIVE:  HTTP/1.1 200 OK
RECEIVE:  Server: nginx
RECEIVE:  Date: Sun, 13 Feb 2022 19:22:09 GMT
RECEIVE:  Content-Type: text/plain;charset=UTF-8
RECEIVE:  Connection: close
RECEIVE:  Vary: Accept-Encoding
RECEIVE:  X-Cache: MISS
RECEIVE:  
FAILED:   Could not get freedns update URLs from freedns.afraid.org
```

My machine:

```
$ apt-cache policy ddclient
ddclient:
  Installed: 3.9.1-7
  Candidate: 3.9.1-7
  Version table:
 *** 3.9.1-7 500
        500 http://deb.debian.org/debian bullseye/main amd64 Packages
        100 /var/lib/dpkg/status
     3.8.3-1.1 500
        500 http://deb.debian.org/debian buster/main amd64 Packages

$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux bullseye/sid
Release:        10.11
Codename:       buster
```

**Comment by suntong** [comment]
> Can someone confirm?

Not working for me. I use the following, while subsititude my login info:

```
ssl=yes
protocol=freedns
use=web, web=https://freedns.afraid.org/dynamic/check.php
server=freedns.afraid.org
login=myfreednsuser #user not email! lowercase! 
password='myFreednsPW'
mydomain.myserver
```

and this is what I get (`FAILED:   Could not get freedns update URLs from freedns.afraid.org`):

```
RECEIVE:  
RECEIVE:  Detected IP : 132....
RECEIVE:  HTTP_CLIENT_IP : 
RECEIVE:  HTTP_X_FORWARDED_FOR : 
RECEIVE:  REMOTE_ADDR : 132....
INFO:     forcing update of mydomain.myserver.
CONNECT:  freedns.afraid.org
CONNECTED:  using SSL
SENDING:  GET /api/?action=getdyndns&sha=c0c7...17 HTTP/1.0
SENDING:   Host: freedns.afraid.org
SENDING:   User-Agent: ddclient/3.9.1
SENDING:   Connection: close
SENDING:   
RECEIVE:  HTTP/1.1 200 OK
RECEIVE:  Server: nginx
RECEIVE:  Date: Sun, 13 Feb 2022 19:22:09 GMT
RECEIVE:  Content-Type: text/plain;charset=UTF-8
RECEIVE:  Connection: close
RECEIVE:  Vary: Accept-Encoding
RECEIVE:  X-Cache: MISS
RECEIVE:  
FAILED:   Could not get freedns update URLs from freedns.afraid.org
```

My machine:

```
$ apt-cache policy ddclient
ddclient:
  Installed: 3.9.1-7
  Candidate: 3.9.1-7
  Version table:
 *** 3.9.1-7 500
        500 http://deb.debian.org/debian bullseye/main amd64 Packages
        100 /var/lib/dpkg/status
     3.8.3-1.1 500
        500 http://deb.debian.org/debian buster/main amd64 Packages

$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux bullseye/sid
Release:        10.11
Codename:       buster
```

**Comment by ostridge** [comment]
# Configuration file for ddclient generated by debconf
# /etc/ddclient.conf
  daemon=300
#  syslog=yes
  ssl=yes,
  use=web, web-skip='dnspark', web='https://freedns.afraid.org/dynamic/check.php'
  mail=root,
  mail-failure=root,

  protocol=freedns,          \
  server=freedns.afraid.org, \
  login='username',          \
  password='mYpAsSwD',       \
 #my_dynamic_fqdn
examplesubdomain.domain.tld

# These services are alternatives for line 6
## not as dnspark  does not work use web-skip=   in line 6
## use=web,  web-skip='dnspark', web=checkip.dyndns.org
## use=web,  web-skip='dnspark', web=myip.dnsomatic.com
## use=web,  web-skip='dnspark', web=myip.dnsdynamic.org

==
ostridge
________________________________

**Comment by ostridge** [comment]
Oops by the way the file location with latest versions is changed to
# from
 /etc/ddclient
# To
 /etc/ddclient/ddclient.conf
# easiest way is to put it in both

==
Ozz
________________________________

**Comment by SuperSandro2000** [comment]
> easiest way is to put it in both

I would suggest to symlink.

**Comment by ostridge** [comment]
thanks

**Comment by cbean** [comment]
This is strange, with ddclient 3.9.1 everything worked like a charm, now with 3.10 it is broken, I get:

WARNING:  skipping update of xxxxx.mine.bz from <nothing> to 87.142.145.81.
WARNING:  last updated Mon Dec 12 17:09:57 2022 but last attempt on Mon Dec 12 17:09:57 2022 failed.
WARNING:  Wait at least 5 minutes between update attempts.
DEBUG:    Reply from 'ip -4 -o addr show dev pppoe scope global' :
DEBUG:    ------
DEBUG:    33: pppoe    inet 87.142.145.81 peer 62.155.242.125/32 scope global pppoe\       valid_lft forever preferred_lft forever
DEBUG:    ------
DEBUG:    get_ip: using if, pppoe reports 87.142.145.81

every 5 minutes ddclient complains about updating

**Comment by SuperSandro2000** [comment]
Looks the like parsing changed but from the log alone I don't see anything obvious.

**Comment by se9000** [comment]
3.9.1 works on freedns, while 3.10 does not.

The problem for 3.10 is, it updates perfectly and stores the ip address in cache file (but: "notconnected").
The log records unneccessary update attempts, although the ip address has not changed and the initial update was stated as successful. It seems that ddclient 3.10 does not correctly memorize the ip address it has updated - or it is not parsing the cache file or the response from freedns.afraid.org correctly. This leads to unnecessary update triggers.

WARNING: ddclient skipping update from <nothing> to xxx.xxx.xxx.xxx
WARNING: last updated xxxxx but last attempt on xxxxx failed.

There is definitely something wrong... reverting to 3.9.1 with the same ddclient.conf solves the problem for now.

**Comment by SuperSandro2000** [comment]
Yeah, the cache is a bit broken in 3.10.0

**Comment by tifoji** [comment]
Works on debian/derivatives
```

# ddclient configuration for FreeDNS.afraid.org
# This configuration was tested and confirmed working on Raspberry Pi OS Lite (64-bit)
#
# Ensure you replace placeholders with your actual FreeDNS account details.
#
# To get your 'YOUR_BASE64_TOKEN', visit: https://freedns.afraid.org/dynamic/
# Look for the "Direct URL" which will be in the format:
# https://freedns.afraid.org/dynamic/update.php?YOUR_BASE64_TOKEN=

# General ddclient settings
daemon=300              # Check for IP changes every 300 seconds (5 minutes)
timeout=10              # Timeout for network operations
syslog=yes              # Log messages to syslog for easy debugging (use 'sudo journalctl -u ddclient -f')
ssl=yes                 # Use SSL/TLS for secure communication with FreeDNS

# FreeDNS.afraid.org specific settings
protocol=freedns        # Specify the FreeDNS protocol
server=freedns.afraid.org # The FreeDNS update server

# How ddclient determines your public IP address
# This is crucial for FreeDNS.afraid.org
use=web, web=https://freedns.afraid.org/dynamic/check.php

# Authentication details for FreeDNS.afraid.org
# 'login' is your FreeDNS web login username (NOT your email)
# 'password' is the full base64 token found in your "Direct URL"
login=YOUR_WEB_LOGIN_USERNAME
password='YOUR_BASE64_TOKEN'

# Your hostname(s) to update
YOUR_HOSTNAME.com       # Replace with your actual FreeDNS hostname (e.g., myhome.freedns.app)
```
