### ISSUE TITLE
.cloud TLD not recognized by ddclient

### ISSUE THREAD

**Issue by rangulicon** [ddclient/ddclient#284]
It seems ddclient doesn't recognize .cloud as a valid TLD. There is no reference of my .cloud domain even being checked in the logs. I am using ddclient with CloudFlare with the following TLDs and all but the .cloud are working without issue.

.email - working fine
.us - working fine
.com - working fine
.cloud - NOT working

**Comment by rangulicon** [comment]
I think this may have something to do with CloudFlare. It seems it wasn't actually updating any of them for a few hours. I think I may have hit some sort of limit on consecutive API calls while I was testing. It is working now.

**Comment by SuperSandro2000** [comment]
We don't do any domain filtering of those kinds so it is always related to the DNS provider.
