### ISSUE TITLE
RFE: noip - confirm/touch the hostname 

### ISSUE THREAD

**Issue by bugsyb** [ddclient/ddclient#285]
Noip requires to confirm hostname every ~30 days despite i.e. using ddclient to update IP address. Even forced update or flip to other IP and back didn't get the timer reset.
It requires to use web UI and whilst investigating it shows to use:
https://my.noip.com/api/host/<hostname_id#>/touch</hostname_id#>

Could we get this implemented in ddclient? It would save me going to their UI every month just to make one click (annoying).

Thanks.

**Comment by dkerr64** [comment]
Would this bypass the captcha that no-ip requires?  As far as I know the need to confirm and the captcha is presented for non-paid accounts.

**Comment by bugsyb** [comment]
Once logged in, there was no captcha during last couple of months when done from browser - not sure if there ever was one (haven't seen or don't remember).

**Comment by dkerr64** [comment]
> Once logged in, there was no captcha during last couple of months when done from browser - not sure if there ever was one (haven't seen or don't remember).

It is possible that I get a captcha because I am using one of their shared domains rather than one I own?

**Comment by SuperSandro2000** [comment]
I could imagine that this could be against their ToS and if so could get your domain suspended. If someone could research that before anyone implements anything would be great.

**Comment by SuperSandro2000** [comment]
out of scope for ddclient
