### ISSUE TITLE
Installation instractions? .deb files

### ISSUE THREAD

**Issue by ineuw** [ddclient/ddclient#286]
Is there a .deb installation file? because the tarballs never work. Are there any up to date installation instructions?

**Comment by SuperSandro2000** [comment]
> Is there a .deb installation file?

Debian provides one but not this project.

> because the tarballs never work.

That is to little info to help you.

> Are there any up to date installation instructions?

https://github.com/ddclient/ddclient#manual-installation

**Comment by ineuw** [comment]
Apologies for the late reply and thanks for the info.
