### ISSUE TITLE
Release more often

### ISSUE THREAD

**Issue by mike2307** [ddclient/ddclient#288]
Issues like [this one](https://github.com/ddclient/ddclient/issues/272) do exist only due to the fact that the [fix](https://github.com/ddclient/ddclient/pull/102) doesn't appear in any release.
Please trigger a release that contains https://github.com/ddclient/ddclient/pull/102 at least.

Thanks a lot in advance.

**Comment by SuperSandro2000** [comment]
I am aware that a new release is needed but there are at least two more PRs we want to  get merged before that. It will probably take a bit cause the recent lack of activity.

**Comment by jlsalvador** [comment]
Please @SuperSandro2000 , can you re-considerate it?
What do you need? Do you need some help? What are the other PRs that you like to be merged before another release?

**Comment by DaveSophoServices** [comment]
What’s involved in creating a release? Is there a document I could follow?

**Comment by SuperSandro2000** [comment]
I think https://github.com/ddclient/ddclient/pull/291 needs to be looked at and then we would need to do some more testing if any of the bigger providers broke. I also cannot update the website.

**Comment by ZLima12** [comment]
Can we just cherry-pick the fix for Cloudflare and bump the version?
