### ISSUE TITLE
ddclient 'use=' tag for pppoe IP addresses

### ISSUE THREAD

**Issue by kaushalsapre** [ddclient/ddclient#289]
I am using ddclient with google domains. The authentication works fine, but I can't get ddclient to send the right IP address to google domains. My public ip as defined by ipcanhazip is 183.x.x.x. My ISP is likely using a carrier grade NAT to assign an ip address to me. As a result, the WAN ip address on my router's homepage is 10.x.x.x(PPPOE). My private ip assigned to me by my server is 192.x.x.x

When I change my ddclient.conf to - 
1. use=web
get_ip: using web, web reports 183.x.x.x 
IP address set to 183.x.x.x
but url gets timed out
2. use=if, if=eth0
get_ip: using if, eth0 reports 192.x.x.x 
IP address set to 192.x.x.x
but url gets timed out
3. use=if, if=ppp0
get_ip: using if, ppp0 reports <undefined>
unable to determine IP address
url gets timed out. 

how do I use ddclient to update the right IP address to my DNS?

FYI: I can access my website when I type both 192.x.x.x and 10.x.x.x on my browser while I am connected to the ISP's network.

**Comment by dkerr64** [comment]
@kaushalsapre the use=web is the correct method to use and it looks like ddclient is finding your external IP just fine, the problem appears to be when updating at google domains.  Have you run with debug enabled to track down exactly where it times out?

**Comment by kaushalsapre** [comment]
So I ran the following command with use=web - 

<details>
<summary>sudo ddclient -daemon=0 -debug -verbose -noquiet</summary>

=== opt ====
opt{cache}                           : <undefined>
opt{cmd}                             : <undefined>
opt{cmd-skip}                        : <undefined>
opt{daemon}                          : 0
opt{debug}                           : 1
opt{exec}                            : <undefined>
opt{facility}                        : <undefined>
opt{file}                            : <undefined>
opt{force}                           : <undefined>
opt{foreground}                      : <undefined>
opt{fw}                              : <undefined>
opt{fw-login}                        : <undefined>
opt{fw-password}                     : <undefined>
opt{fw-skip}                         : <undefined>
opt{geturl}                          : <undefined>
opt{help}                            : <undefined>
opt{host}                            : <undefined>
opt{if}                              : <undefined>
opt{if-skip}                         : <undefined>
opt{ip}                              : <undefined>
opt{login}                           : <undefined>
opt{mail}                            : <undefined>
opt{mail-failure}                    : <undefined>
opt{max-interval}                    : 2592000
opt{min-error-interval}              : 300
opt{min-interval}                    : 30
opt{options}                         : <undefined>
opt{password}                        : <undefined>
opt{pid}                             : <undefined>
opt{postscript}                      : <undefined>
opt{priority}                        : <undefined>
opt{protocol}                        : <undefined>
opt{proxy}                           : <undefined>
opt{query}                           : <undefined>
opt{quiet}                           : 0
opt{retry}                           : <undefined>
opt{server}                          : <undefined>
opt{ssl}                             : <undefined>
opt{syslog}                          : <undefined>
opt{test}                            : <undefined>
opt{timeout}                         : <undefined>
opt{use}                             : <undefined>
opt{usev6}                           : <undefined>
opt{verbose}                         : 1
opt{web}                             : <undefined>
opt{web-skip}                        : <undefined>
=== globals ====
globals{daemon}                      : 60
globals{debug}                       : 1
globals{fw}                          : 192.168.0.1
globals{login}                       : xxxxxxxxxxxxxxxx
globals{password}                    : xxxxxxxxxxxxxxxxx
globals{protocol}                    : googledomains
globals{quiet}                       : 0
globals{server}                      : domains.google.com
globals{ssl}                         : 1
globals{use}                         : web
globals{verbose}                     : 1
=== config ====
config{thismightnotbe.online}{atime} : 0
config{thismightnotbe.online}{cacheable} : ARRAY(0x9860c0)
config{thismightnotbe.online}{cmd}   : <undefined>
config{thismightnotbe.online}{cmd-skip} : 
config{thismightnotbe.online}{fw}    : 192.168.0.1
config{thismightnotbe.online}{fw-login} : <undefined>
config{thismightnotbe.online}{fw-password} : 
config{thismightnotbe.online}{fw-skip} : 
config{thismightnotbe.online}{host}  : thismightnotbe.online
config{thismightnotbe.online}{if}    : ppp0
config{thismightnotbe.online}{if-skip} : 
config{thismightnotbe.online}{ip}    : <undefined>
config{thismightnotbe.online}{login} : xxxxxxxxxxxxx
config{thismightnotbe.online}{max-interval} : 2592000
config{thismightnotbe.online}{min-error-interval} : 300
config{thismightnotbe.online}{min-interval} : 300
config{thismightnotbe.online}{mtime} : 0
config{thismightnotbe.online}{password} : xxxxxxxxxxxxxx
config{thismightnotbe.online}{protocol} : googledomains
config{thismightnotbe.online}{server} : domains.google.com
config{thismightnotbe.online}{status} : 
config{thismightnotbe.online}{use}   : web
config{thismightnotbe.online}{usev6} : <undefined>
config{thismightnotbe.online}{warned-min-error-interval} : 0
config{thismightnotbe.online}{warned-min-interval} : 0
config{thismightnotbe.online}{web}   : dyndns
config{thismightnotbe.online}{web-skip} : 
config{thismightnotbe.online}{wtime} : 30
=== cache ====
cache{thismightnotbe.online}{atime}  : 1600711782
cache{thismightnotbe.online}{backupmx} : 0
cache{thismightnotbe.online}{custom} : 0
cache{thismightnotbe.online}{host}   : thismightnotbe.online
cache{thismightnotbe.online}{ip}     : 183.83.210.73
cache{thismightnotbe.online}{mtime}  : 1600711782
cache{thismightnotbe.online}{mx}     : 
cache{thismightnotbe.online}{script} : /nic/update
cache{thismightnotbe.online}{static} : 0
cache{thismightnotbe.online}{status} : good
cache{thismightnotbe.online}{warned-min-error-interval} : 0
cache{thismightnotbe.online}{warned-min-interval} : 0
cache{thismightnotbe.online}{wildcard} : 0
cache{thismightnotbe.online}{wtime}  : 30
DEBUG:    proxy  = 
DEBUG:    url    = http://checkip.dyndns.org/
DEBUG:    server = checkip.dyndns.org
Redundant argument in sprintf at /usr/sbin/ddclient line 1706.
DEBUG:    opt(fw = 
DEBUG:    glo fw = 192.168.0.1
CONNECT:  checkip.dyndns.org
CONNECTED:  using HTTP
SENDING:  GET / HTTP/1.0
SENDING:   Host: checkip.dyndns.org
SENDING:   User-Agent: ddclient/3.8.3
SENDING:   Connection: close
SENDING:   
RECEIVE:  HTTP/1.1 200 OK
RECEIVE:  Content-Type: text/html
RECEIVE:  Server: DynDNS-CheckIP/1.0.1
RECEIVE:  Connection: close
RECEIVE:  Cache-Control: no-cache
RECEIVE:  Pragma: no-cache
RECEIVE:  Content-Length: 105
RECEIVE:  
RECEIVE:  <html><head><title>Current IP Check</title></head><body>Current IP Address: 183.x.x.x</body></html>
DEBUG:    get_ip: using web, http://checkip.dyndns.org/ reports 183.x.x.x
SUCCESS:  thismightnotbe.online: skipped: IP address was already set to 183.x.x.x

</details>

This ip address also gets updated to my domains.google.com console, but trying to access my url from my browser results in a 'site took too long to respond' message. 

this is how my ddclient.conf file looks like - 
<details>
<summary>sudo nano ddclient.conf</summary>

daemon=300
protocol=googledomains
use=web
fw=192.168.0.1
ssl=yes
server=domains.google.com
login='xxxxxxxxxxxxxx'
password='xxxxxxxxxxxx'
thismightnotbe.online


</details>

 **Have you run with debug enabled to track down exactly where it times out?**

I'm not sure what you meant by this. Should I run some other debug?

**Comment by dkerr64** [comment]
> This ip address also gets updated to my domains.google.com console, but trying to access my url from my browser results in a 'site took too long to respond' message.

This doesn't look like a problem with ddclient.  As the debug log states, your IP address is already correctly set at google domains.  If your web browser is not able to access your site, then that suggests a network problem... firewall or something.

**Comment by kaushalsapre** [comment]
Understood. 

I guess this issue could be closed. But I was also wondering if you could point me in the right direction to try and debug this problem. I'm pretty sure that my system firewall (ufw) and my router firewall have their ports 80 and 443 open. I'm trying to self host a website on an odroid using a consumer ISP connection. I've tried everything short of contacting my ISP (who I guess is using a CGNAT) and request a static IP address (they'll charge me thrice of what I am paying to do that). 

Thanks for all your help!

**Comment by dkerr64** [comment]
> Understood.
> 
> I guess this issue could be closed. But I was also wondering if you could point me in the right direction to try and debug this problem. I'm pretty sure that my system firewall (ufw) and my router firewall have their ports 80 and 443 open. I'm trying to self host a website on an odroid using a consumer ISP connection. I've tried everything short of contacting my ISP (who I guess is using a CGNAT) and request a static IP address (they'll charge me thrice of what I am paying to do that).
> 
> Thanks for all your help!

You should start by checking that you can access your system from outside using raw IP addresses... take DNS out of the path.  Start with ping, then maybe try SSH or HTTP.  From your original text you have multiple gates to pass through as it looks like your gateway WAN has been assigned a private 10.x.x.x address, so the public IP address 183.x.x.x is not even assigned to your gateway.  Feels like some sort of NAT'ing is going on.
