### ISSUE TITLE
Fix for IPV6

### ISSUE THREAD

**Issue by armonica17** [ddclient/ddclient#290]
I use zoneedit for my DNS. I found that no matter what I set in the config file ddclient wouldn't update ipv6 records. I can't seem to make a branch. Here's the fix:
```

diff --git a/ddclient.in b/ddclient.in
index b6db09c..279513b 100755
--- a/ddclient.in
+++ b/ddclient.in
@@ -2320,7 +2320,12 @@ sub get_ip {
         $skip  =~ s/ /\\s/is;
         $reply =~ s/^.*?${skip}//is;
     }
-    $ip //= extract_ipv4($reply) // extract_ipv6($reply);
+    #    $ip //= extract_ipv4($reply) // extract_ipv6($reply);
+    if ($globals{'ipv6'} == 1 ) {
+        $ip = extract_ipv6($reply);
+    } else {
+        $ip //= extract_ipv4($reply)
+    }
     warning("found neither IPv4 nor IPv6 address") if !defined($ip);
     if ($use ne 'ip' && ($ip // '') eq '0.0.0.0') {
         $ip = undef;

```
Now all you have to do is have two config files. One for ipv4, one for ipv6. In the ipv6 file add ipv6=yes and it'll update it. This is tested code. As long as for zoneedit there is an entry for that machine in the dynamic record section, it'll work. For most of my machines I don't even bother with ipv4 any more. However I tested that as well and it updated the address. Ipv6 routes right into my internal network anywhere in the world. Otherwise it's a NAT. Just set everything up as zero trust. Comcast gives me a /64.

**Comment by dkerr64** [comment]
We have work underway to support IPv6 across all services.  Progress is documented in #172 and I need to have PR #233 and #266 merged in order to make progress.

**Comment by dkerr64** [comment]
I have opened PR #291 with the framework that will allow support of IPv6.  Zoneedit is not part of that, but it you want to see how we propose to support IPv6 look at it and how Cloudflare and FreeDNS are implemented.  Other services will, over time, move to use the new framework.

**Comment by armonica17** [comment]
Hi. I'm having no trouble with zoneedit with that change. The only problem I see is an error in the file:
WARNING:  file /usr/local/var/cache/ddclient/ddclient_int_ipv6.cache, line 3: Invalid Value for keyword 'ip' = ''
I have multiple ip addresses I'm watching. Public interface, ipv4, ipv6. Inside the FW - ipv6 only. So this one is for the internal ipv6. Sometimes it sets it, sometimes it doesn't. At least it was consistent. All 3 lost the ip address about the same time.

I messed up on Saturday I think. I rebooted my FW and forgot to restart dhclient. So comcast let my ipv6 block go. Just wonderful. Restarted it and added it to the reboot procedure, fixed radvd and that repopulated the ipv6 addresses. ddclient picked up the right one and updated zoneedit like clockwork.

**Comment by dkerr64** [comment]
> Hi. I'm having no trouble with zoneedit with that change. The only problem I see is an error in the file:
> WARNING: file /usr/local/var/cache/ddclient/ddclient_int_ipv6.cache, line 3: Invalid Value for keyword 'ip' = ''

If you are trying the PR #291 version then that is expected.  We will be replacing `ip` with `ipv4` in the cache file.  There will be a transition phase that existing caches with `ip` will cause a warning.  Eventually `ip` as a setting will go away.  I'll take a look and see if I can get rid of the warning to avoid causing concern.  Thanks.
