### ISSUE TITLE
use with miniupnpc

### ISSUE THREAD

**Issue by steve-lad** [ddclient/ddclient#293]
Hi, great dynamic dns client!

To remove dependance on external checkIP sites, with a Huawei 528s, and probably any other routeur that has upnp, the following solution works:

1. install miniupnpc
        sudo apt-get install miniupnpc

2. Enable upnp on the routeur

3. Modify ddclient.conf
       use=cmd, cmd='external-ip'

Hope this helps

**Comment by rautesamtr** [comment]
Maybe they could add https://metacpan.org/pod/Net::UPnP::GW::Gateway for external ip?
