### ISSUE TITLE
Add support for Cpanel-based DNS

### ISSUE THREAD

**Issue by majurgens** [ddclient/ddclient#294]
Can we look at adding support for the cpanel API?

A couple of documentation URLs:
https://documentation.cpanel.net/display/DD/Guide+to+cPanel+API+2
https://docs.cpanel.net/knowledge-base/security/how-to-use-cpanel-api-tokens/

I already did it in this project (https://github.com/majurgens/cpanel-dynamicdns-tools/blob/master/cpanel-dynamic-dns) but now that I think about it, it is probably more useful in ddclient.

Since ddclient is in perl I could look at it? Would this be ok? I'm not sure if you have any documentation to help someone add a new protocol to the code?

**Comment by SuperSandro2000** [comment]
This is a feature request and feature requests in the form of issues are no longer accepted.
