### ISSUE TITLE
Support for the deSEC service

### ISSUE THREAD

**Issue by JonasOlson** [ddclient/ddclient#297]
The protocol:
```
curl --user <your domain>.dedyn.io:<your authorization token> https://update.dedyn.io/?myipv4=1.2.3.4&myipv6=fd08::1234
```
Updates both IPv4 and IPv6 at the same time. If either address is set to the empty string, the corresponding DNS record is deleted.

[Documentation](https://desec.readthedocs.io/en/latest/dyndns/update-api.html)

They also provide URL:s for checking your IP addresses:

- https://checkip.dedyn.io/
- https://checkipv4.dedyn.io/
- https://checkipv6.dedyn.io/

**Comment by joekerna** [comment]
Do we need both of these commands?

```
curl --user <your domain>.dedyn.io:<your authorization token> \
  https://update.dedyn.io/?myipv4=1.2.3.4&myipv6=fd08::1234

curl https://update6.dedyn.io/?hostname=<your domain>.dedyn.io?myipv4=<1.2.3.4>&myipv6=<fd08::1234> \
  --header "Authorization: Token <your authorization token>"
```

**Comment by JonasOlson** [comment]
> Do we need both of these commands?
> 
> ```
> curl --user <your domain>.dedyn.io:<your authorization token> \
>   https://update.dedyn.io/?myipv4=1.2.3.4&myipv6=fd08::1234
> 
> curl https://update6.dedyn.io/?hostname=<your domain>.dedyn.io?myipv4=<1.2.3.4>&myipv6=<fd08::1234> \
>   --header "Authorization: Token <your authorization token>"
> ```

@joekerna: I don't think so. I think they constitute two ways of accomplishing the same thing.

**Comment by joekerna** [comment]
I've been using the following command in a daily cronjob for a while now and it's working fine

`curl --user DOMAIN.dedyn.io:TOKEN https://update.dedyn.io/?myipv4=$(curl https://checkipv4.dedyn.io)&myipv6=$(curl https://checkipv6.dedyn.io)`

The remaining task is to integrate it into `ddclient` and create a pull request.

**Comment by bagobones** [comment]
Should be noted that deSEC provides specific dyndns2 settings for ddclient already, probably could turn them into a named preset for users fairly easily.

https://desec.readthedocs.io/en/latest/dyndns/configure.html#option-2-use-ddclient

However using thier native REST API would probably be better https://desec.readthedocs.io/en/latest/dyndns/update-api.html

https://desec.readthedocs.io/en/latest/dyndns/update-api.html
