### ISSUE TITLE
Configure cloudflare 

### ISSUE THREAD

**Issue by kinggx9** [ddclient/ddclient#298]
My configuration:
```
use=web, web=dynamicdns.park-your-domain.com/getip
protocol=cloudflare
ttl=1
server=www.cloudflare.com
login=Account
password=Global API Key
zone=xxxx.com
xxxx.com
```
Can you tell me where is wrong?

**Comment by mike2307** [comment]
The cloudflare issue is a known one. See https://github.com/ddclient/ddclient/issues/288.
But the maintainer insists to to not release a new version until other issues are solved.
Be my guest...
