### ISSUE TITLE
Unrecognized Keyword 'usev6'

### ISSUE THREAD

**Issue by ftastisch** [ddclient/ddclient#299]
Hi!

I'm trying to update an IPv6 address with ddclient and just inserted my credentials into the example ddclient.conf of version 3.9.1, but only receive an error "unrecognized keyword 'usev6'". Is there still an issue with IPv6?

BR
Fo

---
edit: I'm using nsupdate.info, so I just changed the example config for the corresponding IPv6 update.

**Comment by dkerr64** [comment]
config parameter `usev6` is not implemented in the current release.  It requires merge of PR #291 and then implementing support for it in the various services (that pull request only implements Cloudflare and FreeDNS).  We need more people to review and test PR #291 before the maintainers feel comfortable to merge it.

**Comment by ftastisch** [comment]
Thank you for the quick help, @dkerr64 . Then it's just confusing when it's already shown in the example config. 🤷 

Then the follow up question would be: Is there a different parameter to update IPv6 already implemented or is this also just not possible yet? I read somewhere that IPv6 should be supported from 3.8.1 or 3.8.3 (don't remember exactly) onwards.

Thank you!

**Comment by dkerr64** [comment]
>Then it's just confusing when it's already shown in the example config.

That is the bug then !!  Odd that this slipped in without corresponding support for it.

**Comment by Pysis868** [comment]
Strange, saw this error with a similar situation, but using version 3.9.1, Fedora Linux Release 37.
