### ISSUE TITLE
can't use dyndns v3.9.1

### ISSUE THREAD

**Issue by boistordu** [ddclient/ddclient#300]
Hi,

I'm under ubuntu 20.10 
ddclient can't retrieve my information. 
the dyndns doesn't work because of a problem with python in ubuntu 20.10 so I went to try ddclient.

This is the message when I try to launch it :
`"my" variable $use masks earlier declaration in same scope at /usr/sbin/ddclient line 986.`

Besides of that when I configured it during the installation phase, it couldn't get any information of my account.

**Comment by boistordu** [comment]
More accurately it tells me that or my password is false or the host list is empty. 
The password is good I verified it in the conf file and try on the website and it worked.
So could it be that de client can't get the list anymore ?
What's the line to configure the host manually ?if possible of course

**Comment by fade2gray** [comment]
Just a thought. I haven't used ddclient for quite a while , but I'm sure I remeber having a prblem with a password that included some special characters other that alphanumeric ones - I'm sure they needed escaping somehow.

**Comment by boistordu** [comment]
@fade2gray  ow shit yeah then it must be it. 
escaping like for a ^ => \^ ?

**Comment by fade2gray** [comment]
Yeah, can't remember if backslash or backtick was used without firing up some old VMs and checking a bunch of configuration files. :/

**Comment by boistordu** [comment]
Can't seem to find the right combination.
What's odd is that it the password in conf file is in '...' so we shouldn't need \^

**Comment by SuperSandro2000** [comment]
If you still have trouble please add another comment.
