### ISSUE TITLE
Release early, release often

### ISSUE THREAD

**Issue by seblu** [ddclient/ddclient#302]
Hello,

The last release of ddclient will soon be one year old. There is interesting features and bug fixes (like a regression with use=ip) which would be nice to see downstream.
Would you mind consider issue a release?

Regards,

**Comment by SuperSandro2000** [comment]
You are right that there should be a release a long time ago but I currently allocate most of my time into other projects.

**Comment by rrthomas** [comment]
Is there something I can do to help get a new release out with some of the bug fixes & improvements that are already waiting to go? I'm a long-term user of ddclient (since at least 2006), the author of some of the PRs (e.g. support for Mythic Beasts and dnsexit), a maintainer of many free software projects, and a Debian Maintainer (i.e. not a full Debian Developer, but involved in the project).

**Comment by wimpunk** [comment]
You may join the team if you like. It's been a while since I've been looking into the project so I'm not sure about the current state.

**Comment by rrthomas** [comment]
@wimpunk I'd be delighted to!

**Comment by dkerr64** [comment]
I'll weigh in with my support here.  All my IPv6 support is queued up awaiting someone to merge it.  I'd also encourage that you create a "development" branch into which new features can be merged and tested before moving all over to "master" in preparation for release.  Hot fixes can go into master, but something like my IPv6 code should really go into a development branch as full support will take multiple PRs to get all services migrated over to the new structure.

This would allow more active development and testing without fear of breaking master branch.

David

**Comment by rrthomas** [comment]
@dkerr64, makes sense. I'd be inclined to create a release candidate branch quickly, with a few "quick wins"; your IPv6 code sounds like it should be on a branch of its own for a bit?

**Comment by dkerr64** [comment]
> @dkerr64, makes sense. I'd be inclined to create a release candidate branch quickly, with a few "quick wins"; your IPv6 code sounds like it should be on a branch of its own for a bit?

Yes, the IPv6 changes impact a lot of the code.  I would prefer it get merged into a "develop" branch so as to minimize risk. Then we can work on updating all the services one-by-one in that branch.

**Comment by rrthomas** [comment]
@wimpunk: I don't seem to have had an invitation from you yet (either in inbox or spam folder!)?

**Comment by SuperSandro2000** [comment]
>This would allow more active development and testing without fear of breaking master branch.

You shouldn't be running that branch anyway as it might be broken or have breaking changes.
