### ISSUE TITLE
ssl=yes forces SSL onto web providers that might not support SSL

### ISSUE THREAD

**Issue by JacobSnyder** [ddclient/ddclient#309]
I'm using the latest-and-greatest version of ddclient built from the master branch (commit hash 11a583b003920f8e15591813598b70061d1a4654) because I want to be able to use Cloudflare API Tokens which were merged in #102 but haven't been included in an official release yet.

What I'm seeing is that ddclient seems to be forcing SSL onto web providers even if they don't support SSL.

For example, here's the snippet from my config, where I'm using the default "dyndns" web provider:
```
verbose=yes
debug=yes
daemon=600
syslog=yes
pid=/usr/local/var/run/ddclient.pid
ssl=yes
use=web
```

Looking at my logs, I see:
```
DEBUG:    proxy    = <undefined>
DEBUG:    protocol = https
DEBUG:    server   = checkip.dyndns.org
DEBUG:    url      =
DEBUG:    ip ver   =
CONNECT:  checkip.dyndns.org
```

As you can see, the protocol has been forced to https.  However, dyndns doesn't accept https connections.  Dyndns will then hang, eventually, timing out after an absurdly long (5+ minutes, I'd guess), and print that the connection failed on port 443 (sorry that I don't have these logs handy).

I've confirmed that this configuration works in 3.9.1 and is a regression in master.

For now, I've worked around this by using the googledomains provider, which does accept https connections:
```
verbose=yes
debug=yes
daemon=600
syslog=yes
pid=/usr/local/var/run/ddclient.pid
ssl=yes
use=web
web=googledomains
```

Please let me know if there's any additional information I can provide to assist!  Thanks for maintaining this project!

**Comment by gerdneuman** [comment]
Yeah, fwiw, this results in the following error message:

```
WARNING:  cannot connect to checkip.dyndns.org:443 socket: Connection timed out SSL connect attempt failed
WARNING:  found neither IPv4 nor IPv6 address
DEBUG:    get_ip: using web, http://checkip.dyndns.org/ reports <undefined>
WARNING:  unable to determine IP address
```

Leaving this here for other people to better find the cause of it. I had the same problem with `master` (cause I want to use gandi.net) and searched the issue tracker without finding it.

**Comment by enricozb** [comment]
There are a list of hosts here that support ssl: https://github.com/ddclient/ddclient/blob/215d4679e4640c5975dd3983d3e2c0ebe7b0e140/ddclient.in#L107-L121,

you can switch to them by doing, using freedns as an example,
```
ssl=yes
use=web
web=freedns
```
perhaps `ssl=yes` should filter for these ssl-only ip strategies?

**Comment by brianread108** [comment]
I'm also suffering from this - my provider - noip.com only provides http for checking the ip address, but allows https for the update. 
It seems to me that a global parameter (ssl=yes) ought to work for all possible combinations of the other parameters. 

Can this be discussed further and I might be in a position to propose a fix to the code.

**Comment by brianread108** [comment]
After further thought I propose that if the web-service URL has "http" or "https" on it, then that is what is used. If they are missing then it adds one according to the setting of "ssl"?
