### ISSUE TITLE
Does this tool have any interface or something?

### ISSUE THREAD

**Issue by f1ames0ff** [ddclient/ddclient#315]
Configuring this tool is a pain. Does this tool have any interface or something?
After run it doesn't show even a simplest console. wtf is this?

**Comment by wimpunk** [comment]
Hi @f1ames0ff,

Ddclient is a daemon which, by default, doesn't show you anything on the console.  Try to run `ddclient -daemon=0 -debug -verbose -noquiet` if you want to see what's happening.  Or check your logging.
