### ISSUE TITLE
Linksys X6200 Dyndns.org stuck on Resolving Domain Name

### ISSUE THREAD

**Issue by SherifSarkis** [ddclient/ddclient#317]
Hi
My Linksys Modem Router X6200 is stuck on "Resolving Domain Name" and is not updating since March 17, it updated once but with the LAN IP 192.168.1.1, but nothing since then.
It was working fine for 2 years, and it's the first time to have this kind of issues. My Dyndns account is working fine on other devices, tried resetting the router and doing everything I can. I don't know if I need to provide more data.
Thanks

**Comment by wimpunk** [comment]
Is your router running `ddclient` or is it running the default linksys firmware?

**Comment by SherifSarkis** [comment]
Its running the default linksys firmware, but when I contacted dyndns.com they referred me to here

**Comment by wimpunk** [comment]
And are you using ddclient on another device to fetch the up from the Linksys? It sounds to me that ddclient isn't involved here. Looks like a big in the firmware of the Linksys router. Or your DNS isn't configured correctly.
