### ISSUE TITLE
Running as daemon, updated IP successfully one time, never agian?

### ISSUE THREAD

**Issue by ioogithub** [ddclient/ddclient#320]
I have the service running as a systemd service, configured to run as a deamon and update every 300s. It successfully updated my dynamic DNS provider once however it hasen't updated again since then (6 hours ago).

What am I missing?

Are there any logs to see when it makes a successful update or why it is failing?

```
pi@raspberrypi:$ systemctl status ddclient.service
● ddclient.service - LSB: Update dynamic domain name service entries
   Loaded: loaded (/etc/init.d/ddclient; generated)
   Active: active (running) since Thu 2021-03-25 00:19:10 EDT; 11min ago
     Docs: man:systemd-sysv-generator(8)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/ddclient.service
           └─3127 ddclient - sleeping for 230 seconds

Mar 25 00:19:10 raspberrypi systemd[1]: Starting LSB: Update dynamic domain name service entries...
Mar 25 00:19:10 raspberrypi systemd[1]: Started LSB: Update dynamic domain name service entries.
```
```
pi@raspberrypi:$ sudo cat /etc/ddclient.conf
# Configuration file for ddclient generated by debconf
#
# /etc/ddclient.conf

daemon=5m
protocol=dyndns2
fw=x.x.x.x
use=web, if=dyndns
server=ipv4.nsupdate.info
login=server
password='pw''
server
```

**Comment by ioogithub** [comment]
When my IP address changed, ddclient did not update anything so the server went offline.

**Comment by wimpunk** [comment]
Best thing to do is stop the service and run `ddclient -daemon=0 -debug -verbose -noquiet` to see what's happening.

**Comment by ioogithub** [comment]
Thanks, running this command manually worked and updated the name as expected. I don't see what is triggering it to run or why it isn't being triggered. Could you point me to more info on how to further troubleshoot?

**Comment by wimpunk** [comment]
Just a little note: `daemon=5m` should not be in your configuration file.  Debian-derived systems are use the info in `/etc/default/ddclient` for the daemon info.
You're using the ddclient package from your distribution, I suppose?  Mixing up a downloaded version with the package version may cause strange results.
Normally your syslog should have more info when updating, or at least if syslog is enabled.

**Comment by ioogithub** [comment]
> Just a little note: `daemon=5m` should not be in your configuration file. Debian-derived systems are use the info in `/etc/default/ddclient` for the daemon info.

I have this line: `daemon=5m`

however it is in `/etc/ddclient.conf.` Are you saying that on debian based systems, the actual configuration file used is not `/etc/ddclient.conf `but `/etc/default/ddclient`? If so, then what is `/etc/ddclient.conf` used for?

I checked /etc/default/ddclient and it just has the defaults:

```
# Configuration for ddclient scripts 
# generated from debconf on Wed 24 Mar 2021 07:45:59 PM EDT
#
# /etc/default/ddclient

# Set to "true" if ddclient should be run every time DHCP client ('dhclient'
# from package isc-dhcp-client) updates the systems IP address.
run_dhclient="false"

# Set to "true" if ddclient should be run every time a new ppp connection is 
# established. This might be useful, if you are using dial-on-demand.
run_ipup="false"

# Set to "true" if ddclient should run in daemon mode
# If this is changed to true, run_ipup and run_dhclient must be set to false.
run_daemon="true"

# Set the time interval between the updates of the dynamic DNS name in seconds.
# This option only takes effect if the ddclient runs in daemon mode.
daemon_interval="300"
```

I am using the version from my distribution:

```
pi@raspberrypi:~ $ apt list ddclient
Listing... Done
ddclient/stable,now 3.8.3-1.1 all [installed]
```

**Comment by wimpunk** [comment]
Sorry for the late reply, I don't spend that much time anymore on ddclient
I'm wrong, it looks like on debian it uses `/etc/ddclient.conf` and `/etc/default/ddclient`.  If you use ddclient from the repository it uses `/etc/ddclient/ddclient.conf`.
