### ISSUE TITLE
Gandi: WARNING:  file /etc/ddclient/ddclient.conf, line 208: Invalid Value for keyword 'ttl' = '3h'

### ISSUE THREAD

**Issue by gerdneuman** [ddclient/ddclient#326]
I am getting `WARNING:  file /etc/ddclient/ddclient.conf, line 208: Invalid Value for keyword 'ttl' = '3h'` when using the Gandi protocol as it is in the conf file:

https://github.com/ddclient/ddclient/blob/11a583b003920f8e15591813598b70061d1a4654/ddclient.conf.in#L206

So either the warning is false/wrong, or the default conf file.

**Comment by daxhuiberts** [comment]
It's missing a command at the end of that line, when added the error goes away.
