### ISSUE TITLE
Issue with deployment on K8S

### ISSUE THREAD

**Issue by fabricesemti80** [ddclient/ddclient#327]
Hi There!

I have deployed DDClient using Kubesail (https://kubesail.com/template/loopDelicious/ddclient )

This is my ddclient config:

`  ddclient.conf: |
    daemon=300
    syslog=yes
    protocol=cloudflare
    zone=fabricesemti.dev
    use=web
    web=https://domains.google.com/checkip
    ssl=yes
    ttl=1
    login=emilfabrice@gmail.com
    password=<API token removed>
    home.fabricesemti.dev`

The pod reports various errors:

![image](https://user-images.githubusercontent.com/37410363/115532238-83304800-a28d-11eb-9d9e-30ff4acebac5.png)

The debug log in the pod shows as follows:

`✘ fabrice@k8s-master01  ~  k exec --stdin --tty ddclient-deployment-6d9f949c9f-h9nlg -- /bin/bash
root@ddclient-deployment-6d9f949c9f-h9nlg:/# ddclient -daemon=0 -debug -verbose -noquiet
WARNING:  file /etc/ddclient/ddclient.conf: Cannot open file '/etc/ddclient/ddclient.conf'. (No such file or directory)
stat() on closed filehandle FD at /usr/bin/ddclient line 1167.
Use of uninitialized value $mode in bitwise and (&) at /usr/bin/ddclient line 1168.
readline() on closed filehandle FD at /usr/bin/ddclient line 1180.
WARNING:  file /etc/ddclient/ddclient.conf: Cannot open file '/etc/ddclient/ddclient.conf'. (No such file or directory)
stat() on closed filehandle FD at /usr/bin/ddclient line 1167.
Use of uninitialized value $mode in bitwise and (&) at /usr/bin/ddclient line 1168.
readline() on closed filehandle FD at /usr/bin/ddclient line 1180.
=== opt ====
opt{cache}                           : <undefined>
opt{cmd}                             : <undefined>
opt{cmd-skip}                        : <undefined>
opt{daemon}                          : 0
opt{debug}                           : 1
opt{exec}                            : <undefined>
opt{facility}                        : <undefined>
opt{file}                            : <undefined>
opt{force}                           : <undefined>
opt{foreground}                      : <undefined>
opt{fw}                              : <undefined>
opt{fw-banlocal}                     : <undefined>
opt{fw-login}                        : <undefined>
opt{fw-password}                     : <undefined>
opt{fw-skip}                         : <undefined>
opt{geturl}                          : <undefined>
opt{help}                            : <undefined>
opt{host}                            : <undefined>
opt{if}                              : <undefined>
opt{if-skip}                         : <undefined>
opt{ip}                              : <undefined>
opt{ipv6}                            : <undefined>
opt{login}                           : <undefined>
opt{mail}                            : <undefined>
opt{mail-failure}                    : <undefined>
opt{max-interval}                    : 2160000
opt{min-error-interval}              : 300
opt{min-interval}                    : 30
opt{options}                         : <undefined>
opt{password}                        : <undefined>
opt{pid}                             : <undefined>
opt{postscript}                      : <undefined>
opt{priority}                        : <undefined>
opt{protocol}                        : <undefined>
opt{proxy}                           : <undefined>
opt{query}                           : <undefined>
opt{quiet}                           : 0
opt{retry}                           : <undefined>
opt{server}                          : <undefined>
opt{ssl}                             : <undefined>
opt{syslog}                          : <undefined>
opt{test}                            : <undefined>
opt{timeout}                         : <undefined>
opt{use}                             : <undefined>
opt{verbose}                         : 1
opt{web}                             : <undefined>
opt{web-skip}                        : <undefined>
=== globals ====
globals{daemon}                      : 60
globals{debug}                       : 1
globals{quiet}                       : 0
globals{verbose}                     : 1
=== config ====
=== cache ====
cache{home.fabricesemti.dev}{atime}  : 0
cache{home.fabricesemti.dev}{backupmx} : 0
cache{home.fabricesemti.dev}{host}   : home.fabricesemti.dev
cache{home.fabricesemti.dev}{mtime}  : 0
cache{home.fabricesemti.dev}{mx}     :
cache{home.fabricesemti.dev}{static} : 0
cache{home.fabricesemti.dev}{status} :
cache{home.fabricesemti.dev}{warned-min-error-interval} : 0
cache{home.fabricesemti.dev}{warned-min-interval} : 0
cache{home.fabricesemti.dev}{wildcard} : 0
cache{home.fabricesemti.dev}{wtime}  : 30
root@ddclient-deployment-6d9f949c9f-h9nlg:/#
`

(or as a picture)

![image](https://user-images.githubusercontent.com/37410363/115532532-cbe80100-a28d-11eb-8b58-1630fad05286.png)

Can you advise what might be the problem? (The client was working while the DNS was on Google Domains, but I had to move to ClodFlare)

Thanks,
F.

**Comment by SuperSandro2000** [comment]
This is probably something about k8s or kubesail. I don't really have time to dig deeper into this. Sorry.
