### ISSUE TITLE
network not reachaeble during boot

### ISSUE THREAD

**Issue by sqllyw** [ddclient/ddclient#328]
Hi,
my raspberry pi connects to the router via WIFI, if I run ddclient as follow, everything works:

    sudo ddclient -verbose -foreground
but if reboot, and you see this message in the log:

     raspberrypi ddclient[519]: WARNING:  cannot connect to checkip.dyndns.com:80 socket: IO::Socket::INET: connect: Network is unreachable

seems to me, ddclient checks web when wifi is not yet connected, anyway to let ddclient checks after the wifi connection is eastablished

config is:
````
protocol=dyndns2
use=web
web=checkip.dyndns.com
web-skip='Current IP Address: '
server=dynupdate.no-ip.com
login=<cut>
password=<cut>
cut.ddns.net

````
version is:
````
ddclient/stable,now 3.8.3-1.1 all [installed]

````

**Comment by dkerr64** [comment]
You should run ddclient as daemon and not in foreground.  It will keep checking and once the network is connected register your IP address then (if update required).

**Comment by sqllyw** [comment]
> You should run ddclient as daemon and not in foreground. It will keep checking and once the network is connected register your IP address then (if update required).

right, thanks
