### ISSUE TITLE
Cannot update domain with unicode characters

### ISSUE THREAD

**Issue by nate2014jatc** [ddclient/ddclient#337]
Hello,

I am currently unable to update my Cloudflare DNS for the site `δελτα.studio` using ddclient.
I don't know how to check which version of ddclient I have, and I don't see a clear way to check in the help page.

**Comment by deercg** [comment]
Same issuse here. After #338 problem. Leave it and back to released build v.3.9.1. Only **work** for **`nomal domain`**. Any domain with **`punycode`** **won't work** and return  **`No zone ID found`**

**Comment by SuperSandro2000** [comment]
You can check the version with ddclient --help IIRC.

**Comment by SuperSandro2000** [comment]
You can check the version with ddclient --help IIRC.

**Comment by trogper** [comment]
try updating it as `xn--mxafdy9b.studio`
Your domain in reality is `xn--mxafdy9b.studio`, but browsers display it as `δελτα.studio`
You can convert between enoceded and decoded form on [punycoder](https://www.punycoder.com/)
