### ISSUE TITLE
FAILED:   updating domain.name: invalid json or result.

### ISSUE THREAD

**Issue by deercg** [ddclient/ddclient#338]
### Log run with ddclient -daemon=0 -debug -verbose -noquiet

> INFO:     getting Cloudflare Zone ID for domain.name
> DEBUG:    proxy    = <undefined>
> DEBUG:    protocol = https
> DEBUG:    server   = api.cloudflare.com
> DEBUG:    url      = client/v4/zones?<redacted>
> DEBUG:    ip ver   =
> CONNECT:  api.cloudflare.com
> CONNECTED:  using SSL
> SENDING:  GET /client/v4/zones?name=domain.name HTTP/1.1
> SENDING:  Host: api.cloudflare.com
> SENDING:  User-Agent: ddclient/3.9.1
> SENDING:  Connection: close
> SENDING:  Content-Type: application/json
> SENDING:  Authorization: Bearer xxxxxxxxxxxxxxxxxx
> SENDING:
> RECEIVE:  HTTP/1.1 200 OK
> RECEIVE:  Date: Sat, 29 May 2021 12:24:33 GMT
> RECEIVE:  Content-Type: application/json
> RECEIVE:  Transfer-Encoding: chunked
> RECEIVE:  Connection: close
> RECEIVE:  CF-Ray: 656fb346cdcfdd8f-SIN
> RECEIVE:  Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
> RECEIVE:  Expires: Sun, 25 Jan 1981 05:00:00 GMT
> RECEIVE:  Set-Cookie: __cflb=0H28vgHxwvgAQtjUGU4vq74ZFe3sNVUZRpHtpB5Vkcm; SameSite=Lax; path=/; expires=Sat, 29-May-21 14:54:34 GMT; HttpOnly
> RECEIVE:  Strict-Transport-Security: max-age=31536000
> RECEIVE:  CF-Cache-Status: DYNAMIC
> RECEIVE:  cf-request-id: 0a59ae603f0000dd8fc3234000000001
> RECEIVE:  Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
> RECEIVE:  Pragma: no-cache
> RECEIVE:  X-Content-Type-Options: nosniff
> RECEIVE:  X-Frame-Options: SAMEORIGIN
> RECEIVE:  Set-Cookie: __cfruid=ee7845aabb296df4cd94f4aced72b5bbe394203d-1622291073; path=/; domain=.api.cloudflare.com; HttpOnly; Secure; SameSite=None
> RECEIVE:  Server: cloudflare
> RECEIVE:
> RECEIVE:  6e7
> RECEIVE:  {"result":[{"id":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxx","name":"domain.name","status":"active","paused":false,"type":"full","development_mode":0,"name_servers":["demi.ns.cloudflare.com","dilbert.ns.cloudflare.com"],"original_name_servers":["ns1.cloudflare.com","ns2.cloudflare.com"],"original_registrar":null,"original_dnshost":null,"modified_on":"2021-05-27T11:01:39.373873Z","created_on":"2021-05-27T10:44:53.603182Z","activated_on":"2021-05-27T11:01:39.373873Z","meta":{"step":2,"wildcard_proxiable":false,"custom_certificate_quota":0,"page_rule_quota":3,"phishing_detected":false,"multiple_railguns_allowed":false},"owner":{"id":"xxxxxxxxxxxxxxxxx","type":"user","email":"mail@gmail.com"},"account":{"id":"xxxxxxxxxxxxxxxxxxxxxxxxxx","name":"Name"},"permissions":["#access:edit","#access:read","#analytics:read","#app:edit","#auditlogs:read","#billing:edit","#billing:read","#cache_purge:edit","#dns_records:edit","#dns_records:read","#lb:edit","#lb:read","#legal:edit","#legal:read","#logs:edit","#logs:read","#member:edit","#member:read","#organization:edit","#organization:read","#ssl:edit","#ssl:read","#stream:edit","#stream:read","#subscription:edit","#subscription:read","#teams:edit","#teams:pii","#teams:read","#teams:report","#waf:edit","#waf:read","#webhooks:edit","#webhooks:read","#worker:edit","#worker:read","#zone:edit","#zone:read","#zone_settings:edit","#zone_settings:read"],"plan":{"id":"0feeeeeeeeeeeeeeeeeeeeeeeeeeeeee","name":"Free Website","price":0,"currency":"USD","frequency":"","is_subscribed":false,"can_subscribe":false,"legacy_id":"free","legacy_discount":false,"externally_managed":false}}],"result_info":{"page":1,"per_page":20,"total_pages":1,"count":1,"total_count":1},"success":true,"errors":[],"messages":[]}
> RECEIVE:  0
> RECEIVE:
> FAILED:   updating domain.name: invalid json or result.

### Here is ddclient.conf
> daemon=600
> syslog=yes
> pid=/usr/local/var/run/ddclient.pid
> ssl=yes
> 
> use=web,web=checkip.org
> web-skip='IP Address'
> 
> protocol=cloudflare \\
> login=token \\
> password=xxxxxxxxxxxxxxxxxxxxxxxxxx \\
> 
> zone=domain.name \\
> domain.name, sub.domain.name

### Password is token zone dns edit - zone zone edit
_Don't know what I am doing wrong. :( Running on debian 10 with current github build._

**Comment by iGodPhil** [comment]
I had the same issue with cloudflare on Debian 10. Something has changed in this version because i had an older version of 3.9.1 on a different lxc container and this one worked perfectly with the same ddclient.conf. 

I could solved my problem with copy the older version from /usr/bin to my new lxc container. So i think there is no problem with your config.

**Comment by plvsouza** [comment]
> ### Log run with ddclient -daemon=0 -debug -verbose -noquiet
> > INFO:     getting Cloudflare Zone ID for domain.name
> > DEBUG:    proxy    = 
> > DEBUG:    protocol = https
> > DEBUG:    server   = api.cloudflare.com
> > DEBUG:    url      = client/v4/zones?
> > DEBUG:    ip ver   =
> > CONNECT:  api.cloudflare.com
> > CONNECTED:  using SSL
> > SENDING:  GET /client/v4/zones?name=domain.name HTTP/1.1
> > SENDING:  Host: api.cloudflare.com
> > SENDING:  User-Agent: ddclient/3.9.1
> > SENDING:  Connection: close
> > SENDING:  Content-Type: application/json
> > SENDING:  Authorization: Bearer xxxxxxxxxxxxxxxxxx
> > SENDING:
> > RECEIVE:  HTTP/1.1 200 OK
> > RECEIVE:  Date: Sat, 29 May 2021 12:24:33 GMT
> > RECEIVE:  Content-Type: application/json
> > RECEIVE:  Transfer-Encoding: chunked
> > RECEIVE:  Connection: close
> > RECEIVE:  CF-Ray: 656fb346cdcfdd8f-SIN
> > RECEIVE:  Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
> > RECEIVE:  Expires: Sun, 25 Jan 1981 05:00:00 GMT
> > RECEIVE:  Set-Cookie: __cflb=0H28vgHxwvgAQtjUGU4vq74ZFe3sNVUZRpHtpB5Vkcm; SameSite=Lax; path=/; expires=Sat, 29-May-21 14:54:34 GMT; HttpOnly
> > RECEIVE:  Strict-Transport-Security: max-age=31536000
> > RECEIVE:  CF-Cache-Status: DYNAMIC
> > RECEIVE:  cf-request-id: 0a59ae603f0000dd8fc3234000000001
> > RECEIVE:  Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
> > RECEIVE:  Pragma: no-cache
> > RECEIVE:  X-Content-Type-Options: nosniff
> > RECEIVE:  X-Frame-Options: SAMEORIGIN
> > RECEIVE:  Set-Cookie: __cfruid=ee7845aabb296df4cd94f4aced72b5bbe394203d-1622291073; path=/; domain=.api.cloudflare.com; HttpOnly; Secure; SameSite=None
> > RECEIVE:  Server: cloudflare
> > RECEIVE:
> > RECEIVE:  6e7
> > RECEIVE:  {"result":[{"id":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxx","name":"domain.name","status":"active","paused":false,"type":"full","development_mode":0,"name_servers":["demi.ns.cloudflare.com","dilbert.ns.cloudflare.com"],"original_name_servers":["ns1.cloudflare.com","ns2.cloudflare.com"],"original_registrar":null,"original_dnshost":null,"modified_on":"2021-05-27T11:01:39.373873Z","created_on":"2021-05-27T10:44:53.603182Z","activated_on":"2021-05-27T11:01:39.373873Z","meta":{"step":2,"wildcard_proxiable":false,"custom_certificate_quota":0,"page_rule_quota":3,"phishing_detected":false,"multiple_railguns_allowed":false},"owner":{"id":"xxxxxxxxxxxxxxxxx","type":"user","email":"[mail@gmail.com](mailto:mail@gmail.com)"},"account":{"id":"xxxxxxxxxxxxxxxxxxxxxxxxxx","name":"Name"},"permissions":["#access:edit","#access:read","#analytics:read","#app:edit","#auditlogs:read","#billing:edit","#billing:read","#cache_purge:edit","#dns_records:edit","#dns_records:read","#lb:edit","#lb:read","#legal:edit","#legal:read","#logs:edit","#logs:read","#member:edit","#member:read","#organization:edit","#organization:read","#ssl:edit","#ssl:read","#stream:edit","#stream:read","#subscription:edit","#subscription:read","#teams:edit","#teams:pii","#teams:read","#teams:report","#waf:edit","#waf:read","#webhooks:edit","#webhooks:read","#worker:edit","#worker:read","#zone:edit","#zone:read","#zone_settings:edit","#zone_settings:read"],"plan":{"id":"0feeeeeeeeeeeeeeeeeeeeeeeeeeeeee","name":"Free Website","price":0,"currency":"USD","frequency":"","is_subscribed":false,"can_subscribe":false,"legacy_id":"free","legacy_discount":false,"externally_managed":false}}],"result_info":{"page":1,"per_page":20,"total_pages":1,"count":1,"total_count":1},"success":true,"errors":[],"messages":[]}
> > RECEIVE:  0
> > RECEIVE:
> > FAILED:   updating domain.name: invalid json or result.
> 
> ### Here is ddclient.conf
> > daemon=600
> > syslog=yes
> > pid=/usr/local/var/run/ddclient.pid
> > ssl=yes
> > use=web,web=checkip.org
> > web-skip='IP Address'
> > protocol=cloudflare \
> > login=token \
> > password=xxxxxxxxxxxxxxxxxxxxxxxxxx \
> > zone=domain.name \
> > domain.name, sub.domain.name
> 
> ### Password is token zone dns edit - zone zone edit
> _Don't know what I am doing wrong. :( Running on debian 10 with current github build._

Same problem here. ( Running on Ubuntu 20.04 with current GitHub build.)

**Comment by dkerr64** [comment]
Are you using the Master or Develop branch from GitHub?  You should use the Master branch as the develop one should be considered unstable -- though the developers would certainly like to receive bug reports on the develop branch, you shouldn't use it in production.

**Comment by deercg** [comment]
> 
> 
> Are you using the Master or Develop branch from GitHub? You should use the Master branch as the develop one should be considered unstable -- though the developers would certainly like to receive bug reports on the develop branch, you shouldn't use it in production.

You're right. I'm using Develop branch as it default branch. Thank you for mention me about Master branch

**Comment by dkerr64** [comment]
@SuperSandro2000 can you change the default branch to master?

**Comment by iGodPhil** [comment]
> @SuperSandro2000 can you change the default branch to master?

git clone https://github.com/ddclient/ddclient.git --branch master should work

**Comment by zraexy** [comment]
I don't use Cloudflare, but looking at the response I'm guessing the breakage was caused by #333. I explained the issue and included a fix in my service PR: #336

**Comment by deercg** [comment]
> 
> 
> @SuperSandro2000 can you change the default branch to master?



> 
> 
> 
> 
> git clone https://github.com/ddclient/ddclient.git --branch master should work

Off topic issues - Current **_`master branch`_** version doesn't work (support) punycode domain name. **`Zone ID not found`** on Cloudflare #337

**Comment by wimpunk** [comment]
> 
> 
> @SuperSandro2000 can you change the default branch to master?

Didn't I set it to develop to make development happen in the develop branch.  I see what I can do to make it by default the master branch for downloading and development branch for committing.

**Comment by SuperSandro2000** [comment]
> Didn't I set it to develop to make development happen in the develop branch. I see what I can do to make it by default the master branch for downloading and development branch for committing.

Don't think you can do that.

**Comment by timschumi** [comment]
It seems like this is an issue with the IO socket geturl implementation specifically. If you look at the received data, there is a `6e7` at the beginning of the received data, and a `0` at the end. Neither should be there in the actual response, as they form invalid JSON (hence the error message).

Switching to the curl implementation by setting `curl=yes` in the configuration seems to work around this for now.

**Comment by dwery** [comment]
I can confirm the bug is caused by #333
