### ISSUE TITLE
ddclient should perhaps not warn about ownership/permissions if file ownership is root:ddclient with 640 permissions

### ISSUE THREAD

**Issue by jhe2** [ddclient/ddclient#348]
ddclient repeatedly warns about config file permissions, even if the file is owned by ``root`` with ``ddclient`` group and ``640`` permissions.

```
ddclient[1234]: WARNING:  file /etc/ddclient/ddclient.conf: file /etc/ddclient/ddclient.conf must be accessible only by its owner.
```

This warning appears every few minutes in the log file.

It would be nice if ddclient would not do that, because having the config file ownership set to ``root:ddclient`` with ``640`` permissions should be even more restrictive (ddclient is unable to write to the file) than having it owned by the ``ddclient`` user.

**Comment by oddlama** [comment]
I second this. I've encountered the same warning today and was quite confused at first why ddclient would warn about this.
