### ISSUE TITLE
Change default daemon interval to more than 1 second

### ISSUE THREAD

**Issue by rugk** [ddclient/ddclient#352]
## Problem

Coming from https://github.com/linuxserver/docker-ddclient/pull/52 the TL;DR of my issue is the following: The Dyndns provider I use, has rate limiting. If you do not use the ` defaults` config file (because you obviously need to configure your own credentials etc. ), 

## Proposed solution

Thus, I'd say just do not use `daemon=0` by default, but `daemon=300`, as 5min is a sensible default without hitting servers way more often than useful.
In any case, people can still re-configure it.

## Related issues

https://github.com/ddclient/ddclient/issues/149 looks related, but is about some combination fo CLI and config as far as I see. Mine if just about the configuration file.

## Alternative solutions

The problem is the default `/defaults/ddclient.conf` gets ignored in my setup (see the linked Docker image), thus the [default setting](https://github.com/ddclient/ddclient/blob/f0270e4940b7f28d551174d8a6e967d2f49368ea/ddclient.conf.in#L19) that is already provided via a default configuration file get's ignored, when you use your own configuration file. (And no, you don't want to copy the whole file including many many comments…)

Thus, an alternative solution would be, if ddclient could somehow merge/fallback to the default configuration file if needed.

**Comment by DaveSophoServices** [comment]
There are checks in the code to set a minimum value on daemon. If it is set to some value less than 60, then we don't honor that, and we up it to 60 seconds.

So, the question is, where is it getting this weird short daemon time from? I guess I have to try to debug someone else's docker image? I've got a few minutes.

**Comment by DaveSophoServices** [comment]
I'm looking at the docker image, where did you put your config, and can you share it?

**Comment by DaveSophoServices** [comment]
Here’s where I think the problem lies. If there is no daemon option, the program runs once, then quits. The supervisor in linuxserver.io then restarts ddclient, cause it quit, and ddclient runs once and quits again. They should specify -daemon on the command line perhaps? I’ll do some tests.

**Comment by rugk** [comment]
Oh thanks a lot for debugging other people's docker images. :sweat_smile: 

It's actually a very popular ddclient Docker image and said to be maintained, so IMHO this is a good thing to do.

As for how to start: Just follow the official doc, and do _not_ set `deamon`.

**Comment by rugk** [comment]
The exact docker-compose etc. is similar to here: https://github.com/linuxserver/docker-ddclient/issues/50

And actually I use podman, but that should not matter.

**Comment by SuperSandro2000** [comment]
This should been increased for the next release. If it is still not enough please write a comment.
