### ISSUE TITLE
Problem with parsing response from easydns

### ISSUE THREAD

**Issue by lemppari** [ddclient/ddclient#354]
I got easydns update working by getting the latest development version which includes the fix #344. However ddclient returns error from the easydns response even if the update goes ok. I've included the response from the api call from debug output. I xxx:ed the domain and IP-address, but kept the length of the strings same. The reason for that is I had two domain in the update job and the other domain name was two characters longer and the response code with that was 92 instead of 90. Could that number in front of html-response tied somehow to the length of the domain name? 

RECEIVE:  HTTP/1.1 200 OK
RECEIVE:  Date: Wed, 18 Aug 2021 16:48:12 GMT
RECEIVE:  Server: Apache
RECEIVE:  Expires: Thu, 19 Nov 1981 08:52:00 GMT
RECEIVE:  Cache-Control: no-store, no-cache, must-revalidate
RECEIVE:  Pragma: no-cache
RECEIVE:  Set-Cookie: easydns_language=en_US; expires=Thu, 18-Aug-2022 16:48:12 GMT; Max-Age=31536000; path=/
RECEIVE:  Set-Cookie: EasyDNS_SID=XXX; expires=Wed, 18-Aug-2021 18:48:12 GMT; Max-Age=7200; path=/; domain=api.cp.easydns.com; secure; HttpOnly
RECEIVE:  X-Frame-Options: sameorigin
RECEIVE:  Vary: Accept-Encoding
RECEIVE:  Connection: close
RECEIVE:  Transfer-Encoding: chunked
RECEIVE:  Content-Type: text/html; charset=UTF-8
RECEIVE:  
RECEIVE:  90
`RECEIVE:  <HTML><BODY><FONT FACE="sans-serif" SIZE="-1">OK<br />`
`RECEIVE:  <hr noshade size="1">`
`RECEIVE:  xxxxxxxxx.xxx updated to xx.xxx.xxx.xxx<br />`
`RECEIVE:  </FONT></BODY></HTML>`
RECEIVE:  0
RECEIVE:  
FAILED:   updating xxxxxxxxx.xxx: unexpected status (90)

**Comment by lemppari** [comment]
I changed my IP-address and now the IP-address is on character shorter. The update for the domain above was updated with return code 8f and the two characters longer domain with return code 91. So the return code could have something to with the length of the domain name and the IP-address. Or not :)

**Comment by lemppari** [comment]
I think it's actually the length of the HTML response in HEX. Numbers match. But anyway the correct return code is probably the zero after the HTML...

**Comment by DaveSophoServices** [comment]
Yeah, looks like a bug in the easy dns update code. Grabbing the wrong return instead of the http status code.

**Comment by DaveSophoServices** [comment]
Looking through the easy dns update code, it looks like easy dns has changed their response format. Looks like it used to be plain text, but now is HTML. What is the update server you're using, can you share a sanitized config file?

**Comment by DaveSophoServices** [comment]
https://kb.easydns.com/knowledge/dynamic-dns/ it seems like quite a bit has changed, and it's a wonder it's still working.

**Comment by lemppari** [comment]
Here is content of my config file. I am not running as a daemon, I'm calling ddclient from a batch file.

daemon=300                                      # check every 300 seconds
syslog=yes                                      # log update msgs to syslog
mail=root                                       # mail update msgs to root
pid=/var/run/ddclient.pid                       # record PID in file.
use=web,      web=checkip.dyndns.com/,       fw-skip='IP Address' # found after IP Address
server=api.cp.easydns.com,              \
protocol=easydns,                       \
login=xxxxxxxx,                 \
password=xxxxxxxxxxxxxxxxx      \
wildcard=yes                    \
xxxxxxxxx.xxx,x.xxxxxxxxx.xxx

**Comment by DaveSophoServices** [comment]
If you're running a batch execution, you shouldn't be putting daemon=300 in there.

**Comment by lemppari** [comment]
Thanks for the hint. My batch job runs with -daemon=0 parameter. I will modify the batch and config files.

**Comment by lemppari** [comment]
I guess the issue with easydns is not fixed.

**Comment by SuperSandro2000** [comment]
I would assume so myself, too.
FYI I am not planning to debug or improve this myself.

**Comment by YamiYukiSenpai** [comment]
So I didn't realize it wasn't working for me, until this morning when I noticed my DDNS still says "offline" after 5 hours.

I added this line in `/etc/ddclient.conf` file at the top:
```
server='api.cp.easydns.com' 
```

which seems to have worked as I saw my IP modify from offline to the current public IP.

Before:

```
CONNECT:  members.easydns.com
```

After: 

```
CONNECT:  api.cp.easydns.com
```

**Comment by lemppari** [comment]
Yes, it works, but returns FAILED status message.
