### ISSUE TITLE
FATAL: Cannot create file '/var/cache/ddclient/ddclient.cache'. (Permission denied)

### ISSUE THREAD

**Issue by eihns** [ddclient/ddclient#358]
Im lost.
Im using your docker on unraid.
All working fine, only problem, for whatever reason, after some time, your docker changes the permissions for the ddclient.cache and is constantly for hours "changing" the same ip over and over again... i can chmod 777 it and it will work for some time and then the same thing happens 2 month later....

What is the problem?
docker run -d --name='ddclient-cloudflare' --net='bridge' -e TZ="Europe/Berlin" -e HOST_OS="Unraid" -e 'PGID'='1000' -e 'PUID'='1000' -l net.unraid.docker.managed=dockerman -l net.unraid.docker.icon='https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/ddclient-logo.png' -v '/mnt/user/appdata/ddclient-cloudflare':'/config':'rw' -v '/mnt/user/appdata/ddclient-cloudflare/ddclient':'/var/cache/ddclient/':'rw' --restart=unless-stopped --log-opt max-size=50m --log-opt max-file=1 'linuxserver/ddclient'

Cant it just use 1kb of memory and save it inside his memory? :D

**Comment by eihns** [comment]
I try to link /var/cache/ddclient now to /tmp/ddclient-cloudflare/ddclient maybe that fixes it.

**Comment by DaveSophoServices** [comment]
It seems like there’s a process running, as root, occasionally, which steal the permissions. Where is the docker image from?

**Comment by eihns** [comment]
I dont know what you mean. 
I just know no other docker has any permission problems, thats why i think its this dockers fault.

What do you mean "where is it from"?

**Comment by DaveSophoServices** [comment]
If this is the docker you used, you might need to ask them why it’s doing this:

https://hub.docker.com/r/linuxserver/ddclient

It’s from Linuxserver.io

**Comment by eihns** [comment]
as far as i know they just bring the template to unraid, they dont change the dockers

**Comment by DaveSophoServices** [comment]
I think that Linuxserver.io created and maintain the docker image. 

Dave

**Comment by eihns** [comment]
Its even shown as "project site"

![1](https://user-images.githubusercontent.com/43281991/132776399-a292932a-7218-4cb6-a916-998bf91ea2d7.png)

**Comment by DaveSophoServices** [comment]
Can you give us a list of the cron processes that are running in the docker image? I suspect there is one run by root that is grabbing ownership of the cache file. Also, let me know what user the ddclient process is running as. Perhaps creating an hourly cron script to change the ownership back to the ddclient process??

The reason we don't just keep the value in memory is that we wish to preserve our state longer term.

**Comment by SuperSandro2000** [comment]
This is likely a problem on linuxserver side but I lack the time to support this in any way.
