### ISSUE TITLE
can't run in foreground mode

### ISSUE THREAD

**Issue by arcnmx** [ddclient/ddclient#359]
I'm attempting to use the develop branch and running into an issue with it always running in daemon mode. There doesn't seem to be a way to force it not to?

(note that nixos can rename binaries to `bin/.ddclient-wrapped`, which I assume is a problem for the `d$` check? So I manually renamed it to avoid this just in case)

Despite all attempts (setting `foreground=YES`, renaming binary, setting daemon=0, not setting daemon, etc), it always ran in daemon mode and would say `.ddclient - sleeping for X seconds`. I gave up and patched it to always set `$daemon` off

**Comment by DaveSophoServices** [comment]
I believe the setting is just ```-foreground```, without any following parameter.

**Comment by DaveSophoServices** [comment]
In the config file, you may specify foreground=YES, or foreground=Y, or foreground=yes, or foreground=y, or foreground=true (just the 't' or even uppercase), or even foreground=1.
It should be working for you.

Can you try running it with the ```-verbose -debug``` setting and posting the output?

**Comment by arcnmx** [comment]
Well `foreground=YES` seemed to be working (it wasn't forking into the bg, and yes I was using the config file to set it) - the problem was that the `daemon` option was **also** considered turned on, and I could not figure out how to convince it otherwise. It seems like you can't explicitly set it off since it has a minimum value, and the default value/guessing logic seemed flawed or something?
I can try to get a debug run in when I get a chance.
