### ISSUE TITLE
No option to disable built in web URLS?

### ISSUE THREAD

**Issue by xevidos** [ddclient/ddclient#360]
I was wondering if I was missing something, but there does not seem to be an option, where a user can disable use of any of the internal or default "web" option urls built in to the program and instead only use their custom one specified.

**Comment by ostridge** [comment]
Yes there is - in the ddclient.conf
`use=web `web-skip='dnspark' 
otherwise requires an edit in the perl script located at  `which ddclient`.
Better to use the 'ddclient.conf' option.
