### ISSUE TITLE
Set email from

### ISSUE THREAD

**Issue by ahrasis** [ddclient/ddclient#362]
We have:
  -mail {address}
  -mail-failure {address}
where email address is added to send email to.

First issue: I couldn't find any option to set email address to send email **"from"**, so if there is any please highlight, but if there is none, may be this feature can be considered.

Second issue: I am not sure if the same can be set per each host definition or protocol, so if there is any please highlight, but if there is none, may be this feature can also be considered.

**Comment by SuperSandro2000** [comment]
This is a feature request and feature requests in the form of issues are no longer accepted.
