### ISSUE TITLE
error if only setting ipv6 arguments (usev6, webv6)

### ISSUE THREAD

**Issue by benneti** [ddclient/ddclient#363]
on the develop branch using `usev6=cmdv6, cmdv6=myip6` (or also inbuilt methods like `usev6=webv6, webv6=ip6only.me` ) results in 
```
WARNING:  '' is not a valid IPv4 or IPv6 address
WARNING:  found neither IPv4 nor IPv6 address
WARNING:  domain: unable to determine IP address with strategy use=ip
Use of uninitialized value $ip in string at /run/current-system/sw/bin/ddclient line 3557.
Use of uninitialized value $_[0] in sprintf at /run/current-system/sw/bin/ddclient line 2080.
INFO:     setting IP address to  for DOMAIN
```
at the same time, `use=cmd, cmd=myip6` does find the correct ip but seems to not update the ip address.
Is ipv6 supported on the development branch (for dyndnsv2)?

**Comment by rautesamtr** [comment]
you have to set `use=no` since otherwise it defaults to `ip`. kind of strange since use is marked deprecated so you would expect it to be set to `no` as default.

**Comment by benneti** [comment]
ah cool thanks, I will try that and yes I guess that the default is ip is probably what confused me!

**Comment by MessieAss** [comment]
> you have to set `use=no` since otherwise it defaults to `ip`

Thanks a ton, this solved my issue! My Raspberry Pi 1B struggled for days with DDNS. It merely acts as an NTP server for a few houses.
Cheers,
     tim
