### ISSUE TITLE
can't get root domain to update.

### ISSUE THREAD

**Issue by RT-Tap** [ddclient/ddclient#364]
Hey, So I HIGHLY doubt this is a ddclient issue but I don't know where to look/ask anymore.

SO, here's the story.  Everything was working fine earlier today, then I went to my registrar/name server/whatever you call them to add another sub domain for another service I wanted to host.  I add it no problem add credentials to ddclient, it automatically updates and then I go to update SSLCert or rather generate a new cert for the subdomain, but I figure while I'm here I'll just update them all ... but I get an error : 
```
Failed authorization procedure. rootdomain.com (http-01): urn:ietf:params:acme:error:dns :: No valid IP addresses found for rootdomain.com, www.rootdomain.com (http-01): urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for rootdomain.com - check that a DNS record exists for this domain,
```
So I go back to the registrar and lo and behold there's no record for the root domain. BUT I'm thinking I had just been to my root domain a couple days ago and I could have sworn I had one.  Whatever, no problem, I'll just add an A record for the root domain.  I go add it to ddclient and run `sudo ddclient -daemon=0 -verbose -noquiet` and I get the following output, which looks good : 
NOTE: not really my domain or ip
```
CONNECT:  dynamicdns.park-your-domain.com
CONNECTED:  using SSL
SENDING:  GET /getip HTTP/1.0
SENDING:   Host: dynamicdns.park-your-domain.com
SENDING:   User-Agent: ddclient/3.9.1
SENDING:   Connection: close
SENDING:   
SENDING:   
RECEIVE:  HTTP/1.1 200 OK
RECEIVE:  Cache-Control: private
RECEIVE:  Content-Type: text/html
RECEIVE:  Set-Cookie: ASPSESSIONIDSCDTQDRQ=ODHHNMDBNGAGIFEHJKBOBMDK; path=/
RECEIVE:  Date: Tue, 05 Oct 2021 04:26:50 GMT
RECEIVE:  Connection: close
RECEIVE:  Content-Length: 13
RECEIVE:  
RECEIVE:  108.5.199.254
SUCCESS:  rootdomain.com: skipped: IP address was already set to 192.168.1.162.      
SUCCESS:  bitwarden.rootdomain.com: skipped: IP address was already set to 192.168.1.162.
SUCCESS:  cloud.rootdomain.com: skipped: IP address was already set to 192.168.1.162.
SUCCESS:  copied: skipped: IP address was already set to 192.168.1.162.
SUCCESS:  git.rootdomain.com: skipped: IP address was already set to 192.168.1.162.
SUCCESS:  wordpress.rootdomain.com: skipped: IP address was already set to 192.168.1.162.
Can't exec "sendmail": No such file or directory at /usr/bin/ddclient line 1647.
ddclient: cannot execute command | sendmail -oi art.
```
Looks good, right?  Well apparently not, I can't get to my root domain and certbot won't update the cert for my root domain because apparently there's no record for it.  I tried adding additional subdomains (such as test, test2, etc.) and they all updated immediately after adding them to `ddclient.conf` but the root domain stays at 0.0.0.0 .   So I finally contact google (as they are my registrar or whatever) and I talk to 2 different people but I can't convince them it's an issue on their end as every subdomain EXCEPT the root domain updates.  They both tell me it's an issue with whatever dynamic DNS client I'm using.  So here I am asking for help.  Any ideas what the issue may be?
Also, I tried removing the record for the root domain and readding it to no avail.  I kept all the credentials they gave me and none of them work, or rather ddclient says that it's already at the correct ip address but for some reason it's not updating on Google's end.

EDIT:  Maybe it is a ddclient issue? clearly the record hasn't been updated with my current ip address so why is it reporting that it already has been?

**Comment by RT-Tap** [comment]
actually maybe it is an issue ... I just removed ddclient and reinstalled and now I can't get any output when I run `sudo ddclient -daemon=0 -verbose -noquiet` any idea why this may be?

**Comment by RT-Tap** [comment]
Fixed by clearing cache with : 
```
sudo rm /var/cache/ddclient/ddclient.cache
```
In case anyone else stumbles upon this.

**Comment by SyderAkaris** [comment]
clearing cache worked, i am saved!
