### ISSUE TITLE
dynv6?

### ISSUE THREAD

**Issue by NULUSIOS** [ddclient/ddclient#367]
I know asking for a provider is not the suggested method, but to be honest I don't even know where to start, while someone that has done this before needs maybe 5 to 10 minutes to implement.

Dynv6 (https://dynv6.com/) is a free provider, that AFAIK even provides multiple methods to update the IP (i.e. it can behave like other known providers).

So, if someone can help, I would appreciate it.
Or point me to the exact files I need to look and try to fiddle.

**Comment by geraldhansen** [comment]
Are you looking for an example config to do ipv6 updates?
https://myonlineportal.net/dyndns/how_to_ddclient This provider support IPv6 and has also an example config for ddclient.

**Comment by NULUSIOS** [comment]
No no. I am using it with IP v4 (despite its name it is also for v4).

**Comment by SuperSandro2000** [comment]
This should be drastically improved for the next release.
