### ISSUE TITLE
how to set up cloudflare conf?

### ISSUE THREAD

**Issue by viponedream** [ddclient/ddclient#375]
when install ddclient, i fill in my username and password. 
but it  does not work. 

skipping host: eth.pool123.org: 'zone=' is an invalid fully qualified host name.

**Comment by awalon** [comment]
It seems that "zone" option was not set for cloudflare:
```  ## single host update using an API token
  protocol=cloudflare
  zone=dns.zone
  login=token             
  password=cloudflare-api-token                             
  myhost.com
```
Please try to add:
`zone=<name of your DNS zone>`
maybe `zone=pool123.org`
