### ISSUE TITLE
Time for a major fork?

### ISSUE THREAD

**Issue by bitshiftnetau** [ddclient/ddclient#378]
Developers aren't responding and last update was 2 years ago. Correct me if I'm wrong but it seems time to fork to a new major project.

**Comment by SuperSandro2000** [comment]
related #380

**Comment by dkerr64** [comment]
The answer is not to fork, but rather to find developer(s) that will actively maintain and contribute to this project.  The last few days have seen significant increase in activity to there is hope.

**Comment by bitshiftnetau** [comment]
> The answer is not to fork, but rather to find developer(s) that will actively maintain and contribute to this project. The last few days have seen significant increase in activity to there is hope.

It must be something about clocks that make developers unable to read haha 😅 I do the same all the time... yeh it's all good this thread was made a few days before his announcement. Luckily the torch can be past on from the maintainer, otherwise it would indeed have resulted in a major fork. 

Closing.
