### ISSUE TITLE
Support for Mail-In-A-Box 

### ISSUE THREAD

**Issue by geek-baba** [ddclient/ddclient#379]
The project is hosted at - [Mail-in-a-Box](https://mailinabox.email/)
Usage:
`curl -X VERB [-d "value"] --user {email}:{password} https://box.miab.email/admin/dns/custom[/qname[/rtype]]`

Examples: _(For simplicity the examples omit the --user me@mydomain.com:yourpassword command line argument which you must fill in with your email address and password.)_

```
# sets laptop.mydomain.com to point to the IP address of the machine you are executing curl on
curl -X PUT https://box.miab.email//admin/dns/custom/laptop.mydomain.com
# deletes that record and all A records for that domain name
curl -X DELETE https://box.miab.email//admin/dns/custom/laptop.mydomain.com
```

Another project thats implemented it - [Dynamic DNS Go](https://github.com/alinbalutoiu/dynamicdns-go)

**Comment by geek-baba** [comment]
Hi - will this be included in next release?

**Comment by SuperSandro2000** [comment]
Yes, when it eventual happens
