### ISSUE TITLE
WARNING:  unable to determine IP address

### ISSUE THREAD

**Issue by rhumbliner** [ddclient/ddclient#381]
Using DDclient 3.9.1 with `-use=ip -ip xxx.xxx.xxx.xxx` generates the following error:

`WARNING:  unable to determine IP address`

I tracked down the bug and suggest the following fix:

```
2222c2222
< 	$ip  = opt('ip', $h);
---
> 	$reply = opt('ip', $h);
```

**Comment by SuperSandro2000** [comment]
I think that should have been already fixed. Please wait for the next version if that fixes it.

**Comment by rhumbliner** [comment]
thx for the update.  i downloaded the latest version from GitHub and it is indeed fixed.  the version i installed from HomeBrew onto my Mac and the version i installed onto to my Gentoo servers were the versions with the bug.

tom
