### ISSUE TITLE
URL error when using Namecheap

### ISSUE THREAD

**Issue by nerdworks** [ddclient/ddclient#385]
Hi, 

I have been struggling to make ddclient work with Namecheap.

If I try to update the IP for a host named host.mydomain.tld, the URL sent is as follows:

https://dynamicdns.park-your-domain.com/update?host=host.tld&domain=mydomain&password=[ddns_password]&ip=[new_ip]

If I replace my login name in the config file with mydomain.tld, everything works just fine.

In the ddclient config file:
login=MyNamecheapLoginName    \ This does not work
login=mydomain.tld                          \ This works 

When trying to figure this one out it soon became obvious that my Namecheap login name is not required to do an update.

I propose that the documentation is updated to avoid future users having the same issues.

Thanks,

**Comment by SuperSandro2000** [comment]
You mean like https://github.com/ddclient/ddclient/commit/eaa3263dc012f01a1292c77f77d1227ad55579fd ?

**Comment by nerdworks** [comment]
Yes, exactly.

Perfect :-)
