### ISSUE TITLE
curl cron

### ISSUE THREAD

**Issue by flatroof** [ddclient/ddclient#387]
Am i missing something? This tool seems so much overhead when it seems a [simple curl](https://support.opendns.com/hc/en-us/community/posts/115018684243/comments/360003273811) can do it all.

`curl --user username:password https://updates.opendns.com/nic/update?hostname=<Network name>`

single quote user/pass if special chars in use.

**Comment by wimpunk** [comment]
I think you're missing a lot.

- ddclient verifies if the update was succesful
- ddclient can send a mail or do extra actions after succesful update
- ddclient hides your username and password
- ddclient supports multiple protocols
- ddclient can fetch it's IP from different locations

**Comment by SuperSandro2000** [comment]
For example the cloudflare protocol does like 3 requests in total which would require a small little script.
