### ISSUE TITLE
ipv4 & ipv6 only one will be updated

### ISSUE THREAD

**Issue by CoLuxe** [ddclient/ddclient#390]
Hello!
Im behind NAT (Dual Stack) but my Router uses an ipv6 prefix so every client has an public ipv6 adress in my local network.
Im using this config to update both:

ssl=yes
protocol=cloudflare
use=web, web=https://api.ipify.org/
usev6=if, if=ens18
login=blablabla
password='blablabla'
zone=bllabla.bla
bla.blabla.bla

With this config it updates only ipv6. DDClient doesnt try ipv4 even. No error in the log.
How its possible to update an A and AAAA Record at the same time?

**Comment by SuperSandro2000** [comment]
Please try

```
ssl=yes
protocol=cloudflare
use=web, web=api.ipify.org
usev6=if, if=ens18

login=blablabla \
password='blablabla' \
zone=bllabla.bla \
bla.blabla.bla
```
