### ISSUE TITLE
Add Support for Selfhost.de DynDNS

### ISSUE THREAD

**Issue by TheHille** [ddclient/ddclient#394]
Would like to see native support (i.e. profile) for Selfhost.de DynDNS.

Following guide helped me to set up custom settings:

https://selfhost.de/cgi-bin/selfhost?p=faq&show=113&CGISESSID=8bcf92f9c76f2e6307deb71d33cf4655

protocol=dyndns2
use=web, web-skip='IP Address'
server=carol.selfhost.de
login=ihr_dyndns_account
password=ihr_passwort

**Comment by SuperSandro2000** [comment]
That is already pretty compact and I don't think we need to add anything else here.
