### ISSUE TITLE
Add interface option whith use=web to allow multi-WAN setups that are behind NAT [feature-request]

### ISSUE THREAD

**Issue by toxic0berliner** [ddclient/ddclient#395]
My understanding is that when the user set use=web in the config file, ddclient will ultimately end up querying some web service then parse the result to find out what IP to use when setting it using whatever protocol is chosen.

My tests show that there is no way to tell ddclient which interface to use when querying this web service. As such, the default routing table is used and only a single public IP can be fetched like this.

Having 2 ISP and therefore 2 WAN, each having a NAT, I had to do something like this : 
`use=cmd, cmd="curl --interface ovpnc1 api.ipify.org"`

Which pretty much defeats the purpose of half of the logic in this nice software from my point of view...

I see that in some places you are already using curl anyway, so probably someone here could add some option when use=web to also specify which physical interface to use when contacting the web service ?

**Comment by SuperSandro2000** [comment]
> My understanding is that when the user set use=web in the config file, ddclient will ultimately end up querying some web service then parse the result to find out what IP to use when setting it using whatever protocol is chosen.

Yes, that is right.

> Which pretty much defeats the purpose of half of the logic in this nice software from my point of view...

I don't know to be honest. cmd exists for exactly such custom cases. I also do not want to add a bunch more little used options.

> probably someone here could add some option when use=web to also specify which physical interface to use when contacting the web service ?

PRs are welcome but I will probably take a bit to review them.

**Comment by toxic0berliner** [comment]
Sadly I'm totally incompetent with perl so I probably won't be submitting a PR... 
If anyone is interested in pitching in I'm available for help or test though.

I think the feature would be more than "little used" as there is the whole community of OpnSense router users that was previously using another solution for dyndns and will have to migrate to a new one based on ddclient, so I'm using the OpnSense framework to go around that and use=cmd but adding this would be used by quite a lot of people I think, indirectly at least.

**Comment by awalon** [comment]
Hello @toxic0berliner,
maybe you could test the interface enhancement with this updated version by adding `webif=<interface>` to your configuration.

**Comment by SuperSandro2000** [comment]
This is a feature request and feature requests in the form of issues are no longer accepted.
