### ISSUE TITLE
Ability to show cached IP adress (opnSense)

### ISSUE THREAD

**Issue by thetruetype** [ddclient/ddclient#399]
Just updated to os-ddclient in OpnSense from the old dyndns, but now when using ddclient is there any way to see the cached IP adress like dyndns did? It's a good feature to see if it's working or not.

**Comment by SuperSandro2000** [comment]
You can always take a look into the cache file or just dig the domain which is supposed to be updated.

**Comment by thetruetype** [comment]
> You can always take a look into the cache file or just dig the domain which is supposed to be updated.

I tried to update my Cloudflare DNS without success and if I could see the cached IP as before with the old DynDNS I could see the cached IP and that was more convenient to see it in the opnsense web-gui.

**Comment by SuperSandro2000** [comment]
I have never used opnsense, so I can't assist much here.
