### ISSUE TITLE
Add an option to send logs to its own log file and not syslog

### ISSUE THREAD

**Issue by Sopor** [ddclient/ddclient#402]
I would be able to log ddclient to its own log file and not to syslog when i run it as a daemon.

Is it possible to add an options for this?

**Comment by SuperSandro2000** [comment]
Did you try setting `syslog=no`?

**Comment by Sopor** [comment]
Yes, but i can't see any log files. What should the name of the log file be, ddclient.log?

Was it you guessing or should it really work? 😊

**Comment by SuperSandro2000** [comment]
It probably just logs to stdout which you would need to redirect to a file.

**Comment by Sopor** [comment]
Fiddling around like this was something i wanted to avoid. It should be easy as changing a `no` to `yes` `ddclientlog=yes` and it should create its own log file.

**Comment by SuperSandro2000** [comment]
I think you might be able to set daemon to no and then leave in the foreground and log to wherever you want. I am not going to add new options to log to some file because ddclient is already bloated to much.
