### ISSUE TITLE
Missing IPv6 address in cache file ?

### ISSUE THREAD

**Issue by Highspeedy** [ddclient/ddclient#404]
Hello,

in the cache file from my ddclient installation (dualstack IPv4 & IPv6) there is after an IP update no IPv6 cached.
The goal are unnecessary IPv6 updates on the DYNDNS provider every few minutes.

Is this a bug or ist it a configuration error of my ddclient.conf ?

#begin of file

#/etc/ddclient.conf

daemon=600
syslog=yes
#mail=root
#mail-failure=root
pid=/var/run/ddclient.pid
ssl=yes
cache=/var/cache/ddclient/ddclient.cache
protocol=dyndns2
usev4=webv4, webv4=ip4.ddnss.de/meineip.php/, webv4-skip='IP Address'
usev6=ifv6, ifv6=eth0
server=ddnss.de
login=xxxxx
password=xxxxxxxx
xxxxxxx.xxxxx.xx

#end of file

**Comment by SuperSandro2000** [comment]
> Is this a bug or ist it a configuration error of my ddclient.conf ?

I would guess a bug but I don't have the capacity to investiagte this right now.

**Comment by agowa338** [comment]
I'm using version 3.9.1 and the IPv4 isn't written to the cache either. It only wrote the hostname it checks. the `ip` attribute doesn't have any value in the cache.

**Comment by tduboys** [comment]
Hi,
I had the same issue, you're using dyndns2 provider, and it was not working with ipv4/ipv6 logic
I tried to fix it on https://github.com/ddclient/ddclient/pull/502 and works correctly on my config, but I didnt tested every dyndns2 provider
