### ISSUE TITLE
Support to provide IP address of Fritz!box in config file

### ISSUE THREAD

**Issue by Kalvalax** [ddclient/ddclient#407]
In an environment with multiple fritzboxes (primary and backup) the resolution of "fritz.box" can only query one Fritz!box.
A parameter for the ip address to be used in the config file could solve this scenario.

**Comment by SuperSandro2000** [comment]
Replace fritz.box in the [sample](https://github.com/ddclient/ddclient/blob/develop/sample-get-ip-from-fritzbox#L19) with the Ip address.

**Comment by Kalvalax** [comment]
This would be easy when using ddclient directly. I'm using linuxserver/ddclient which directly uses ddclient unmodified.
So, if this isn't enabled here, you would need to always modify the docker image manually.

**Comment by SuperSandro2000** [comment]
You can always mount the modified script and tell ddclient to execute it via `cmd=`. I want to avoid adding more edge features to ddclient because I already don't have enough time to maintain it.

**Comment by Kalvalax** [comment]
Got it, so I use

use=cmd, cmd=curl -s -H 'Content-Type: text/xml; charset="utf-8"' ...

correct?
