### ISSUE TITLE
IPv4 detection on OpenBSD 7.1 fails

### ISSUE THREAD

**Issue by fireglow** [ddclient/ddclient#411]
I'm running ddclient 3.9.1 on OpenBSD 7.1, installed with `pkg_add`.
My `ddclient.conf` uses `use=if, if=pppoe0`.
Since 7.1, OpenBSD shows obtained DNS server information in ifconfig ("[Added display of DNS information from sppp(4) to ifconfig(8).](https://www.openbsd.org/71.html)")
```sh
gate# ifconfig pppoe0
pppoe0: flags=48851<UP,POINTOPOINT,RUNNING,SIMPLEX,MULTICAST,AUTOCONF6TEMP> mtu 1492
        description: 1&1 DSL
        index 11 priority 0 llprio 3
        dev: em0 state: session
        sid: 0xe97b PADI retries: 1 PADR retries: 1 time: 21:59:45
        sppp: phase network authproto pap authname "foo"
        dns: 82.145.9.8 82.144.41.8
        groups: pppoe egress
        status: active
        inet 92.117.130.2 --> 62.214.63.146 netmask 0xffffffff
```
`ddclient` mistakenly uses the first DNS servers IP (82.145.9.8) as newip, instead of 92.117.130.2.

**Comment by fireglow** [comment]
As a workaround, I'm using
```sh
use=cmd, cmd='ifconfig egress | grep -m1 "inet " | awk \'{print $2}\''
```
in `ddclient.conf`

**Comment by SuperSandro2000** [comment]
I don't have any machine that has BSD or ifconfig. My main suspect is that the regex is wrong. If someone is going to fix that please also add a test to make sure it is less likely to break in the future.

**Comment by SuperSandro2000** [comment]
I am not planning to improve support for any none Linux OS. If you happen to find a bug on another OS please submit a PR to fix it.
