### ISSUE TITLE
STRATO Support

### ISSUE THREAD

**Issue by bunkel** [ddclient/ddclient#415]
Dear developers
Completely new to the community, I don't know if this is even the right way to express wishes.
I use OPNsense and dyndns. This allows the IP to be assigned without any problems with a STRATO domain name.
If I use ddclient, there is no synchronization. STRATO is missing from the list of supported providers. However, I can select STRATO when setting up.
Thanks very much
Bernd

**Comment by gafzgarrr** [comment]
Same Issue here

**Comment by kangaroo72** [comment]
I'm using Debian/Ubuntu and these settings work fine for me:
`pid=/var/run/ddclient.pid
protocol=dyndns2
use=web
ssl=yes
server=dyndns.strato.com/nic/update
login=domain.tld
password=dyndns-password
domain.tld
`
