### ISSUE TITLE
WARNING:  malformed IPv4 address (ipv6:address:here...)

### ISSUE THREAD

**Issue by chongmx** [ddclient/ddclient#416]
after running ddclient with the following command, 

sudo ddclient -daemon=0 -noquiet -debug

I get a warning

DEBUG:    proxy  =
DEBUG:    url    = https://domains.google.com/checkip
DEBUG:    server = domains.google.com
DEBUG:    get_ip: using web, https://domains.google.com/checkip reports xx:xx:xx...ipv6:address:here...
WARNING:  malformed IPv4 address (xx:xx:xx...ipv6:address:here...)

how to ensure it always send out request in IPv4, so google will respond in IPv4 as well?

**Comment by ianmlunaq** [comment]
Hey, I had the same problem and I was able to fix it by replacing the url with https://ifconfig.me/ip
