### ISSUE TITLE
generic Link URL protocol?

### ISSUE THREAD

**Issue by shawndalton** [ddclient/ddclient#418]
Im using dirctnic.com which offers a link to change an IP dynamically:

https://directnic.com/dns/gateway/{SECURECODEFORDOMAIN}/?data={IP_ADDRESS}

Is there a protocol i should use or a way to build this link?

**Comment by Moskito99** [comment]
Please add support for URL update.
I use a script which updated a PowerDNS Domain only via URL.

**Comment by SuperSandro2000** [comment]
dupe of #270
