### ISSUE TITLE
Unable to install 3.10.0_2 - Configure not found

### ISSUE THREAD

**Issue by brianread108** [ddclient/ddclient#423]
This must be an easy one!

`[root@sme10 ddclient-3.10.0_2]# ./configure          --prefix=/usr          --sysconfdir=/etc/ddclient          --localstatedir=/var
-bash: ./configure: No such file or directory
[root@sme10 ddclient-3.10.0_2]# 

`

**Comment by brianread108** [comment]
aha - autoconf.

I downloaded the tar file, and thought that as I had not done a git clone, I did not need the autoconf.

**Comment by brianread108** [comment]
However now I get this:

`[root@sme10 ddclient-3.10.0_2]# ./autogen
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I m4 --output=aclocal.m4t
Can't exec "aclocal": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 326.
autoreconf: failed to run aclocal: No such file or directory
ERROR: 'autoreconf -fviW all' failed
[root@sme10 ddclient-3.10.0_2]# 
`
This is a centos7 based system

**Comment by brianread108** [comment]
ok, needed

yum install autogen, automake

**Comment by SuperSandro2000** [comment]
> I downloaded the tar file, and thought that as I had not done a git clone, I did not need the autogen.

The github auto generated tarball is comparable to a shallow git clone.
