### ISSUE TITLE
AAAA record updates

### ISSUE THREAD

**Issue by Falc0n2k** [ddclient/ddclient#424]
Is there any way to have an AAAA record updated with an IPv6 address?

I recently set up HE's Tunnel Broker on my Unify USG and I'd love to be able to keep the AAAA record for my subdomains updated for my network. In looking through the code I don't see where ddclient supports DNS records of this type, just updating IPv4 addresses.

Would this be a feature that could be added seeing as how the world is moving progressively more towards v6?

**Comment by SuperSandro2000** [comment]
There is already ipv6 support with ``ipv6=yes``. Please check the ``--help``.

**Comment by Falc0n2k** [comment]
@SuperSandro2000 - The first thing I did was check `--help`, and it makes no mention of `ipv6=yes`.

**Comment by SuperSandro2000** [comment]
Then it maybe is only in the 3.10.0 pre release.
