### ISSUE TITLE
check ddns domain for IP change, instead of cache file

### ISSUE THREAD

**Issue by jackcctse** [ddclient/ddclient#428]
ddclient by default checking local cache file for IP change. Is it possible to override this by checking the actual ddns domain instead? This way should be more reliable, despite increased network traffic; in my setup the default behavior has caused some issue, some time IP wasn't updated even public IP changed.

**Comment by SuperSandro2000** [comment]
This is a feature request and feature requests in the form of issues are no longer accepted.

I know the dyndns client on openwrt is supporting this and if you have a openwrt device I recommend switching to that.
