### ISSUE TITLE
No release in two years?

### ISSUE THREAD

**Issue by ilium007** [ddclient/ddclient#429]
Why hasn't there been a package release in over two years? Genuine question / interest.

**Comment by SuperSandro2000** [comment]
Two pre releases happened in May https://github.com/ddclient/ddclient/releases but I am not very confident to push them to a full release right now. Maybe I just push 3.10 in the next days and see what happens.

**Comment by ilium007** [comment]
Yeah, I saw the pre-releases. I know my question got a thumb down but I was genuinely interested as to whether the project was still alive or was abandoned.

**Comment by SuperSandro2000** [comment]
It is more or less in maintenance mode and does not get much attention from me.

**Comment by SuperSandro2000** [comment]
I just released 3.10.0.
