### ISSUE TITLE
Alternatives

### ISSUE THREAD

**Issue by stokito** [ddclient/ddclient#430]
There is a lot of other DDNS Clients:

- https://openwrt.org/docs/guide-user/services/ddns/client DDNS client for routers with OpenWrt
- http://github.com/troglobit/inadyn In-a-Dyn depends on GnuTLS
- https://github.com/leamas/ddupdate uses Python

- https://sourceforge.net/projects/dyndnssimplycl/ DynDNS Simply Client for Windows. Old but still works
- https://www.directupdate.net/ for Windows. Rich options but paid

Maybe it worth to add the list somewhere into README or in a separate list?

The ddclient.net seems one of the most popular and available in all distros but it uses Perl. This makes it hard to use on OpenWrt where only BusyBox Ash shell is present out of the box. That's why there is a separate package.
It's scripts are here https://github.com/openwrt/packages/tree/master/net/ddns-scripts/files/usr/lib/ddns and the list of supported providers in https://github.com/openwrt/packages/tree/master/net/ddns-scripts/files/usr/share/ddns/default

Maybe it's possible somehow to merge this two projects? Then it may be easier to write a single instruction for all OS. Also the list of providers will be the same.
I don't feel like the JSON format is necessary but maybe it would be better to use some plain ini like text files as ddclient use.

**Comment by SuperSandro2000** [comment]
openwrt has totally different constraints that do not apply to most other distros and in most places perl is already pre installed.

I am not planning to introduce bigger changes to ddclient right now due to other priorities.
