### ISSUE TITLE
ddclient is doing spam updates every 5 minutes when managing hostnames that are proxied through cloudflare

### ISSUE THREAD

**Issue by R-Adrian** [ddclient/ddclient#431]
I downloaded ddclient from github here and configured it a few days ago and since it seemed to be doing its job i left it at that...
( it says `use version 0.77; our $VERSION = version->declare('v3.10.0_2');` in the source code)

Today i took a look at the /var/log/syslog file... and had a **facepalm** moment - i realized that ddclient is spamming cloudflare with IP address updates.... but to the same IP address that is already currently assigned to the domain hostnames.

Since the domain is proxied through cloudflare it's possible that ddclient is probably doing DNS lookups and since its getting back a different IP address from DNS than the current one ... then it's trying to push an IP address update again,..and again....and again.....ad nauseam.

Can you please use cloudflare's API and the API access token already provided to check the real IP address of the hosts that are defined in the zone (thus ignoring cloudflare's proxy routing from normal DNS queries), so that ddclient avoids constant;y spam-updating the IP address to the same one every 5 minutes?

This check should be possible with the DNS Record details API call... and if the current IP address is already defined there then PLEASE, do not spam-update it again to the same one.

https://api.cloudflare.com/#dns-records-for-a-zone-list-dns-records
https://api.cloudflare.com/#dns-records-for-a-zone-dns-record-details

```
Jul 17 17:02:32 DuckServer ddclient[1234]: SUCCESS:  updating my domain here..... is updated to the same IP address it already has.
Jul 17 17:02:35 DuckServer ddclient[1234]: SUCCESS:  updating www dot my domain here.....and same here
Jul 17 17:07:38 DuckServer ddclient[1234]: SUCCESS:  updating (...and so on down... )
Jul 17 17:07:42 DuckServer ddclient[1234]: SUCCESS:  updating (...all the next lines...)
Jul 17 17:12:45 DuckServer ddclient[1234]: SUCCESS:  updating 
Jul 17 17:12:49 DuckServer ddclient[1234]: SUCCESS:  updating 
Jul 17 17:17:53 DuckServer ddclient[1234]: SUCCESS:  updating 
Jul 17 17:17:56 DuckServer ddclient[1234]: SUCCESS:  updating 
Jul 17 17:22:59 DuckServer ddclient[1234]: SUCCESS:  updating 
Jul 17 17:23:03 DuckServer ddclient[1234]: SUCCESS:  updating 
Jul 17 17:28:08 DuckServer ddclient[1234]: SUCCESS:  updating 
Jul 17 17:28:12 DuckServer ddclient[1234]: SUCCESS:  updating 
Jul 17 17:33:15 DuckServer ddclient[1234]: SUCCESS:  updating 
Jul 17 17:33:18 DuckServer ddclient[1234]: SUCCESS:  updating 
Jul 17 17:38:22 DuckServer ddclient[1234]: SUCCESS:  updating 
Jul 17 17:38:25 DuckServer ddclient[1234]: SUCCESS:  updating 
Jul 17 17:43:29 DuckServer ddclient[1234]: SUCCESS:  updating 
Jul 17 17:43:32 DuckServer ddclient[1234]: SUCCESS:  updating 
Jul 17 17:48:35 DuckServer ddclient[1234]: SUCCESS:  updating 
Jul 17 17:48:39 DuckServer ddclient[1234]: SUCCESS:  updating 
Jul 17 17:53:43 DuckServer ddclient[1234]: SUCCESS:  updating 
Jul 17 17:53:46 DuckServer ddclient[1234]: SUCCESS:  updating 
Jul 17 17:58:50 DuckServer ddclient[1234]: SUCCESS:  updating 
Jul 17 17:58:54 DuckServer ddclient[1234]: SUCCESS:  updating 
Jul 17 18:03:58 DuckServer ddclient[1234]: SUCCESS:  updating 
Jul 17 18:04:01 DuckServer ddclient[1234]: SUCCESS:  updating 
Jul 17 18:09:04 DuckServer ddclient[1234]: SUCCESS:  updating 
Jul 17 18:09:08 DuckServer ddclient[1234]: SUCCESS:  updating 
Jul 17 18:14:11 DuckServer ddclient[1234]: SUCCESS:  updating 
Jul 17 18:14:15 DuckServer ddclient[1234]: SUCCESS:  updating 
Jul 17 18:19:19 DuckServer ddclient[1234]: SUCCESS:  updating 
Jul 17 18:19:21 DuckServer ddclient[1234]: SUCCESS:  updating 
Jul 17 18:24:25 DuckServer ddclient[1234]: SUCCESS:  updating 
Jul 17 18:24:29 DuckServer ddclient[1234]: SUCCESS:  updating 
Jul 17 18:29:32 DuckServer ddclient[1234]: SUCCESS:  updating 
Jul 17 18:29:35 DuckServer ddclient[1234]: SUCCESS:  updating 
Jul 17 18:34:38 DuckServer ddclient[1234]: SUCCESS:  updating 
Jul 17 18:34:42 DuckServer ddclient[1234]: SUCCESS:  updating 
Jul 17 18:39:45 DuckServer ddclient[1234]: SUCCESS:  updating 
Jul 17 18:39:48 DuckServer ddclient[1234]: SUCCESS:  updating 
Jul 17 18:44:52 DuckServer ddclient[1234]: SUCCESS:  updating 
Jul 17 18:44:55 DuckServer ddclient[1234]: SUCCESS:  updating 
Jul 17 18:49:58 DuckServer ddclient[1234]: SUCCESS:  updating 
Jul 17 18:50:03 DuckServer ddclient[1234]: SUCCESS:  updating 
Jul 17 18:55:11 DuckServer ddclient[1234]: SUCCESS:  updating 
Jul 17 18:55:14 DuckServer ddclient[1234]: SUCCESS:  updating 
Jul 17 19:00:18 DuckServer ddclient[1234]: SUCCESS:  updating 
Jul 17 19:00:20 DuckServer ddclient[1234]: SUCCESS:  updating 
```

**Comment by R-Adrian** [comment]
small update: i looked a bit into the source code and... from what i could understand from there, i think that the needed Cloudflare `dns_records` API bits are already mostly implemented... but are implemented as an unconditional update in the `nic_cloudflare_update` function.

I think that this update function could be tweaked around these lines to add an additional test to check if the current IP address is already present for the host(s) in the JSON zone query result _(data which is already received by ddclient at this point, just needs to be parsed)_ and if it is already correct then skip pushing a DNS update.

https://github.com/ddclient/ddclient/blob/5382a982cbf4ad8e0c7b7ff682d21554a8785285/ddclient.in#L5875


in the meantime, i changed my configuration file from one check every 5 minutes to one every 2 hours.

**Comment by Saturn49** [comment]
I have to admit I don't completely understand the code, but I think I'm having the same issue.  One thing I noticed is that for my cloudflare host, the cache says 
```
status=noconnect,status-ipv4=good,status-ipv6=noconnect
```

Despite the fact I have usev6=disabled in my config, maybe it is bubbling up this status and retrying every time?

**Comment by SuperSandro2000** [comment]
I think the caching is broken but I lack the resources to fix it.

**Comment by SuperSandro2000** [comment]
Lack of time and general interest in this project.

I don't know the code anymore and can't really be a help in fixing this.

**Comment by julsssark** [comment]
Also see [481](https://github.com/ddclient/ddclient/issues/481). I see the same behavior when using the API token. I've set ddclient to run every hour as a workaround.

**Comment by LenardHess** [comment]
Fixed here: https://github.com/rrthomas/ddclient/pull/10
(Changes from that fork merged back here: https://github.com/ddclient/ddclient/pull/551 )
