### ISSUE TITLE
ddclient occasionally stops updating ip

### ISSUE THREAD

**Issue by krzysiobal** [ddclient/ddclient#434]
I have Internet Service Provider (VDSL) that changes its ip every 24 hours and raspberry-pi based computer with web server + .COM domain and ddclient that updates my domain with the ip address (it is configured to check the ip every 30 seconds)

The whole thing has been running for over year without almost any troubles but what I found is that very rarely the ddclient refuses to update the domain and then nothing can be done until manual forcing the ddclient to update. 
The last issue happened on 22 July, today is 26 July and the domain's IP was still not updated.
I luckily found my computer's ip by contacting ISP hotline (I am on holidays so don't have direct access to the router)

Last modification of the "/var/cache/ddclient/ddclient.cache" was on 22 July.
I run "ddclient -query" and it showed my new ip address correctly, but ddclient.cache was still not updated.
Runnig "ddclient" without any parameters forced ddclient.cache to be updated. Why is that? Is there any log that can be seen to examine the causes? I want to have reliable domain but it looks like this thing happened 2 or 3 times in the last year.

**Comment by SuperSandro2000** [comment]
I think there is currently a bug that if the updating fails ddclient writes the cache in some circumstances. I currently don't plan to further investigate that.
