### ISSUE TITLE
[request] New API support DNSExit

### ISSUE THREAD

**Issue by jortkoopmans** [ddclient/ddclient#441]
Recently, ddclient has gained support for DNSExit, see https://github.com/ddclient/ddclient/issues/393 and main PR https://github.com/ddclient/ddclient/pull/311 (albeit unreleased atm). Many thanks to @sreknob , @rrthomas and @SuperSandro2000 for this :+1: (and others I miss to credit)!

However, the preferred and safer method now seems to be to use a new api, as described here; https://dnsexit.com/dns/dns-api/#guide-to-use

It would be great if we can get support for this :smile: :rocket: .

See also related request; https://github.com/opnsense/plugins/issues/2900

**Comment by jortkoopmans** [comment]
I've written an implementation, hope this helps! 
@SuperSandro2000

**Comment by jortkoopmans** [comment]
@SuperSandro2000 : You've closed this issue as completed, but I'm not sure why you would consider it completed? :sweat_smile: 
Note; The PR is not merged...

**Comment by SuperSandro2000** [comment]
that button is new and I am not used to it. A year ago an issue could only be closed or open.

**Comment by jortkoopmans** [comment]
Closed because of #528
