### ISSUE TITLE
BUG not pulling correct id from cloudflare json v4?

### ISSUE THREAD

**Issue by moviebrain** [ddclient/ddclient#453]
I've downloaded and installed the 3.10.02 dev branch trying to fix a very long running issue. I am unable to update dns records, and I think I've narrowed down the issue but I'm not a perl expert so I might be of base.

Line 5888 in ddclient.in:

                my ($dns_rec_id) = map {$_->{name} eq $domain ? $_->{id} : ()} @{$response->{result}};

I think it should be:

                my ($dns_rec_id) = map {$_->{name} eq $domain ? $_->{id} eq $dns_rec_id} @{$response->{result}};

I'm blindly poking, my experience is mostly with python.

I just notice that the debug output says there are no A records at Cloudflare for me, but I'm able to manually retrieve the ID's and manually PUT updates from curl at the command line. I've narrowed it down to incorrectly pulling/storing the record id before posting the update.

edit: ok sorry, shouldn't my ($dns_rec_id) = {id}? The record id has a json tag of {id} in the json response.
my apologies for my lack of perl understanding, but I’m trying to understand and will try a fix in-code soon.

**Comment by davidschlachter** [comment]
You can see more details by running `ddclient` with the `verbose` flag, e.g. `sudo ddclient -foreground -verbose`. In my case, this shows that it is selecting the right zone ID. However, I see the same error (`Cannot set IPv4 to [my ip address] No 'A' record at Cloudflare`) because `ddclient` can't get the list of `A` records.

```
SENDING:  GET /client/v4/zones/****redacted_correct_zone_id****/dns_records?type=A&name=\ HTTP/1.1
SENDING:  Host: api.cloudflare.com
SENDING:  User-Agent: ddclient/3.10.0_2
SENDING:  Connection: close
SENDING:  Content-Type: application/json
SENDING:  Authorization: Bearer *********redacted_my_api_token**********
SENDING:
RECEIVE:  HTTP/1.1 200 OK
RECEIVE:  Date: Fri, 09 Sep 2022 17:19:59 GMT
RECEIVE:  Content-Type: application/json
RECEIVE:  Transfer-Encoding: chunked
RECEIVE:  Connection: close
RECEIVE:  Vary: Accept-Encoding
RECEIVE:  CF-Cache-Status: DYNAMIC
RECEIVE:  x-envoy-upstream-service-time: 17
RECEIVE:  Server: cloudflare
RECEIVE:
RECEIVE:  88
RECEIVE:  {"result":[],"success":true,"errors":[],"messages":[],"result_info":{"page":1,"per_page":100,"count":0,"total_count":0,"total_pages":1}}
RECEIVE:  0
RECEIVE:
```

When I try the same request with `curl` (to `/client/v4/zones/**my_zone_id**/dns_records?type=A&name=`, with the right token), I get the expected list of results, rather than an empty results list.

For reference, here's my config file:

```
daemon=300
syslog=yes
pid=/var/run/ddclient.pid
ssl=yes
use=web

protocol=cloudflare, \
zone=mydomain.tld, \
ttl=1,
password='*********redacted_my_api_token**********',
mydomain.tld
```

**Comment by davidschlachter** [comment]
I saw this error (`No 'A' record at Cloudflare`) when my token was scoped to a particular zone, rather than to all zones on my account. Running `ddclient` with the `-verbose` flag showed me that it is correctly identifying the zone ID.

**Comment by moviebrain** [comment]
> I saw this error (`No 'A' record at Cloudflare`) when my token was scoped to a particular zone, rather than to all zones on my account. Running `ddclient` with the `-verbose` flag showed me that it is correctly identifying the zone ID.

My zone ID isn’t the issue, it’s the record id. Zone id is being correctly identified per the output, but to change the dns records you need to specify the zone and record id in the post and I think however that zone and record query is malformed or incorrectly submitted somehow. The verbose output redacts the record ID so I’m unable to verify the right info is being used.

**Comment by moviebrain** [comment]
Closing as trouble was caused by multiple versions of ddclient conflicting at run
