### ISSUE TITLE
[request] Add support for Bunny.net DNS

### ISSUE THREAD

**Issue by Thesola10** [ddclient/ddclient#456]
Updating a domain using Bunny.net's API can be done in two steps:

1) Find the DNS zone ID and record ID from the [`GET /dnszone`](https://docs.bunny.net/reference/dnszonepublic_index) endpoint
2) Push the new address using the [`PUSH /dnszone/<zoneid>/records/<recid>`](https://docs.bunny.net/reference/dnszonepublic_updaterecord) endpoint. The minimum JSON body for this step is:
```json
{ "Value": "<new value>", "Id": <recid> }
```

I'm not exactly sure how to implement this in Perl

**Comment by satrapes** [comment]
Hi @Thesola10 I had never touched Perl either but I made a pull request to add Njal.la DNS provider. Check it out [here](https://github.com/ddclient/ddclient/pull/459) I could possibly help you. As a minimum it would be helpful to provide some link to the documentation.
