### ISSUE TITLE
IO::Socket::INET6 is deprecated

### ISSUE THREAD

**Issue by Urumasi** [ddclient/ddclient#461]
[IO::Socket::INET6](https://metacpan.org/pod/IO::Socket::INET6) has been deprecated in favour of [IO::Socket::IP](https://metacpan.org/pod/IO::Socket::IP) which provides IPv6 functionality.
I propose that IO::Socket::INET6 is removed as a dependency and relevant code is rewritten using IO::Socket::IP

**Comment by michal-josef-spacek** [comment]
PR: https://github.com/ddclient/ddclient/pull/480

**Comment by michal-josef-spacek** [comment]
@SuperSandro2000 If you need some help, please ping me

**Comment by SuperSandro2000** [comment]
I am currently not actively working so on ddclient, so replacing deprecated components is really low on my todo list.

**Comment by michal-josef-spacek** [comment]
@SuperSandro2000 ok, thanks.
Tests are working, I believe that's ok. Still, some real tests could be fine.

**Comment by SuperSandro2000** [comment]
I think this got fixed in a PR.
