### ISSUE TITLE
"Feature" Request/Bug: Allow the same hosts multiple times

### ISSUE THREAD

**Issue by haarp** [ddclient/ddclient#464]
Hello,

let's say I have the same host `foo.bar.com` on two different services. One is the main, the other is a backup provider in case the other has problems. I can imagine other use-cases relating to redundancy/backup too.

When I do so in the config, ddclient will only update one of them. This is probably because `ddclient.cache`  uses the same entry for both services if they have the same host, and thus when it comes to updating the other, ddclient thus assumes that it's already been updated.

Maybe adding another key denoting the `server` to the cache fle could help?

Thanks a lot!

**Comment by SuperSandro2000** [comment]
This is a feature request and feature requests in the form of issues are no longer accepted.
