### ISSUE TITLE
freedns.afraid.org not updating

### ISSUE THREAD

**Issue by Taughtimp2786** [ddclient/ddclient#466]
These are not the full logs of `ddclient -daemon=0 -debug -verbose -noquiet` because my username and password were in it lots of times which was too tiring for me to censor.
```
WARNING:  found neither ipv4 nor ipv6 address
DEBUG:    get_ip: using ip, ip reports <undefined>
WARNING:  unable to determine IP address
WARNING:  found neither ipv4 nor ipv6 address
DEBUG:    get_ip: using ip, ip reports <undefined>
WARNING:  unable to determine IP address
WARNING:  found neither ipv4 nor ipv6 address
DEBUG:    get_ip: using ip, ip reports <undefined>
WARNING:  unable to determine IP address
WARNING:  found neither ipv4 nor ipv6 address
DEBUG:    get_ip: using ip, ip reports <undefined>
WARNING:  unable to determine IP address
WARNING:  found neither ipv4 nor ipv6 address
DEBUG:    get_ip: using ip, ip reports <undefined>
WARNING:  unable to determine IP address
Can't exec "sendmail": No such file or directory at /usr/bin/ddclient line 1647.
ddclient: cannot execute command | sendmail -oi root.
```

config:
```
daemon=300
syslog=yes
mail=root
mail-failure=root
pid=/var/run/ddclient.pid
ssl=yes
server=freedns.afraid.org
protocol=freedns
login=<username in lowercase>
password=<8 digit password>
domain1,domain2,domain3,domain4,domain5
```

**Comment by Taughtimp2786** [comment]
I am running `ddclient` using `systemd`.
output of `systemctl status ddclient.service`:
```
Oct 09 19:08:27 ryuo ddclient[20411]: WARNING:  found neither ipv4 nor ipv6 address
Oct 09 19:08:27 ryuo ddclient[20412]: WARNING:  found neither ipv4 nor ipv6 address
Oct 09 19:13:27 ryuo ddclient[20970]: WARNING:  found neither ipv4 nor ipv6 address
Oct 09 19:13:27 ryuo ddclient[20971]: WARNING:  found neither ipv4 nor ipv6 address
Oct 09 19:13:27 ryuo ddclient[20972]: WARNING:  found neither ipv4 nor ipv6 address
Oct 09 19:13:27 ryuo ddclient[20973]: WARNING:  found neither ipv4 nor ipv6 address
Oct 09 19:18:27 ryuo ddclient[21544]: WARNING:  found neither ipv4 nor ipv6 address
Oct 09 19:18:27 ryuo ddclient[21545]: WARNING:  found neither ipv4 nor ipv6 address
Oct 09 19:18:27 ryuo ddclient[21546]: WARNING:  found neither ipv4 nor ipv6 address
Oct 09 19:18:27 ryuo ddclient[21547]: WARNING:  found neither ipv4 nor ipv6 address
```

**Comment by Taughtimp2786** [comment]
`ddclient` was installed with `pacman` in `Arch Linux`

**Comment by Taughtimp2786** [comment]
Please tell me if you need any more information.

**Comment by dkerr64** [comment]
Your config file is missing statements to tell ddclient how to find your public IP address.  You need at a minimum a `ip=<something>` statement.

**Comment by Taughtimp2786** [comment]
Sorry for the very late reply.

I checked the config again, and I have three options.
I really want the least amount of delay and no useless unnecessary website loadings.
Will it be possible to use `use=if, if=enp1s0` as that seems it won't load any website or such. I have a dynamic updating IP address and if the `use=if` option isn't used for dynamic IPs, please tell if the `use=web` option is necessary.

Thanks.

**Comment by dkerr64** [comment]
The `use=if` option will be the most efficient... but it will only work if you are running ddclient on a system that is directly connected to the internet, so the interface has a publicly routable IP address.  If you are behind a NAT router then the interface has a local address which makes no sense to record at a public DNS service.

**Comment by Taughtimp2786** [comment]
I don't understand

**Comment by dkerr64** [comment]
> I don't understand

The purpose of ddclient is to update the **_public_** IP address of your server for your domain name at a DNS service.  ddclient needs to obtain that public IP address and there are many ways to do that... you can ask another server to tell you what your IP address is `use=web`, or you can specify the IP address yourself manually `use=ip`, or you can take the IP address assigned to a network interface of the system you are running ddclient on `use=if`.  Which you choose is up to your specific environment, but the most common would be `use=web` as it is the "no brainer" and most likely to give the correct result.

If you `use=if` and your system is behind a NAT router then you interface likely has a 192.168.x.y address.... recording that in a public DNS service does no good as any local address like a 192.168.x.y cannot be routed over the public internet.

**Comment by Taughtimp2786** [comment]
Thanks
That is all I needed to know. 
`use=web` is what I should use
