### ISSUE TITLE
Invalid Value for keyword 'ip' = ''

### ISSUE THREAD

**Issue by gforschi** [ddclient/ddclient#467]
I can't seem to be able to use this plugin with OpnSense and Cloudflare.

**Comment by kangaroo72** [comment]
Actually my system is down, but 2 weeks ago my system worked with cloudflare.
I had to change [this](https://github.com/ddclient/ddclient/pull/343/commits/ed128a0b99a5fbf2d3aab10320922c24c4364f6a)

**Comment by SuperSandro2000** [comment]
Dupe of #307
