### ISSUE TITLE
Not working on MacOS after 3.9.x -> 3.10.0

### ISSUE THREAD

**Issue by edrozenberg** [ddclient/ddclient#468]
Homebrew updated this today for me and now it no longer works as expected.

The first issue was a new requirement for `IO::Socket::SSL` - was never necessary w/ ddclient 3.9. Had to use `cpan` to install. `cpan` did its ugly horrible slow thing, testing etc., hundreds of lines of garbage, and finally finished (I know it's not "garbage" but have always hated everything about cpan and its horrible ugly installer).

Second issue is ddclient no longer executes properly, with the same config file I used previously. It hangs as follows:

```
$ sudo ddclient -foreground -verbose
Password:
CONNECT:  checkip.dyndns.com
```

My `ddclient.conf` looks like:

```
# /usr/local/etc/ddclient.conf
#

#~~~~~~~~~~~~~~~~~#
# Global settings #
#~~~~~~~~~~~~~~~~~#
syslog=yes
mail=root
mail-failure=root
ssl=yes

#use=web
#web=checkip.dyndns.com/

#~~~~~~~~~~~~~~~~~~~~~~~~~#
# DynDNS Personal Account #
#~~~~~~~~~~~~~~~~~~~~~~~~~#
use=web
web=checkip.dyndns.com/
custom=yes
server=members.dyndns.org
protocol=dyndns2
login=mylogin
password=mypassword
somehost.domain.com

#~~~~~~~~~~~~~~~~~~~~~~~#
# No-IP Account         #
#~~~~~~~~~~~~~~~~~~~~~~~#
use=web
web=checkip.dyndns.com/
web-skip='IP Address'
server=dynupdate.no-ip.com
protocol=dyndns2
login=somelogin@some.com
password=somepassword
somehost.domain.com

**Comment by edrozenberg** [comment]
Tried again and now that perl module doesn't even install properly. Junk/jank all the way with perl stuff. Thanks for any hints.

```
Failed 37/40 test programs. 1/238 subtests failed.
make: *** [test_dynamic] Error 2
Lockfile removed.
  SULLR/IO-Socket-SSL-2.075.tar.gz
one dependency not OK (Net::SSLeay); additionally test harness failed
  /usr/bin/make test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports SULLR/IO-Socket-SSL-2.075.tar.gz
Failed during this command:
 CHRISN/Net-SSLeay-1.92.tar.gz                : writemakefile NO '/opt/homebrew/Cellar/perl/5.36.0/bin/perl Makefile.PL' returned status 256
 SULLR/IO-Socket-SSL-2.075.tar.gz             : make_test NO one dependency not OK (Net::SSLeay); additionally test harness failed
```

**Comment by SuperSandro2000** [comment]
> The first issue was a new requirement for `IO::Socket::SSL` - was never necessary w/ ddclient 3.9. Had to use `cpan` to install.

That needs to be fixed in brew. I don't know much about darwin outside of nix but I would recommend to use brew to install the additional perl package instead of cpan. Not sure if that is supported.

**Comment by SuperSandro2000** [comment]
I don't own a Mac and I do not plan to invest any time myself fixing any issues outside of linux (and probably that only in very rare occasions).
