### ISSUE TITLE
Why is ddclient now ddclient.in?

### ISSUE THREAD

**Issue by brianread108** [ddclient/ddclient#473]
I am trying to incorporate the latest ddclient (3.10.0) into an rpm for the SMEServer distro.

However I cannot see what the purpose of renaming the perl code to ddclient.in.  

Can someone enlighten me please?

**Comment by SuperSandro2000** [comment]
I think it is only done to substitute the version number and sysconfdir.

**Comment by brianread108** [comment]
aha - yes I can see that in the makefile. Ok, so no other significance. I'll have to work out how to map the files in the install script for the rpm. 
Thanks for the pointer.
