### ISSUE TITLE
pid file not generated for arch linux

### ISSUE THREAD

**Issue by txelu** [ddclient/ddclient#476]
I could install ddclient-git v3.10.0.r0.g3e2cb0a-1 but the service didn't start, showing the following error:
```
nov 01 10:07:43 raspi-manjaro systemd[1]: Starting Dynamic DNS Update Client...
nov 01 10:07:43 raspi-manjaro ddclient[1024586]: WARNING:  file /var/cache/ddclient/ddclient.cache, line 1: program version mismatch; ignoring /var/cache/ddclient/ddclient.cache
nov 01 10:07:44 raspi-manjaro ddclient[1024586]: SUCCESS:  updating @: good: IP address set to X.X.X.X
nov 01 10:07:44 raspi-manjaro systemd[1]: ddclient.service: Can't open PID file /run/ddclient.pid (yet?) after start: Operation not permitted
nov 01 10:07:44 raspi-manjaro systemd[1]: ddclient.service: Failed with result 'protocol'.
nov 01 10:07:44 raspi-manjaro systemd[1]: Failed to start Dynamic DNS Update Client.
```
So the update worked but the service failed because the pid file was not generated. I could fix it by modifying the `ExecStart` in the `ddclient.service` file:
```
ExecStart=/usr/bin/ddclient -pid=/run/ddclient.pid -daemon=300
```
Without the `daemon` setting the pid file wasn't generated yet and if I omitted the `pid` setting the service seemed to wait for the value in the daemon setting before updating the ip and starting the service (300 s in my case). I'm using Manjaro-ARM 22.10 (in a raspberry pi).

**Comment by SuperSandro2000** [comment]
Probably runstatedir is missing here https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ddclient-git#n42 causing the file to be placed in /var/run I would assume.

**Comment by SuperSandro2000** [comment]
This is a distro problem which I am unable to help with.
