### ISSUE TITLE
ddclient 3.10.0 and OpenDNS update response make ddclient fail with "uninitialized value"

### ISSUE THREAD

**Issue by module0x90** [ddclient/ddclient#483]
Hi,

I am trying to update an OpenDNS network label with ddclient-3.10.0 - 3.10.0 as I needed Cloudflare API support.
Now my OpenDNS update fails with

```
SENDING:  GET /nic/update?system=dyndns&hostname=Home&myip=a.b.c.d. HTTP/1.1
SENDING:  Host: updates.opendns.com
SENDING:  Authorization: Basic ----------------
SENDING:  User-Agent: ddclient/3.10.0
SENDING:  Connection: close
SENDING:
RECEIVE:  HTTP/1.1 200 OK
RECEIVE:  date: Sat, 24 Dec 2022 11:32:22 GMT
RECEIVE:  server: opendns
RECEIVE:  vary: Accept-Encoding
RECEIVE:  content-type: text/html; charset=UTF-8
RECEIVE:  x-envoy-upstream-service-time: 48
RECEIVE:  x-xss-protection: 1; mode=block
RECEIVE:  x-ingress-point: lon
RECEIVE:  connection: close
RECEIVE:  transfer-encoding: chunked
RECEIVE:
RECEIVE:  11
RECEIVE:  good a.b.c.d.
RECEIVE:  0
RECEIVE:
FAILED:   updating Home: unexpected status (11)
Use of uninitialized value $h in hash element at /usr/bin/ddclient line 4101.
```
I have raised a ticket with OpenDNS - "[1404111]Some issue with ddclient 3.10.0 and responses from DDNS updates?". I will update this ticket here when I have a response.

I did check the sourcecode and even with not too much Perl experience I was able to determine the "11" response is rather stray.

Cheers

**Comment by goeranbruns** [comment]
Got the same issue here. Managed to circumvent the strange status error, with switch to curl. (-curl option)

**Comment by SuperSandro2000** [comment]
> I have raised a ticket with OpenDNS - "[1404111]Some issue with ddclient 3.10.0 and responses from DDNS updates?". I will update this ticket here when I have a response.

The problem is most likely on ddclients side and not opendns.

---

I am not using OpenDNS and with the limited time I spend on ddclient I don't have time to debug this. If someone finds a fix, they can create a PR and I'll merge it.

**Comment by SuperSandro2000** [comment]
dupe of #386
