### ISSUE TITLE
Generic failure command

### ISSUE THREAD

**Issue by ColinHebert** [ddclient/ddclient#484]
Currently alerts are sent via sendmail. It would be great to be able to have the ability to configure webhooks. In particular integrating with https://gotify.net/ as a way to send alerts when something went wrong.

**Comment by SuperSandro2000** [comment]
> Currently alerts are sent via sendmail.

There is such feature? I did not know.

> In particular integrating with [gotify.net](https://gotify.net/)

gotify itself is very limited but alternatives like ntfy.sh are also. Ideally we would use something more sophisticated like matrix or a library that implements many backends like apprise (which is written in python) or its cli.

**Comment by ColinHebert** [comment]
> There is such feature? I did not know.
Absolutely!

https://github.com/ddclient/ddclient/blob/master/ddclient.in#L2218
https://github.com/ddclient/ddclient/blob/master/ddclient.in#L2095-L2114

> gotify itself is very limited but alternatives like ntfy.sh are also. Ideally we would use something more sophisticated like matrix or a library that implements many backends like apprise (which is written in python) or its cli.

An alternative to apprise could be shoutrrr (https://github.com/containrrr/shoutrrr) It is for golang, but has a CLI and might be more lightweight.

**Comment by SuperSandro2000** [comment]
I would not accept an implementation that is specific to something but one that is just a generic command and people can then configure what they need.

**Comment by SuperSandro2000** [comment]
This is a feature request and feature requests in the form of issues are no longer accepted.
