### ISSUE TITLE
Keep passwords out of the ddclient.conf

### ISSUE THREAD

**Issue by ColinHebert** [ddclient/ddclient#485]
Currently ddclient expects to have a mix of sensitive (passwords) and non sensitive (configuration) data in ddclient.conf.
For the sake of clarity and to allow configuration files to be versioned without worrying having passwords leaking, it would be good to set a way for ddclient to obtain passwords from other files or environment variables rather than having to store them in the configuration file.

**Comment by SuperSandro2000** [comment]
The config is usually only 10 lines long. I would recommend to just store everything in a secure location and be done with it.

NixOS solves this problem by only replacing the secret into a temporary file at startup. Not ideal but better than nothing.

https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/networking/ddclient.nix#L32-L39


I myself have no plans to implement this.

**Comment by SuperSandro2000** [comment]
This is a feature request and feature requests in the form of issues are no longer accepted.

**Comment by JohnPaton** [comment]
For future searchers: This is supported now https://ddclient.net/#using-environment-variables

> ## Using environment variables
> As of version 3.11.0_1, ddclient supports using environment variables inside the configuration file. By appending ‘_env’ to a parameter, ddclient will interpret the value of that parameter as the name of an environment variable and use the value of that environment variable as the configuration value. This allows to keep sensitive information such as the login or password outside of the configuration file.
> ```
> login_env=DDCLIENT_LOGIN
> password_env=DDCLIENT_PASSWORD
> myhost.dyndns.org
> ```
>
> This example config file will use the value of the environment variables `DDCLIENT_LOGIN` and `DDCLIENT_PASSWORD` as the login and password for the domain myhost.dyndns.org respectively.

**Comment by dvergeylen** [comment]
> For future searchers: This is supported now https://ddclient.net/#using-environment-variables
> 
> > ## Using environment variables
> > As of version `3.11.0_1`, ddclient supports using environment variables inside the configuration file. By appending `_env` to a parameter, ddclient will interpret the value of that parameter as the name of an environment variable and use the value of that environment variable as the configuration value. This allows to keep sensitive information such as the login or password outside of the configuration file.
> > ```
> > login_env=DDCLIENT_LOGIN
> > password_env=DDCLIENT_PASSWORD
> > myhost.dyndns.org
> > ```
> > This example config file will use the value of the environment variables `DDCLIENT_LOGIN` and `DDCLIENT_PASSWORD` as the login and password for the domain myhost.dyndns.org respectively.


Very nice! If you use `ddclient` as a systemd service, you can even use the `EnvironmentFile=` directive to group your environment variables in a specific file.
