### ISSUE TITLE
Documentation missing to configure 1984.is [1984Hosting DNS]

### ISSUE THREAD

**Issue by jahway603** [ddclient/ddclient#489]
The README currently has
```
1984.is     - See https://www.1984.is/product/freedns/ for details
```
but there is nothing in the README or on the 1984.is website about which type of DynDNS protocol this is using or how to configure it; [there is nothing in the Wiki protocol section](https://github.com/ddclient/ddclient/wiki/protocols) about this; and I am having trouble finding any information/documentation on how to configure ddclient with this DNS provider.

I do have the API key and there is an example in [ddclient here](https://github.com/ddclient/ddclient/blob/master/ddclient.in#L5415) as well as mention of this provider [here](https://github.com/ddclient/ddclient/blob/master/ddclient.in#L542)

I need help figuring this out and then will gladly contribute to the documentation so that this is clear for future ddclient users who want to use this DNS provider.

**Comment by jahway603** [comment]
I'm using Debian 11, and their ddclient package is stuck at 3.9.1. Support for 1984 is not in that older version, so I opened a [request on the Debian Forum](https://forums.debian.net/viewtopic.php?t=153614) to update ddclient in the apt repos. I was able to figure out the syntax for this provider from [the example in ddclient here](https://github.com/ddclient/ddclient/blob/master/ddclient.in#L5390) and will document this soon.

**Comment by jahway603** [comment]
Now using ddclient 3.10.0 on Debian and this will not work. My ddclient.conf is trying to use both `protocol=dyndns2` and `protocol=1984` at the same time -- how can I do this in the config?

**Comment by SuperSandro2000** [comment]
> My ddclient.conf is trying to use both `protocol=dyndns2` and `protocol=1984` at the same time -- how can I do this in the config?

You can configure multiple backends by using comma ``,`` and backslash ``\`` to essentially make the config parser think it is a single line and does not apply to all hosts.

something like this if I remember this correct:

```
protocol=dyndns2, a=b, c=d, ....
```
or
```
protocol=dyndns2, \
a=b, \
c=d, \
....
```

that is also shown on the wiki https://github.com/ddclient/ddclient/wiki/protocols#dyndns2

FYI the wiki is not maintained and I don't have any plans to change that.
