### ISSUE TITLE
Cloudflare "No zone ID found" for domain contaning non unicode characters.

### ISSUE THREAD

**Issue by lorenc88** [ddclient/ddclient#492]
I'm running ddclient version 3.10.0 in docker container (https://hub.docker.com/r/linuxserver/ddclient). 
All domains are served flawlessly except one containing non-unicode characters (ś and ł). The log output says:
`FAILED:   updating śłdomainname.com: No zone ID found.`

Found related issues #259 #337 and tried to update the config using https://www.punycoder.com/ to convert the problematic name but the output remains the same.

**Comment by SuperSandro2000** [comment]
Did you add the hostname as punycode to your DNS provider?

PS:

The linuxserver.io docker image is build wrong. They are symlinking the ddclient.in file instead of using autoconf. This is not supported and might break anytime without notice.

**Comment by lorenc88** [comment]
> Did you add the hostname as punycode to your DNS provider?
> 
> PS:
> 
> The linuxserver.io docker image is build wrong. They are symlinking the ddclient.in file instead of using autoconf. This is not supported and might break anytime without notice.

It was added as is, than I deleted this zone and readded punified (in cloudflare UI it is still presented in unpunified form). Error in ddclient remains the same.
