### ISSUE TITLE
Documentation missing to use more than one DNS service provider

### ISSUE THREAD

**Issue by jahway603** [ddclient/ddclient#493]
Documentation missing to use more than one DNS service provider. I am filing this issue as I experienced ddclient not able to login/use the 2nd DNS provider configured in ddclient.conf (as mentioned in Issue https://github.com/ddclient/ddclient/issues/489)

**Comment by SuperSandro2000** [comment]
https://github.com/ddclient/ddclient/blob/3149171aa70a95d0b933eaa97a4dcd4fb5adedef/ddclient.in#L5482-L5499 is the documentation. There is no other documentation I am aware off and due to limited maintenance there won't be any new things added by myself.
