### ISSUE TITLE
-bash: ./configure: No such file or directory (am I an idiot)?

### ISSUE THREAD

**Issue by Mnchstrcityblues79** [ddclient/ddclient#509]
Greetings; as always, thank you so much for all the work you do.

I am attempting to install ddclient-3.10.0 manually on my Ubuntu 22.04 Linux Container.  I download the source tar, un-tar it, cd into it and then run: 

```
./configure \
    --prefix=/usr \
    --sysconfdir=/etc/ddclient \
    --localstatedir=/var
```

Unfortunately, I continually receive:

`-bash: ./configure: No such file or directory`

I do notice there is an `configure.ac` but when replacing `./configure` with `./configure.ac`, I receive (even if root):

`-bash: ./configure.ac: Permission denied`

Any suggestions?  Thank you!

**Comment by Ahajha** [comment]
Are you running `./autogen` first?
