### ISSUE TITLE
`web=checkip.dyndns.org` does not work.

### ISSUE THREAD

**Issue by ryu0q** [ddclient/ddclient#510]
I am using:
```
use=web, web=freedns.afraid.org/dynamic/check.php
freedns.afraid.org
protocol=freedns
login=<redacted>
password=<redacted>
subdomain.domain.tld,subdomain2.domain.tld
```
and it works fine. But when `web=` is set to `checkip.dyndns.org`, it just doesn't update any of my subdomains.

**Comment by ryu0q** [comment]
I assume this happens because `checkip.dyndns.org` doesn't use SSL

**Comment by ryu0q** [comment]
`web=freedns.afraid.org/dynamic/check.php` works just fine.
But `checkip.dyndns.org` is the default for `use=web`. It would be difficult for many people to figure out why it might not be working.

**Comment by daxhuiberts** [comment]
The default config has `ssl=yes` and then using `use=web` results in the above problem. In that case the process hangs till the timeout. It doesn't respond to any SIGINT or SIGTERM either when it's trying to connect. Perhaps it's an idea to use an ssl supported host for `use=web` instead?
