### ISSUE TITLE
ddclient for cloudflare only works with curl=yes

### ISSUE THREAD

**Issue by wlarsong** [ddclient/ddclient#513]
I am running Ubuntu 20.04 and cloned the most recent master branch of ddclient and built the code from source.

I have a cloudflare dns and here is my config paras

> daemon=300                              # check every 300 seconds
syslog=yes                              # log update msgs to syslog
pid=/var/run/ddclient.pid               # record PID in file.
use=web
protocol=cloudflare
zone=domain.com
ttl=1
login=email@domain.com
password=MYGLOBALAPIKEY 
domain.com,sub.domain.com

If I run this : sudo ddclient -daemon=0 -debug -verbose -noquiet
It will hang on

>DEBUG:    get_ip: using ip, ip reports XXX.XXX.XXX.XXX
DEBUG:    
DEBUG:    nic_cloudflare_update -------------------
INFO:     getting Cloudflare Zone ID for sub.domain.com
DEBUG:    proxy    = <undefined>
DEBUG:    protocol = https
DEBUG:    server   = api.cloudflare.com
DEBUG:    url      = client/v4/zones/?<redacted>
DEBUG:    ip ver   = 
CONNECT:  api.cloudflare.com

and after 5 minutes of hanging it will spit out

> RECEIVE:  HTTP/1.1 400 Bad Request
RECEIVE:  Date: Mon, 06 Feb 2023 20:05:52 GMT
RECEIVE:  Content-Type: application/json
RECEIVE:  Transfer-Encoding: chunked
RECEIVE:  Connection: close
RECEIVE:  CF-Ray: 795680cbdbf8800e-SAN
RECEIVE:  Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
RECEIVE:  Expires: Sun, 25 Jan 1981 05:00:00 GMT
RECEIVE:  Set-Cookie: __cflb=0H28vgHxwvgAQtjUGU4vq74ZFe3sNVUZWyRrkToijoj; SameSite=Lax; path=/; expires=Mon, 06-Feb-23 22:35:53 GMT; HttpOnly
RECEIVE:  Strict-Transport-Security: max-age=31536000
RECEIVE:  CF-Cache-Status: DYNAMIC
RECEIVE:  Pragma: no-cache
RECEIVE:  X-Content-Type-Options: nosniff
RECEIVE:  X-Frame-Options: SAMEORIGIN
RECEIVE:  Set-Cookie: __cfruid=32764b950a9312798fb96e667b52a4d7bf73cea0-1675713952; path=/; domain=.api.cloudflare.com; HttpOnly; Secure; SameSite=None
RECEIVE:  Server: cloudflare
RECEIVE:  
RECEIVE:  b9
RECEIVE:  {"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6103,"message":"Invalid format for X-Auth-Key header"}]}],"messages":[],"result":null}
RECEIVE:  0

If I enable curl=yes 
everything works.

If this expected behavior?

**Comment by SuperSandro2000** [comment]
> I am running Ubuntu 20.04 and cloned the most recent master branch of ddclient and built the code from source.

Please use the latest release. master might be broken for specific providers.

> If this expected behavior?

No, but I lack the time to fix the legacy provider and using curl for http requests is more robust then self written perl code.

**Comment by EqualMa** [comment]
I just found out the password must be the *Global API Key* instead of *API Token*.

**Comment by Nezteb** [comment]
> I just found out the password must be the _Global API Key_ instead of _API Token_.

That's unfortunate, because [Cloudflare lists global API keys as legacy](https://developers.cloudflare.com/fundamentals/api/get-started/keys/). I wouldn't be surprised if they eventually deprecate them entirely. 🤔 

I did find [a post on the OpenDNS forum about setting up DNS-O-Matic with Cloudflare though](https://support.opendns.com/hc/en-us/community/posts/115000937008-How-to-set-up-DNS-O-MATIC-for-Cloudflare-and-the-other-way-around-and-a-FritzBox).

I'll try out a few things and report back.
