### ISSUE TITLE
WARNING:  skipping update ... Wait at least 5 minutes between update attempts.

### ISSUE THREAD

**Issue by oscarfv** [ddclient/ddclient#514]
Since my Debian Testing box upgraded ddclient from 3.9 to 3.10, every few hours I'm receiving this mail:

```
WARNING:  skipping update of <domain-name-redacted> from <nothing> to <ip-address-redacted>.
WARNING:  last updated Fri Feb 10 17:23:27 2023 but last attempt on Fri Feb 10 17:23:27 2023 failed.
WARNING:  Wait at least 5 minutes between update attempts.
WARNING:  skipping update of <another-domain-name-redacted> from <nothing> to <ip-address-redacted>.
WARNING:  last updated Fri Feb 10 17:23:27 2023 but last attempt on Fri Feb 10 17:23:27 2023 failed.
WARNING:  Wait at least 5 minutes between update attempts.
``` 

Please note that it shows exactly the same hour for `last updated` and `last attempt`. How can this be? I already checked that there is only one instance of ddclient running.

My configuration:

```
daemon=1h
syslog=yes
mail=root
mail-failure=root

protocol=freedns, \
server=freedns.afraid.org, \
use=web, \
web=http://checkip.feste-ip.net/, \
curl=yes, \
ssl=no, \
login=<redacted>, \
password=<redacted> \
<domain-name-redacted>,<another-domain-name-redacted>
```

I added `curl=yes` and `ssl=no` in an attempt to fix the issue, as recommend in #449. I also tried `webv4`, `usev4` but they caused new problems (ip check failed.)

**Comment by MADXhh** [comment]
+1 
Same issue

**Comment by SuperSandro2000** [comment]
The cache is currently broken but I lack the time to fix it. There are already multiple other issues related to this. Please help fixing the bug by creating a PR.
