### ISSUE TITLE
v3.9.1 Ubuntu 22.04 - dnspark is no more, causing testing issues

### ISSUE THREAD

**Issue by FarYetNear** [ddclient/ddclient#526]
Within the ddclient perl, line 72 calls "...dnspark,com" for use in -query testing.  Dnspark.com no longer provides address information, from all testing I have done.    This site change causes an "unable to connect" error in the "-query" testing results.     

I replaced the url on line 72 within the ddclient perl with "checkip.dynu.com" and the connection error while using "-query" went away.

**Comment by SuperSandro2000** [comment]
dnspark got already removed.
