### ISSUE TITLE
AnyDNS support

### ISSUE THREAD

**Issue by japoch** [ddclient/ddclient#530]
Hi,

I've added support for the [AnyDNS API](https://anydns.info/faq.php).

Now I want to push my feature branch to your repo and create an PR if possible and you find my feature useful.

BR,
japoch

**Comment by SuperSandro2000** [comment]
https://github.com/ddclient/ddclient/issues/528#:~:text=I%20closed%20all%20feature%20requests.%20They%20where%20not%20considered%20in%20the%20past%20year%20and%20will%20not%20be%20considered%20by%20myself%20in%20the%20future.%20Please%20refrain%20from%20opening%20new%20ones.
