### ISSUE TITLE
ipv6 is not working 

### ISSUE THREAD

**Issue by 18569510529** [ddclient/ddclient#534]
**1、 /etc/ddclient.conf configured as below:**
<img width="690" alt="image" src="https://user-images.githubusercontent.com/79614737/231107555-453e2ffa-a024-43a4-b187-1d73c97f6c1c.png">

**2、 systemctl status ddclient shows updating by ipv6 address**
<img width="1397" alt="image" src="https://user-images.githubusercontent.com/79614737/231106918-99cc62db-91f3-4c84-acc0-34430976f28f.png">

**3、 The problem is when checking in dynv6.com,there updated by the ipv4 address.**
<img width="438" alt="image" src="https://user-images.githubusercontent.com/79614737/231107406-e37221a2-44f6-4e7b-b40c-ba7fbe23248b.png">

please let me know if someone can help to resolve the issue, thx.

**Comment by SuperSandro2000** [comment]
The cmd to get the ip returns all ipv6 addresses and I think it should also be cmdv6 or cm6.

**Comment by 18569510529** [comment]
> The cmd to get the ip returns all ipv6 addresses, ddclient needs a single one, and I think it should also be cmdv6 or cmd6.

Thank you for your answer. I specify eth0 in the command and i am sure there return only one ipv6 address. 
I thought it should be the version problem, i install 3.9 but i checked the website,  it seems support ipv6 only from 3.10.

**Comment by SuperSandro2000** [comment]
> I specify eth0 in the command and i am sure there return only one ipv6 address.

I tried it locally and got over 10 IPv6 addresses. I think you need a local fe80 address for IPv6 to work and that would not be filtered.

> I thought it should be the version problem, i install 3.9 but i checked the website, it seems support ipv6 only from 3.10.

I don't really know, ddclient is in kinda abounded and unsupported and anything other than the latest version is absolutely unsupported.
