### ISSUE TITLE
Issues with "my ip" detection over cell networks

### ISSUE THREAD

**Issue by edrozenberg** [ddclient/ddclient#535]
When using a cell/hotspot connection with checkip.dyndns.com, ddclient frequently/always retrieves an incorrect value for my own IP.

I use:
```
ssl=no
use=web, web=checkip.dyndns.com/, web-skip='IP Address'
```

For ex. checkip.dyndns.com might return 1.2.3.4 while my actual IP (via for ex. https://www.whatismyip.com) might be 1.2.3.20.

Current workaround: activate a VPN service. When a VPN connection is active, this helps checkip.dyndns.com to return the correct IP address.

Not directly a ddclient issue but curious if anyone has found a solution or alternate ip checker api to use instead of checkip.dyndns.com, that does a proper job. Or maybe I need to run my own "whatismyip" api service on a server to do a better job than checkip.dyndns.com.

**Comment by SuperSandro2000** [comment]
In cell networks you are often behind NAT. Nothing ddclient can do to fix this.
