### ISSUE TITLE
[question] support for HTTP GET with custom url

### ISSUE THREAD

**Issue by kcris** [ddclient/ddclient#541]
Is there a way in ddclient to specify a URL (with a placeholder for the IP)
and just have ddclient perform an HTTP GET using that url?

some dns providers do allow simple dyndns updates via their urls (cloudns, afraidns)

Such URLs can vary, some need user/pass basic auth, others use some custom tokens but no need for user/pass
so it's hard to deal with multiple dns providers because of different url params.

However, if I could 
* specify the full url 
* url supports a placeholder, e.g. `${IP}`
 
and just have ddclient replace `${IP}` with actual ip 
and then do an HTTP GET

this would allow using a few dns providers without too much hassle.

Thanks

**Comment by SuperSandro2000** [comment]
New features are not considered.
