### ISSUE TITLE
http1.1 chunked encoding

### ISSUE THREAD

**Issue by alacn1** [ddclient/ddclient#548]
ddclient v3.10.0 is broken, failing to parse server response because chunked transfer-encoding.

```
SENDING:  GET /... HTTP/1.1
SENDING:  Host: ...
SENDING:  User-Agent: ddclient/3.10.0
SENDING:  Connection: close
[...]
RECEIVE:  HTTP/1.1 200 OK
[...]
RECEIVE:  Connection: close
RECEIVE:  Transfer-Encoding: chunked
RECEIVE:
RECEIVE:  15
RECEIVE:  nochg xxx.xxx.xxx.xxx
RECEIVE:  0
RECEIVE:
FAILED:   updating yyy.yyy.com: unexpected status (15)
```

PR #333 9a44eeb changed from `HTTP/1.0` to `HTTP/1.1` in geturl fetch_via_socket_io.
Chunked transfer encoding is required for HTTP/1.1.

To get it working need revert request to HTTP/1.0 or add support chunked encoding for HTTP/1.1.

**Comment by SuperSandro2000** [comment]
Chunked encoding would be a new feature and those are no longer accepted in the form of issues.

**Comment by SuperSandro2000** [comment]
The maintainers should just ditch the hand crafted http code and either replace it with a library or always use curl.

**Comment by LenardHess** [comment]
@straight-shoota I expect this to work since curl is now always used - but it never hurts to confirm. Can you verify that v3.11.0_1 no longer has the issue?

**Comment by straight-shoota** [comment]
Yes, I can confirm this issue does not reproduce with v3.11.0_1 🎉
