### ISSUE TITLE
debian bookworm: not a valid IPv4 or IPv6 address

### ISSUE THREAD

**Issue by hajohoetger** [ddclient/ddclient#550]
Hello,
may i kindly ask for your help? I have been using ddclient for more than one year without any problems. The box ist a Raspberry Pi. Yesterday i upgraded to debian bookworm (which brings ddclient version 3.10.0). I want to upgrade only the v6 address and ddclient tells me, it can't find one.

From journalctl:
--> Jun 29 17:12:13 gargamel ddclient[10248]: WARNING: '' is not a valid IPv4 or IPv6 address

Then i started 'ddclient -daemon=0 -debug -verbose -noquiet' as supposed in the helpfile. It seems, that the address is detected correctly, but not passed to the web interface.

DEBUG: get_ipv6: using (ifv6, default) reports 2a01:c22:8c61:4900:c3aa:dead:7fd2:4145
DEBUG:
DEBUG: nic_dyndns2_update -------------------
INFO: setting IP address to for gargamel.firewall-gateway.com
UPDATE: updating gargamel.firewall-gateway.com
DEBUG: proxy =
DEBUG: protocol = https
DEBUG: server = update.spdyn.de
DEBUG: url = nic/update?
DEBUG: ip ver =
CONNECT: update.spdyn.de
CONNECTED: using SSL
SENDING: GET /nic/update?system=dyndns&hostname=gargamel.firewall-gateway.com&myip= HTTP/1.1
SENDING: Host: update.spdyn.de
SENDING: Authorization: Basic cGl1cy5maXJld2FsbC1nYXhsgGtiaOgqbTp2aGRoLXF2enYtaGRkdg==
SENDING: User-Agent: ddclient/3.10.0
SENDING: Connection: close
SENDING:
RECEIVE: HTTP/1.1 400 Bad Request

Is this a known bug? I have several other servers running debian bullseye which i plan to bring to bookworm shortly.
tia
HaJo

**Comment by SuperSandro2000** [comment]
see https://github.com/ddclient/ddclient/issues/528#issuecomment-1620070572

**Comment by paulastronaut** [comment]
Hey @hajohoetger, don't know for sure, but this could be the same error: [https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1038247](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1038247) Replacing a file on my system with a file from this repo as described in my bug report solved my issue. Ugly hack, but it works. :-) HTH, Paul

**Comment by hajohoetger** [comment]
Hi Paul,
Am Thu, Nov 23, 2023 at 02:58:45AM -0800 schrieb paulastronaut:
> Hey @hajohoetger, don't know for sure, but this could be the same error: [https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1038247](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1038247) Replacing a file on my system with a file from this repo as described in my bug report solved my issue. Ugly hack, but it works. :-) HTH, Paul
> 

Thank you very much for your answer.  After some days
without dyndns updates and no clue on how to solve this with
ddclient i started to look around for alternatives.
Meanwhile all my boxes are on bookworm, running inadyn as
dyndns client. This works fairly well with some tweeks.
cheers
-- 
Hans-Joachim Hötger

             "Klug ist jener, der Schweres einfach sagt."
                                                       Albert Einstein
