### ISSUE TITLE
Providers: fix various old caching issues

### ISSUE THREAD

**Issue by rrthomas** [ddclient/ddclient#554]
Some providers have improper implementations with regards to caching. It seems that these implementations never did right in the first place.

These fixes are not required for the v3.11 release, that was handled in rrthomas/ddclient#10 .

Providers without proper cache parameter implementation:
- [ ] 1984
- [ ] Njalla
- [x] nsupdate

**Comment by rhansen** [comment]
nsupdate was fixed in #604 (commit bfe20e75f865e80dffbcb8648ea1539e3e31ec5a)
