### ISSUE TITLE
DuckDNS behind proxy

### ISSUE THREAD

**Issue by nkgiovannivl** [ddclient/ddclient#563]
Hi All,

I'm trying to setup my config, but I'm getting this error:

```
CONNECT:  www.duckdns.org via proxy 10.158.100.187:8080
WARNING:  cannot connect to 10.158.100.187:8080 socket: SSL connect attempt failed error:0A000126:SSL routines::unexpected eof while reading SSL connect attempt failed error:0A000126:SSL routines::unexpected eof while reading
FAILED:   updating mybestdomain.duckdns.org: Could not connect to www.duckdns.org.
```
What means this error to start check my options? Thanks!

**Comment by LenardHess** [comment]
Hello,

apologies for this issue slipping through the cracks for a while.

It looks like the connection to the proxy is attempted as an SSL connection but is refused. I haven't looked much at the proxying feature so far. What does your setup look like?

**Comment by nkgiovannivl** [comment]
Thanks! The issue is proxy, has blocked querys to some dns including duckdns

**Comment by LenardHess** [comment]
Ok, so not a ddclient issue :+1:
