### ISSUE TITLE
Google Domains Transfer to Squarespace Domains

### ISSUE THREAD

**Issue by heyhewmike** [ddclient/ddclient#564]
Squarespace has purchased or is in the process of purchasing all TLDs from Google Domains. They will be taking all Domain Registrar and DNS Records so the Google DDNS may not be able to update the records.

I do not presently see squarespace DNS as an option for the 'Service' Dropdown.

Please see the announcement:
https://newsroom.squarespace.com/blog/googledomains

Here is the Squarespace FAQs:
https://domains.squarespace.com/faq

Please look into adding Squarespace as a new 'Service' so that once the Deal has been processed and the TLDs & DNS Records are moved the plugin can be updated to use Squarespace DNS to be updated dynamically.

**Comment by alex-titarenko** [comment]
Today I got the following email from Google which informs me that SquareSpace does not support DDNS :(
Looks like it's time to look for another domain registrar...

> As previously communicated, Squarespace has purchased all domain name registrations and related customer accounts from Google Domains. Customers are in the process of being moved to Squarespace Domains, but before we migrate your domain **** we wanted to inform you that a feature you use, **Dynamic DNS** (DDNS), will not be supported by Squarespace.
> 
> After your domain has been migrated, you will no longer be able to update DDNS records using the DDNS service offered by Google Domains. Any active DDNS records will remain as A and/or AAAA records with the last IP addresses provided prior to migration, but those IP addresses will no longer update automatically. If you leave any DDNS client active, it will receive an error when trying to perform an update.
>
> **Action required**
>
> Since Squarespace Domains doesn’t offer DDNS services, you should consider looking for an alternative from another provider and configure that ahead of your domain migration. Your domain will be migrated as soon as 30 days from today, so please act now to ensure your DDNS records will continue to work as you’d like.
>
> You’ll receive another email after your domain migrates successfully to Squarespace Domains.

**Comment by heyhewmike** [comment]
I got the same email just a few minutes ago. Now I have research to do.

> Today I got the following email from Google which informs me that SquareSpace does not support DDNS :(
> Looks like it's time to look for another domain registrar...
>

**Comment by alex-titarenko** [comment]
It's another confirmation to not use Google Services... @heyhewmike curious about which provider you would peak, I need to research now too.

**Comment by alex-titarenko** [comment]
On a side note, I contacted SquareSpace support if they have any plans to add support of DDNS, and this is what I got:

> I understand you are wondering if we have plans to add the feature for DDNS in the future. We do not have plans to add this feature that I am aware of.

**Comment by dannybloomfield** [comment]
>  that I am aware of.
🤦 
Who did you go with, @alex-titarenko ?

**Comment by alex-titarenko** [comment]
> > that I am aware of.
> 
> 🤦 Who did you go with, @alex-titarenko ?

http://porkbun.com - they are the only ones who checked all of the boxes for my requirements, and I'm not regretting so far.

**Comment by dannybloomfield** [comment]
> > > that I am aware of.
> > 
> > 
> > 🤦 Who did you go with, @alex-titarenko ?
> 
> http://porkbun.com - they are the only ones who checked all of the boxes for my requirements, and I'm not regretting so far.

Looks interesting. What made them stand out to you? It all looks so commoditized that in not sure where to begin.

**Comment by alex-titarenko** [comment]
> > > > that I am aware of.
> > > 
> > > 
> > > 🤦 Who did you go with, @alex-titarenko ?
> > 
> > 
> > http://porkbun.com - they are the only ones who checked all of the boxes for my requirements, and I'm not regretting so far.
> 
> Looks interesting. What made them stand out to you? It all looks so commoditized that in not sure where to begin.

Support of URL forwarding with path forwarding over HTTPS probably was the main feature which was not present on any other provider I checked. Meaningful support that was able to answer all of my questions. Some nice touches like Passkey support for auth and Apple Pay support.

**Comment by heyhewmike** [comment]
> > 
> > 🤦 Who did you go with, @alex-titarenko ?
> 
> http://porkbun.com - they are the only ones who checked all of the boxes for my requirements, and I'm not regretting so far.

@alex-titarenko 
Do you have anything documented on how to configure the client for Porkbun or any handy links?

**Comment by alex-titarenko** [comment]
> > > 🤦 Who did you go with, @alex-titarenko ?
> > 
> > 
> > http://porkbun.com - they are the only ones who checked all of the boxes for my requirements, and I'm not regretting so far.
> 
> @alex-titarenko Do you have anything documented on how to configure the client for Porkbun or any handy links?

You can find the configuration sample for ddclient here: https://github.com/ddclient/ddclient/blob/ab9ac65f46a2ef6e240ce80a0617e8067630fee2/ddclient.conf.in#L300

**Comment by rhansen** [comment]
I was hoping to add a new `squarespace` protocol with `googledomains` as an alias to ease the transition, but as far as I can tell Squarespace does not have a dynamic DNS API or any plans to add such a service.  I'm afraid there's not much that can be done other than delete `googledomains` from ddclient.
