### ISSUE TITLE
Unknown option: daemon 300 -syslog -pid /var/run/ddclient.pid

### ISSUE THREAD

**Issue by zixijian** [ddclient/ddclient#566]
On Ubuntu 22.04
```
service ddclient start
Unknown option: daemon 300 -syslog -pid /var/run/ddclient.pid
usage: ddclient [options]

service ddclient stop
No /usr/bin/perl found running; none killed.
```

**Comment by zixijian** [comment]
copy & replace `/etc/init.d/ddclient` from Ubuntu18,solved.

**Comment by MossabDiae** [comment]
> copy & replace `/etc/init.d/ddclient` from Ubuntu18,solved.

Having same issue on MX Linux 21
Can you kindly upload the file or provide a url to it, thanks

**Comment by zixijian** [comment]
> > copy & replace `/etc/init.d/ddclient` from Ubuntu18,solved.
> 
> Having same issue on MX Linux 21 Can you kindly upload the file or provide a url to it, thanks

/`

**Comment by LenardHess** [comment]
> service ddclient start
Unknown option: daemon 300 -syslog -pid /var/run/ddclient.pid
usage: ddclient [options]
>
> service ddclient stop
No /usr/bin/perl found running; none killed.

This original report has a malformed argument: `daemon` should be `-daemon`. As a result ddclient aborts with the usage info, and the `service ddclient stop` cannot find a ddclient process to stop.
