### ISSUE TITLE
cloudflare - wildcard A record

### ISSUE THREAD

**Issue by thezoggy** [ddclient/ddclient#574]
I cant seem to figure out how to make ddclient update cloudflare when I only use a A wildcard.
![cf](http://zoggy.net/2023-10-08_13-09-15.png)

as ddclient wants to filter the list of dns_records by name (internally what ddlicent knows as the domain) it always results in not getting any A records because of
https://github.com/ddclient/ddclient/blob/master/ddclient.in#L6101

resulting in:
> FAILED:   updating \: Cannot set IPv4 to <removed> No 'A' record at Cloudflare

trying to do something like this:
```
protocol=cloudflare,        \
zone=domain.tld,            \
ttl=1,                      \
password=xxx
  
```
it breaks because no domain defined...

```
protocol=cloudflare,        \
zone=domain.tld,            \
ttl=1,                      \
wildcard=yes,               \
password=xxx
*
```
also did not work. 

not sure why this didnt work before (maybe i left off wildcard=yes) but got this to finally update:
```
protocol=cloudflare,        \
zone=domain.tld,            \
ttl=1,                      \
wildcard=yes,               \
password=xxx
*.domain.tld
```

**Comment by LZeugirdor** [comment]
I'm trying to get this working but I'm having some difficulty
