### ISSUE TITLE
Getting "Invalid version format line 24" upon startup

### ISSUE THREAD

**Issue by hubertbanas** [ddclient/ddclient#579]
Running ddclient v3.11.0 via docker container using  linuxserver.io image at https://github.com/linuxserver/docker-ddclient

Here is the message upon start:

```bash
Invalid version format (non-numeric data) at /usr/bin/ddclient line 24.
```

And here is that line 24 diff

```bash
# v3.10.0
use version 0.77; our $VERSION = version->declare('v3.10.0');

# v3.11.0
use version 0.77; our $VERSION = version->declare('@PACKAGE_VERSION@');
```

Here is that specific [commit](https://github.com/ddclient/ddclient/commit/36744e5b205c676b326e72de5cf81ed7ad437f64) from October 25 2022

```bash
commit 36744e5b205c676b326e72de5cf81ed7ad437f64
Author: Sandro Jäckel <sandro.jaeckel@sap.com>
Date:   Tue Oct 25 15:46:33 2022 +0200

    set version number via autoconf

diff --git a/ddclient.in b/ddclient.in
index 5e4759e..05bafc3 100755
--- a/ddclient.in
+++ b/ddclient.in
@@ -30,8 +30,8 @@ use IO::Socket::INET;
 use Socket qw(AF_INET AF_INET6 PF_INET PF_INET6);
 use Sys::Hostname;
 
-use version 0.77; our $VERSION = version->declare('v3.10.0');
-(my $version = $VERSION->stringify()) =~ s/^v//;
+use version 0.77; our $VERSION = version->declare('@PACKAGE_VERSION@');
+my $version = $VERSION->stringify();
 my $programd = $0;
 $programd =~ s%^.*/%%;
 my $program = $programd;

```

Let me know if this is an upstream issue or docker specific and should be reported to linuxserver.io
Thanks!

**Comment by spencerhughes** [comment]
I replaced `@PACKAGE_VERSION@` with `v3.11.0` and that immediately resolved the issue, so I believe the issue is with ddclient and not with the LSIO image.

**Comment by misterjtc** [comment]
I am also experience this issue with the lsio container.

**Comment by LenardHess** [comment]
The `@PACKAGE_VERSION@` is a placeholder for autoconf to replace ([here](https://github.com/ddclient/ddclient/blob/9913e0ec2997568158d97830f2c373b7ad658bd5/Makefile.am#L21))

On first glance, the LSIO build just copies ddclient.in, without running autoconf ([here](https://github.com/linuxserver/docker-ddclient/blob/8e59f00d5fcb20619f8c3e78f0e81078220f86e9/Dockerfile#L45)).

The older uses of autoconf had a code-based fallback path for replacing other uses of autoconf placeholders ([here](https://github.com/ddclient/ddclient/blob/0b8d391b26788f731fe937696eb3970eb06a6c12/ddclient.in#L45)), but the `@PACKAGE_VERSION@` does not.

**Comment by hubertbanas** [comment]
@LenardHess, good info. Do you suggest  linuxserver.io handles the substitution via Dockerfile? Or would you rather have a fix here?

**Comment by LenardHess** [comment]
The suggested steps for installation are [here](https://github.com/ddclient/ddclient#manual-installation).
Those take care of the substitution.

I haven't looked much into the autoconf stuff so far, so I don't hold much of an opinion yet on how to proceed.
@nemchik Can the lsio docker image build incorporate the suggested installation sequence?

**Comment by nemchik** [comment]
It looks like we need to run `./autogen` which shouldn't be a big issue, but I also see
```
./configure \
    --prefix=/usr \
    --sysconfdir=/etc/ddclient \
    --localstatedir=/var
make
make VERBOSE=1 check
sudo make install
```
and I'd like to know what all those flags end up doing?

We install to `/usr/bin/ddclient` and manually specify where the conf file should be read from (and symlink that to a user accessible persistent volume). So another question I have is if we don't specify `-file <conf_location>` where does it try to read the conf from?

Lastly, we've got a handful of dependencies installed such as perl and some perl modules, but I can't tell what is required vs what might have been from legacy requirements. What are the actual required dependencies currently?

With those things answered, I can probably clean up the image a bit.

**Comment by LenardHess** [comment]
@nemchik i will take some time to document those flags/the build process.

In the meantime i will revert the commit as a hotfix (hopefully later today) until the build process docs are there and lsio has adopted it :+1:

**Comment by LenardHess** [comment]
v3.11.1 is released, the `@PACKAGE_VERSION@` string got replaced with the version string.
