### ISSUE TITLE
Unnecessary updates in version 3.11.1

### ISSUE THREAD

**Issue by toby63** [ddclient/ddclient#601]
**Log:**
```
Nov 18 23:05:18 Berry2 systemd[1]: Stopped Dynamic DNS Update Client.
Nov 18 23:05:18 Berry2 systemd[1]: Starting Dynamic DNS Update Client...
Nov 18 23:05:18 Berry2 systemd[1]: Started Dynamic DNS Update Client.
Nov 19 02:35:21 Berry2 ddclient[1477]: WARNING:  updating [REDACTED].info: nochg: No update required; unnecessary attempts to change to the current address are considered abusive
Nov 19 03:35:22 Berry2 ddclient[1637]: WARNING:  updating [REDACTED].info: nochg: No update required; unnecessary attempts to change to the current address are considered abusive
Nov 19 05:05:23 Berry2 ddclient[1879]: WARNING:  updating [REDACTED].info: nochg: No update required; unnecessary attempts to change to the current address are considered abusive

[multiple more of these, until my DynDNS service blocked me.]
```

**More Infos:**
OS: Manjaro Linux for ARM64
Computer System: Raspberry Pi 400 (aarch64)
ddclient version: 3.11.1
DynDns service: nsupdate.info

The cache exists and looks ok to me.
I tried to delete the cache multiple times, but it did not help.

Then I downgraded and Version **3.10.0** works as expected.

The bug looks similar to:
#544

The ddclient.conf file below is used.
It always worked well and nsupdate.info is also recommending it as is (at least the part below the general configuration).

**ddclient.conf:**
```
# /etc/ddclient.conf

daemon=1800                              # in seconds
syslog=yes                              # log update msgs to syslog
mail=root                               # mail all msgs to root
mail-failure=root               # mail failed update msgs to root
pid=/var/run/ddclient.pid               # record PID in file.
ssl=yes                                 # use ssl-support.  Works with
                                                # ssl-library

# this will update your ipv4 address to the address
# the web service sees requests coming from:
protocol=dyndns2
use=web, web=http://ipv4.nsupdate.info/myip
ssl=yes  # yes = use https for updates
server=ipv4.nsupdate.info
login=[REDACTED].nsupdate.info
password='[REDACTED]'
[REDACTED].nsupdate.info
```

**Comment by caderobinson** [comment]
I was having this as well.
Looked through ddclient script and saw that there is a "%ip_strategies" section that says all the non-versioned options are deprecated (ip, web, if etc) and to use the a "versioned" option (ipv4, ipv6, webv4 webv6 etc)

I changed my config to use them and removed the cache file at /var/cache/ddclient/ddclient.cache and it updated and running the client then said my ipv4 and ipv6 ip were already set.

so changed from:
use=if, if=extnic0

to:
usev4=ifv4, ifv4=extnic0
usev6=ifv6, ifv6=extnic0

and it looks so far to maybe work.

Maybe try:
use=webv4, webv4=http://ipv4.nsupdate.info/myip

If you have a ipv6 ip as well may add this as well
use=webv6, webv6=http://ipv6.nsupdate.info/myip

**Comment by LenardHess** [comment]
This looks to be related to #590

**Comment by LenardHess** [comment]
On further checking - this is the same issue as #590:
- It has `protocol=dyndns2`
- It has the old `use` parameter.

The fix for it has been merged, I'm just waiting for final confirmation of resolution in the other issue.
Closing this as it's duplicate.
