### ISSUE TITLE
curl cannot connect to https://myip.dnsomatic.com using IPv0

### ISSUE THREAD

**Issue by jayjr1105** [ddclient/ddclient#612]
![2024-01-02_14-31](https://github.com/ddclient/ddclient/assets/68028898/9dcc1cb1-3b57-4969-b4e1-41c328bc6be6)

I moved my ddclient to a docker container and since then I've had issues with dnsomatic.  Above SS is my config.  I should mention the DNS server runs on the same hardware in a different container.  Not sure if that might have something to do with it.  Here are the logs...

ddclient  | WARNING:  CURL error (6) Couldn't resolve host. The given remote host was not resolved.
ddclient  | WARNING:  curl cannot connect to https://myip.dnsomatic.com using IPv0
ddclient  | WARNING:  found neither IPv4 nor IPv6 address
ddclient  | WARNING:  Could not determine an IP for all.dnsomatic.com

**Comment by LenardHess** [comment]
It seems that curl is unable to get https://myip.dnsomatic.com resolved.
- Can you reach the URL via your browser?
- Can you reach the URL via `curl https://myip.dnsomatic.com` in a shell?

**Comment by jayjr1105** [comment]
I should have updated my original post.  It appears to be a DNS issue.  This ddclient container can't resolve using my other container (adguard home) as DNS.  I'm pretty new to docker so I'm still working it out.  For the moment.  I set the host resolvers to external DNS servers so it's working now however I still haven't seen an IP update.  Just a lot of this...

ddclient  | WARNING:  found neither IPv4 nor IPv6 address
ddclient  | WARNING:  Could not determine an IP for all.dnsomatic.com
ddclient  | WARNING:  found neither IPv4 nor IPv6 address
ddclient  | WARNING:  Could not determine an IP for all.dnsomatic.com

I know DNS is working not because I can ping google.com from within the container.

**Comment by LenardHess** [comment]
If you set the -verbose you can see the network calls via curl. Can you check that the IP querying happens as expected?
(Note: This option can leak your secrets through the provider network calls, make sure to redact any secret/private info before posting any logs)

**Comment by jayjr1105** [comment]
> If you set the -verbose you can see the network calls via curl. Can you check that the IP querying happens as expected? (Note: This option can leak your secrets through the provider network calls, make sure to redact any secret/private info before posting any logs)

I rebuilt the container from scratch now that I have DNS mostly sorted out and it works.  98% of the time I still get 
ddclient | WARNING: found neither IPv4 nor IPv6 address
ddclient | WARNING: Could not determine an IP for all.dnsomatic.com
But I remember that was the case on my standalone linux server as well.  It only successfully "changes" the public IP every once in a while.  
![image](https://github.com/ddclient/ddclient/assets/68028898/b7a79764-45eb-4f98-bc5d-6a20f756b7d0)

**Comment by LenardHess** [comment]
Ok, so that sounds like its just an issue with myip.dnsomatic.com and/or your network connection.
Closing :+1:
