### ISSUE TITLE
Rework the Mythic Beasts implementation

### ISSUE THREAD

**Issue by retep** [ddclient/ddclient#613]
Rework the Mythic Beasts implementation so that:

1. IPV6 requirements are correctly detected
2. Permit one invocation to update both IPV4 and IPV6 addresses (pseudo simultaneous)

This has been tested with the built-in service within OPNsense (v23.7.10_1) with a minor tweak.

**Comment by LenardHess** [comment]
Hi,

this reads like you meant to do a pull request instead of an issue?

**Comment by retep** [comment]
Indeed, you are correct.  With assistance (thank you @rrthomas ) I have created a pull request (my first on Github - please be gentle).

**Comment by rrthomas** [comment]
Thanks for the PR @retep, closing this issue in favour of #614.
