### ISSUE TITLE
Enhancement: Add '--version' option

### ISSUE THREAD

**Issue by olddog55** [ddclient/ddclient#619]
Add the option '-version' to the executable so that:
---
ddclient version 3.10.0,   <= Current version ID
  originally written by Paul Burry, paul+ddclient@burry.ca
  project now maintained on https://github.com/ddclient/ddclient
---
is displayed without wading thru the full command option synopsis.

**Comment by LenardHess** [comment]
Added in bab6633.

**Comment by olddog55** [comment]
Regression or did it just fall thru the cracks during the transition?

The minor change  commited in bab6633  is not present in v3.11.2

thanx, /dave
