### ISSUE TITLE
Using password_env causes check_value to be called with $type uninitialized on each IP check

### ISSUE THREAD

**Issue by nallick** [ddclient/ddclient#643]
I'm using ddclient in Docker with the Cloudflare protocol. When I include my password directly in the configuration file it works file. When I switch to using a Docker secret and change to _password_env_ in my configuration file it continues to work (so the configuration seems fine) but my log has 17 lines similar to the following for each IP check (i.e., every five minutes)

> Use of uninitialized value $type in string eq at /usr/bin/ddclient line 2383.

I'm not a Perl expert, but it seems the _check_value_ subroutine is being called without initializing the _$type_ variable in this case.

I'm using the current Docker image _lscr.io/linuxserver/ddclient:latest_
Build: _Linuxserver.io version:- v3.11.2-ls151 Build-date:- 2024-03-05T06:51:14+00:00_

My configuration is:
```
daemon=300
syslog=yes
pid=/var/run/ddclient/ddclient.pid
ssl=yes
use=web, web=https://cloudflare.com/cdn-cgi/trace, web-skip='ip='
protocol=cloudflare,        \
zone=redacted.com,        \
ttl=1
password_env=API_TOKEN
redacted.com,another.redacted.com
```

**Comment by LenardHess** [comment]
Fixed in [981dd5f](https://github.com/ddclient/ddclient/commit/981dd5f333f9f2a9430e65a2ccc0c09e0a05d3f1)
