### ISSUE TITLE
 Scalar value @total_payload{$ipv} better written as $total_payload{$ipv} at /usr/sbin/ddclient line 4120

### ISSUE THREAD

**Issue by unnilennium** [ddclient/ddclient#650]
I can thisthis message in log while running using ddclient-3.11.2

seems related to this line in code:
https://github.com/ddclient/ddclient/blame/9885d55a3741363ad52d3463cb846d5782efb073/ddclient.in#L4173C14-L4173C27

**Comment by rhansen** [comment]
What version of Perl are you using?

**Comment by unnilennium** [comment]
version 5.16.3

thanks for the fix.
