### ISSUE TITLE
systemd logs 

### ISSUE THREAD

**Issue by sergiomb2** [ddclient/ddclient#655]
why logs aren't going to journalctl ?

we got log=syslog , I think ddclient don't have log=systemd ?  as I saw in a few projects

**Comment by rhansen** [comment]
By default, systemd captures STDOUT and STDERR in the journal.  However, if ddclient is started in `--noforeground` mode (the default) then STDOUT and STDERR are closed.  To get the STDOUT/STDERR logs in the journal, start ddclient in `--foreground` mode (use `Type=exec` in the [systemd.service(5)](https://www.freedesktop.org/software/systemd/man/latest/systemd.service.html#) file).
