### ISSUE TITLE
v3.11.2 perl warnings?

### ISSUE THREAD

**Issue by l0ddej0kk0** [ddclient/ddclient#706]
Hi,

Using ddclient v3.11.2-1 on Ubuntu 22.4 to update a no-ip dynamic domain.
On daemon start in the system log appears
```
jul 15 13:06:11 myhostname ddclient[162439]: Use of uninitialized value in string eq at /usr/bin/ddclient line 3549.
jul 15 13:06:11 myhostname ddclient[162439]: Use of uninitialized value in string ne at /usr/bin/ddclient line 3563.

```
Common in those 2 lines is the use of `$cache{$host}{'status-ipv4'}` which thus maybe doesn't have a value.

This **could be an artifact** of my first successful update (since discovering usev4 instead of use 8^).

My /etc/default/ddclient:
```
run_dhclient="false"
run_ipup="false"
daemon_interval="86400s"

```
My /etc/ddclient.conf:
```
daemon=86400
usev4=webv4,webv4=ipify-ipv4
protocol=noip \
login=somename \
password='somepassword' \
myfancyhost.hopto.org

```
Probably the second 86400 seconds interval is superfluous, for until i set it in default/ddclient, the daemon ran every 300s, which no-ip considered abusive.

-- 
regards,
-- l0ddej0kk0

**Comment by rhansen** [comment]
Can you try a recent version of `master`?  https://code.launchpad.net/~ddclient/+recipe/ddclient-daily

**Comment by l0ddej0kk0** [comment]
Hi,

now, i updated to
`https://launchpad.net/~ddclient/+archive/ubuntu/daily/+files/ddclient_4.0.0~alpha-1~git202407150750.9256096~ubuntu24.10.1_all.deb`
and stopped an started the ddclient.service.
Journalctl said:
```
jul 16 17:01:17 myhostname systemd[1]: Starting Update dynamic domain name service entries...
jul 16 17:01:17 myhostname systemd[1]: Started Update dynamic domain name service entries.
jul 16 17:01:17 myhostname audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=ddclient comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
...
jul 16 17:01:17 myhostname ddclient[514819]: WARNING:   file /var/cache/ddclient/ddclient.cache, line 3:  Invalid Value for keyword 'wtime' = ''

```
So, the old warnings are history, but you get a new one 8^)
 
--
regards,
-- l0ddej0kk0
