### ISSUE TITLE
Need to submit update on nsupdate.info documentation for ipv6

### ISSUE THREAD

**Issue by DaveSophoServices** [ddclient/ddclient#71]
https://nsupdateinfo.readthedocs.io/en/latest/user.html

> Recommended
> Here are some clients that likely qualify:
>     ddclient
>         we offer configuration help for it, just copy & paste
>         good working, reliable
>         the official version is IPv4 only, IPv6 support needs a patched version
>         Linux & other POSIX systems

create a github pull request to update documentation saying IPv6 no longer needs a patch

**Comment by Taknok** [comment]
PR: nsupdate-info/nsupdate.info#503

**Comment by Taknok** [comment]
PR merged, this issue can be closed.
