### ISSUE TITLE
Using a Cloudflare API token fails but a global key works

### ISSUE THREAD

**Issue by Smartich0ke** [ddclient/ddclient#760]
I'm trying to get ddclient running on Debian 12. I want it to update some A records on CLoudflare. Below is the config I'm using. Obviously I have replaced the sensitive data with placeholders:

```
daemon=300
syslog=yes
pid=/var/run/ddclient.pid
ssl=yes
use=web

protocol=cloudflare \
zone=MY_ZONE, \
ttl=1, \
use=web, web=ipify-ipv4 \
login=MY_EMAIL \
password=MY_API_TOKEN_HERE
MY,DNS,NAMES
```

This config works fine when I use the Global Key fro my cloudflare profile but when I create an API token with `DNS:Edit` permissions over my desired zone and use that instead, the script fails like so. I have removed the logs that seem irrelevant for brevity:
```
$ sudo ddclient --daemon=0 --debug --verbose
[...]
RECEIVE:  {"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6103,"message":"Invalid format for X-Auth-Key header"}]}],"messages":[],"result":null}
RECEIVE:  0
RECEIVE:  
FAILED:   updating MY_DOMAIN: Could not connect to api.cloudflare.com/client/v4.
```

**Comment by LiatrisStar** [comment]
Looks like the code to add support for Cloudflare API _tokens_ was added ~5 months ago: https://github.com/ddclient/ddclient/blame/1c0ba9a1260111f2eb75e76718d218ae2ee0b29f/ddclient.in#L5860

Doesn't look like there's been a release since then, and apt is further out of date (it installed release v3.9.1 on Ubuntu 22.04.05)

**Comment by Smartich0ke** [comment]
Ah, I see! My version must been to old then. I'm still on 3.10.0 with the apt version from the debian 12 repo.

**Comment by surfudder** [comment]
Have the same issue with version 3.11.2. I get a message: "WARNING:  null password specified for host xxx.domein"

**Comment by indrajitr** [comment]
@surfudder, can you please share your `ddclient.conf`?

**Comment by surfudder** [comment]
daemon=300                              # check every 300 secon>
syslog=yes                              # log update msgs to sy>
#mail=root                              # mail all msgs to root
#mail-failure=root          # mail failed update msgs to root
pid=/var/run/ddclient/ddclient.pid      # record PID in file.
ssl=yes                                 # use ssl-support.  Wor>

use=web                                 # via web
web='https://cloudflare.com/cdn-cgi/trace'
web-skip='ip=' # IP address above is after 'ip='

protocol=cloudflare,        \
zone=mydomain.nl,            \
ttl=1,                      \
#login='token',                                         \ 
password='my-token’,       \ # >
wireguard.mydomain.nl,mydomain.nl

**Comment by indrajitr** [comment]
> password='my-token’, \ # >
The ending `, \` doesn't look right.

Can you please try:
```
protocol=cloudflare, \
zone=mydomain.nl, \
password='my-token’ \
wireguard.mydomain.nl
```
A few points regarding Cloudflare configuration:
1. You do no need `login='token', \` if you are using API token, `login` will automatically default to `token` if not supplied
2. Ensure that password is wrapped within `''`
3. You should not have a `,` separator before host (end of `password=` line in your case)

**Comment by surfudder** [comment]
This does not change the output, same result.

**Comment by indrajitr** [comment]
That's very odd. I am not sure what else might be going on. To troubleshoot, you might try something like the following and go through the the verbose log to see if anything is abnormal:

```
ddclient -daemon=0 -debug -force -verbose -noquiet
```

**Comment by jonofmac** [comment]
I've been banging my head against a wall for the last 3 hours trying to get ddclient (3.11.2) to update my subdomain A records. It for some reason is NOT finding the subdomain record at all, even though I have a valid A record already. Looking at the code.

I'm shocked that such a popular DNS host doesn't seem to work. I'm at a loss...

I've tried adding user=token, or user=<my account email>, with no change.

ddclient.conf
```
protocol=cloudflare,        \
zone=domain.com,            \
ttl=1,                      \
usev4=webv4,            \
webv4=http://domain.com/ip.php,  \
password='api token'             \ 
sub.domain.com
```


Output:
```
WARNING:  file /var/cache/ddclient/ddclient.cache, line 3: file ends while expecting a continuation line.
SENDING:  Curl system cmd to https://valdeznetwork.com/
SENDING:  silent
SENDING:  include
SENDING:  ipv4
SENDING:  user-agent="ddclient/3.11.2"
SENDING:  connect-timeout=120
SENDING:  max-time=120
SENDING:  request=GET
SENDING:  url="https://domain.com/ip.php"
RECEIVE:  HTTP/2 200
RECEIVE:  date: Tue, 24 Dec 2024 04:26:50 GMT
RECEIVE:  content-type: text/html; charset=UTF-8
RECEIVE:  cf-cache-status: DYNAMIC
RECEIVE:  vary: Accept-Encoding
RECEIVE:  report-to: {"endpoints":[{"url":"https:\/\/[a.nel.cloudflare.com](http://a.nel.cloudflare.com/)\/report\/v4?s=xk%sensitive"}],"group":"cf-nel","max_age":604800}
RECEIVE:  nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
RECEIVE:  server: cloudflare
RECEIVE:  cf-ray: sensitive-DFW
RECEIVE:  alt-svc: h3=":443"; ma=86400
RECEIVE:  server-timing: cfL4;desc="?proto=TCP&rtt=9419&min_rtt=9087&rtt_var=2116&sent=6&recv=11&lost=0&retrans=0&sent_bytes=3404&recv_bytes=832&delivery_rate=307496&cwnd=220&unsent_bytes=0&cid=sensitive&ts=616&x=0"
RECEIVE:  
RECEIVE:  <my ipv4>
INFO:     forcing updating \ because no cached entry exists.
WARNING:  null password specified for host [sub.domain.com](http://sub.domain.com/).
INFO:     getting Cloudflare Zone ID for \
SENDING:  Curl system cmd to https://api.cloudflare.com/
SENDING:  silent
SENDING:  include
SENDING:  user-agent="ddclient/3.11.2"
SENDING:  connect-timeout=120
SENDING:  max-time=120
SENDING:  request=GET
SENDING:  url="https://api.cloudflare.com/client/v4/zones/?name=domain.com"
SENDING:  header="Content-Type: application/json"
SENDING:  header="Authorization: Bearer <token>"
RECEIVE:  HTTP/2 200
RECEIVE:  date: Tue, 24 Dec 2024 04:26:51 GMT
RECEIVE:  content-type: application/json
RECEIVE:  cf-ray: <sensitive>
RECEIVE:  cf-cache-status: DYNAMIC
RECEIVE:  cache-control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
RECEIVE:  expires: Sun, 25 Jan 1981 05:00:00 GMT
RECEIVE:  set-cookie: __cflb=<sensitive>; SameSite=Lax; path=/; expires=Tue, 24-Dec-24 06:56:52 GMT; HttpOnly
RECEIVE:  strict-transport-security: max-age=31536000
RECEIVE:  pragma: no-cache
RECEIVE:  cf-auditlog-id: <sensitive>
RECEIVE:  x-content-type-options: nosniff
RECEIVE:  x-frame-options: SAMEORIGIN
RECEIVE:  set-cookie: __cf_bm=<sensitive>; path=/; expires=Tue, 24-Dec-24 04:56:51 GMT; domain=.[api.cloudflare.com](http://api.cloudflare.com/); HttpOnly; Secure; SameSite=None
RECEIVE:  set-cookie: __cfruid=<sensitive>; path=/; domain=.[api.cloudflare.com](http://api.cloudflare.com/); HttpOnly; Secure; SameSite=None
RECEIVE:  server: cloudflare
RECEIVE:  
RECEIVE:  {"result":[{"id":"<zone ID>","name":"[domain.com](http://domain.com/)","status":"active","paused":false,"type":"full","development_mode":0,"name_servers":["[charles.ns.cloudflare.com](http://charles.ns.cloudflare.com/)","[michelle.ns.cloudflare.com](http://michelle.ns.cloudflare.com/)"],"original_name_servers":["[ns1.hostmonster.com](http://ns1.hostmonster.com/)","[ns2.hostmonster.com](http://ns2.hostmonster.com/)"],"original_registrar":"fastdomain inc. (id: 1154)","original_dnshost":null,"modified_on":"<date>","created_on":"<date>","activated_on":"<date>","meta":{"step":2,"custom_certificate_quota":0,"page_rule_quota":3,"phishing_detected":false},"owner":{"id":null,"type":"user","email":null},"account":{"id":"<acount id>","name":"[<account email>(mailto:<email>'s Account"},"tenant":{"id":null,"name":null},"tenant_unit":{"id":null},"permissions":["#dns_records:edit","#dns_records:read","#zone:read"],"plan":{"id":"<id>","name":"Free Website","price":0,"currency":"USD","frequency":"","is_subscribed
":false,"can_subscribe":false,"legacy_id":"free","legacy_discount":false,"externally_managed":false}}],"result_info":{"page":1,"per_page":20,"total_pages":1,"count":1,"total_count":1},"success":true,"errors":[],"messages":[]}
INFO:     Zone ID is <zone id>
INFO:     updating \: setting IPv4 address to <my ipv4>
SENDING:  Curl system cmd to https://api.cloudflare.com/
SENDING:  silent
SENDING:  include
SENDING:  user-agent="ddclient/3.11.2"
SENDING:  connect-timeout=120
SENDING:  max-time=120
SENDING:  request=GET
SENDING:  url="https://api.cloudflare.com/client/v4/zones/<zoneid>/dns_records?type=A&name=\\"
SENDING:  header="Content-Type: application/json"
SENDING:  header="Authorization: Bearer  <token>"
RECEIVE:  HTTP/2 200
RECEIVE:  date: Tue, 24 Dec 2024 04:26:51 GMT
RECEIVE:  content-type: application/json
RECEIVE:  cf-ray: <sensitive>
RECEIVE:  cf-cache-status: DYNAMIC
RECEIVE:  set-cookie: __cflb=<sensitive> SameSite=Lax; path=/; expires=Tue, 24-Dec-24 06:56:52 GMT; HttpOnly
RECEIVE:  vary: Accept-Encoding
RECEIVE:  cf-auditlog-id: <sensitive>
RECEIVE:  set-cookie: __cf_bm=<sensitive>; path=/; expires=Tue, 24-Dec-24 04:56:51 GMT; domain=.[api.cloudflare.com](http://api.cloudflare.com/); HttpOnly; Secure; SameSite=None
RECEIVE:  set-cookie: __cfruid=<sensitive>; path=/; domain=.[api.cloudflare.com](http://api.cloudflare.com/); HttpOnly; Secure; SameSite=None
RECEIVE:  server: cloudflare
RECEIVE:  
RECEIVE:  {"result":[],"success":true,"errors":[],"messages":[],"result_info":{"page":1,"per_page":100,"count":0,"total_count":0,"total_pages":1}}
FAILED:   updating \: Cannot set IPv4 to <my IPv4> No 'A' record at Cloudflare
```

**Comment by surfudder** [comment]
WARNING:  file /etc/ddclient/ddclient.conf: Cannot open file '/etc/ddclient/ddclient.conf'. (No such file or directory)
stat() on closed filehandle FD at /usr/bin/ddclient line 1578.
Use of uninitialized value $mode in bitwise and (&) at /usr/bin/ddclient line 1579.
-o on closed filehandle FD at /usr/bin/ddclient line 1584.
-w on closed filehandle FD at /usr/bin/ddclient line 1584.
Use of uninitialized value $mode in bitwise and (&) at /usr/bin/ddclient line 1587.
readline() on closed filehandle FD at /usr/bin/ddclient line 1594.
WARNING:  file /etc/ddclient/ddclient.conf: Cannot open file '/etc/ddclient/ddclient.conf'. (No such file or directory)
stat() on closed filehandle FD at /usr/bin/ddclient line 1578.
Use of uninitialized value $mode in bitwise and (&) at /usr/bin/ddclient line 1579.
-o on closed filehandle FD at /usr/bin/ddclient line 1584.
-w on closed filehandle FD at /usr/bin/ddclient line 1584.
Use of uninitialized value $mode in bitwise and (&) at /usr/bin/ddclient line 1587.
readline() on closed filehandle FD at /usr/bin/ddclient line 1594.
=== opt ====
opt{cache}                           : <undefined>
opt{cmd}                             : <undefined>
opt{cmd-skip}                        : <undefined>
opt{cmdv4}                           : <undefined>
opt{cmdv6}                           : <undefined>
opt{daemon}                          : 0
opt{debug}                           : 1
opt{exec}                            : <undefined>
opt{facility}                        : <undefined>
opt{file}                            : <undefined>
opt{force}                           : 1
opt{foreground}                      : <undefined>
opt{fw}                              : <undefined>
opt{fw-banlocal}                     : CODE(0x7c5b7a799570)
opt{fw-login}                        : <undefined>
opt{fw-password}                     : <undefined>
opt{fw-skip}                         : <undefined>
opt{fw-ssl-validate}                 : <undefined>
opt{fwv4}                            : <undefined>
opt{fwv4-skip}                       : <undefined>
opt{fwv6}                            : <undefined>
opt{fwv6-skip}                       : <undefined>
opt{geturl}                          : <undefined>
opt{help}                            : <undefined>
opt{host}                            : <undefined>
opt{if}                              : <undefined>
opt{if-skip}                         : CODE(0x7c5b7a799570)
opt{ifv4}                            : <undefined>
opt{ifv6}                            : <undefined>
opt{ip}                              : <undefined>
opt{ipv4}                            : <undefined>
opt{ipv6}                            : <undefined>
opt{list-devices}                    : CODE(0x7c5b7a60b940)
opt{list-protocols}                  : CODE(0x7c5b7a4ac540)
opt{list-web-services}               : CODE(0x7c5b7a4b5c78)
opt{login}                           : <redacted>
opt{mail}                            : <undefined>
opt{mail-failure}                    : <undefined>
opt{max-interval}                    : 2160000
opt{max-warn}                        : <undefined>
opt{min-error-interval}              : 300
opt{min-interval}                    : 30
opt{options}                         : <undefined>
opt{password}                        : <redacted>
opt{pid}                             : <undefined>
opt{postscript}                      : <undefined>
opt{priority}                        : <undefined>
opt{protocol}                        : <undefined>
opt{proxy}                           : <undefined>
opt{query}                           : <undefined>
opt{quiet}                           : 0
opt{retry}                           : <undefined>
opt{server}                          : <undefined>
opt{ssl}                             : <undefined>
opt{ssl_ca_dir}                      : <undefined>
opt{ssl_ca_file}                     : <undefined>
opt{syslog}                          : <undefined>
opt{test}                            : <undefined>
opt{timeout}                         : <undefined>
opt{use}                             : <undefined>
opt{usev4}                           : <undefined>
opt{usev6}                           : <undefined>
opt{verbose}                         : 1
opt{web}                             : <undefined>
opt{web-skip}                        : <undefined>
opt{web-ssl-validate}                : <undefined>
opt{webv4}                           : <undefined>
opt{webv4-skip}                      : <undefined>
opt{webv6}                           : <undefined>
opt{webv6-skip}                      : <undefined>
=== globals ====
globals{daemon}                      : 60
globals{debug}                       : 1
globals{force}                       : 1
globals{quiet}                       : 0
globals{verbose}                     : 1
=== config ====
=== cache ====

**Comment by jonofmac** [comment]
The error is right there. You don't have a /etc/ddclient/ddclient.conf file. 

Check to see if the file exists in that path.

**Comment by surfudder** [comment]
what I don't understand about this is that it does not matter if I add this file. It read the config apparently from /config/ddclient.conf. At least those changes are effecting log outputs. So not sure what the /etc/ddclient/ddclient.conf file does.

**Comment by indrajitr** [comment]
> It for some reason is NOT finding the subdomain record at all, even though I have a valid A record already.

@jonofmac: Can you please analyze the `result` array in the Cloudflare response in the ddclient debug message (the line that reads `RECEIVE:  {"result":[{"id":"143cff9a...","zone_id":"..."}`) and see if the `A` record that you expect is showing up in Cloudflare DNS dashboard? If you have a comment for the `A` record in Cloudflare, that comment would also be available in the `result` array.

FWIW, Cloudflare support is pretty stable with the current 3.11.x release (either with global-key or with api-token).

**Comment by indrajitr** [comment]
> what I don't understand about this is that it does not matter if I add this file. It read the config apparently from /config/ddclient.conf. At least those changes are effecting log outputs. So not sure what the /etc/ddclient/ddclient.conf file does.

@surfudder your docker image might need to be validated. What is the config option that `ddclient` call is expecting? Does it require mounting any volume/path? etc. need to be validated.

**Comment by surfudder** [comment]
Just to make sure it is not the docker container I tried it on a different system without docker and get the same result:
WARNING:  null password specified for host
FAILED:   updating \: Cannot set IPv4 to xxx.xxx.xxx.xxx No 'A' record at Cloudflare

OS alpine 3.21 with ddclient 3.11.2

**Comment by Cameronwyatt** [comment]
Currently running into this myself. If you run with `--verbose`, you can see the issue - ddclient is querying for a specific A record: `SENDING:  url="https://api.cloudflare.com/client/v4/zones/<snip>dns_records?type=A&name=\\"`

I'm not sure why it's searching for an A record with the name "\". If I run the same curl command but without the `&name=` param, I get back the A records I have currently defined in CloudFlare. 

```bash
curl -X GET https://api.cloudflare.com/client/v4/zones/4a731adb04b5c10eb15062839038874d/dns_records?type=A -H "Authorization: Bearer <snip>" | jq .
{
  "result": [
    {
      "id": "<snip>",
      "zone_id": "<snip>",
      "zone_name": "cwyatt.me",
      "name": "cwyatt.me",
      "type": "A",
      "content": "<snip>",
      "proxiable": true,
      "proxied": true,
      "ttl": 1,
      "settings": {},
      "meta": {
        "auto_added": false,
        "managed_by_apps": false,
        "managed_by_argo_tunnel": false
      },
      "comment": null,
      "tags": [],
      "created_on": "2024-12-26T19:51:56.678676Z",
      "modified_on": "2024-12-26T19:51:56.678676Z"
    },
    {
      "id": "<snip>",
      "zone_id": "<snip>",
      "zone_name": "cwyatt.me",
      "name": "www.cwyatt.me",
      "type": "A",
      "content": "<snip>",
      "proxiable": true,
      "proxied": true,
      "ttl": 1,
      "settings": {},
      "meta": {
        "auto_added": false,
        "managed_by_apps": false,
        "managed_by_argo_tunnel": false
      },
      "comment": null,
      "tags": [],
      "created_on": "2024-12-26T19:51:50.290899Z",
      "modified_on": "2024-12-26T19:51:50.290899Z"
    }
  ],
  "success": true,
  "errors": [],
  "messages": [],
  "result_info": {
    "page": 1,
    "per_page": 100,
    "count": 2,
    "total_count": 2,
    "total_pages": 1
  }
}
```

Is there a reason it's looking for an A record called "\"?

**Comment by Cameronwyatt** [comment]
@surfudder recommend trying the fix I posted in the previous comment in the update section. Essentially just edit ddclient.conf so that your managed zones are on the same line as your password config

**Comment by indrajitr** [comment]
@Cameronwyatt, thank you for narrowing this down!

> Note that I'm using environment variables for my password, hence the password_env field instead of password, but I don't think it'll make a difference.

No, they don't

> ```
> #inside ddclient.conf
> ##
> ## CloudFlare (www.cloudflare.com)                                    
> ##                                                               
> protocol=cloudflare, \                                             
> zone=cwyatt.me, \                                              
> ttl=1, \                                                     
> password_env=CLOUDFLARE_DNS_API cwyatt.me
> ```

Could you please trim the whitespaces at the end of the lines ending with `\` and try something like this (notice that the last character on every line is `\`)?
```
#inside ddclient.conf
##
## CloudFlare (www.cloudflare.com)
##
protocol=cloudflare, \
zone=cwyatt.me, \
ttl=1, \
password_env=CLOUDFLARE_DNS_API \
cwyatt.me
```

ddclient did not use to like trailing whitespaces and misbehaved altogether. This has been handled in the current main version (also available with [v4.0.0-rc.1](https://github.com/ddclient/ddclient/releases/tag/v4.0.0-rc.1)).

**Comment by Cameronwyatt** [comment]
@indrajitr yep, that appears to fix it as well. FWIW many of the protocol examples/defaults in the ddclient.conf have significant whitespace after them - is this a common issue?

**Comment by indrajitr** [comment]
@Cameronwyatt They have been mostly taken care of. But if you notice any inconsistency you still see in v4, it would be wonderful to be notified.

**Comment by jonofmac** [comment]
Looks like removing all whitespace/comments after the \ fixed the issue fixed it for me.

Very strange. But essentially just having a simple ", \" after each line with no extra white spaces did indeed make it function for me.

**Comment by surfudder** [comment]
Yes removing the '\' and the commented text after de password fixes it. It now works perfectly. Thanks for the help.

**Comment by indrajitr** [comment]
Summarizing this for anyone coming here via a search engine:

1. Cloudflare protocol works with both API token and global key on ddclient v3.11.2.
2. ddclient v3.11.2 config parsing does have issues with configuration having trailing whitespaces
3. Please make sure that the configuration lines do not have trailing white spaces or comments (starting with `#`)
4. These issues should not appear in ddclient v4.0.0

Thank you very much for confirming @Cameronwyatt, @jonofmac and @surfudder! I'll go ahead and close this issue for now. @Smartich0ke: Feel free to open another issue if you still have trouble.
