### ISSUE TITLE
Latest Release

### ISSUE THREAD

**Issue by AhnHEL** [ddclient/ddclient#778]
There are a lot of commits and efforts from @rhansen along with the community within the last year to the project and some necessary changes will never be ported for us end users until the latest release is updated because ddclient is packaged into other projects that just use the latest release.   Kindly, is there any expectation on when this will happen?  Thank you in advance.

**Comment by indrajitr** [comment]
Thank you @AhnHEL for raising this. As you might have noticed, 4.0.0 release candidate has been [created](https://github.com/ddclient/ddclient/releases/tag/v4.0.0-rc.1).

All going well, v4.0.0 will be released "when it is ready" but is not too far away :) - there isn't any specific date though.

**Comment by AhnHEL** [comment]
@indrajitr @rhansen Thank you
