### ISSUE TITLE
ddclient behind a NAT gateway.

### ISSUE THREAD

**Issue by TomHsiung** [ddclient/ddclient#79]
For some reason, the ddclient's outgoing packets would be modified by NAT POSTROUTING rules so that the packets' source IP address would be changed from the ddclient machine's IP address to the NAT gateway's address.

So, would this affect the domains being maintained by ddclient? Thank you.

**Comment by wimpunk** [comment]
I'm afraid I have some issues understanding your question.  Ddclient fetches the IP based on how you configure ddclient and updates the service you configured based on the fetched IP.  If you use ddclient behind a NAT gateway (a situation a lot of people use), the traffic will be translated the same way like you browse the internet behind that NAT gateway.

**Comment by TomHsiung** [comment]
Hello,

Thank you for your respond. Per my understanding of your description, so the NAT gateway's public IP address would be fetched and used to update the DDNS domain records, correct?

What we want is to fetch the machine's IP address where ddclient runs and send it to DDNS service.

For example, Alice is behind the NAT gateway and has an IP address of 1.1.1.1. The NAT gateway change source IP addresses of Alice's outgoing packets to the NAT gateway's public IP address, saying 2.2.2.2, and ddclient is running on Alice.

So in this case, which of the two IP addresses above would be update to DDNS records? Thank you

Thank you.

**Comment by wimpunk** [comment]
It depends on your configuration.  If you use the typical `-use=web` your public IP will probably be fetched.  Using the `-if=eth0` option ddclient will fetch the IP from you eth0 interface.

**Comment by TomHsiung** [comment]
Oh, that is a good news. Now let me ask my DDNS service provider if they support `-use=eth0`. Probably they only support `-use=web`, :(

**Comment by wimpunk** [comment]
No, it's not related to your ddns provider, it's related to the ddclient configuration.  Although some ddns providers don't support the use of private IP's when updating.

**Comment by TomHsiung** [comment]
Hello,

It is absolute not private IP. It is definitely public IP. You know, I mean the IPsec tunnel. Traffics flow along an encapsulated tunnel toward the NAT gateway. Thank you.

**Comment by TomHsiung** [comment]
Just talking with Namecheap supporters, they said:

> t is only possible to have use=web details applied in DDClient in order DynamicDNS can work properly.

Below is their official guide on how to use ddclient to update DNS records.

![image](https://user-images.githubusercontent.com/6930263/67072627-e2ecf500-f1b7-11e9-9a7e-026b6b79f993.png)

**Comment by wimpunk** [comment]
Just use this as your configuration and you will be fine:
```
use=if, if=eth0
protocol=namecheap
server=dynamicdns.park-your-domain.com
```
It's just imported for ddclient to know how to fetch your IP and what he has to update.  In this case you tell ddclient to fetch the IP from the interface eth0 and use the namecheap protocol to update the server dynamicdns.park-your-domain.com

*Most* people use ddclient to update their public IP and to prevent troubles they say don't change the `use`-line.  It works in 99% of the cases.  You're an exception in this case.  Most people just use mDNS or bonjour to find the systems in the local network.

**Comment by TomHsiung** [comment]
It really worked! Thank you for your kind help!

Tom
