### ISSUE TITLE
Request: Dreamhost

### ISSUE THREAD

**Issue by saltymedic** [ddclient/ddclient#80]
If like to request adding Dreamhost to the list of places this client can update the IP address to

[https://help.dreamhost.com/hc/en-us/articles/217555707-DNS-API-commands](https://help.dreamhost.com/hc/en-us/articles/217555707-DNS-API-commands) 

Thank you

**Comment by jkugler** [comment]
Howdy! This was closed as completed, but the README.md doesn't reference dreamhost, and I don't see PRs relating to Dreamhost: https://github.com/ddclient/ddclient/pulls?q=is%3Apr+is%3Aopen+dreamhost

Was Dreamhost support added?

I currently use Dreamhost, so this would be a fantastic addition.

**Comment by mrfuntime** [comment]
another 2 years have passed and the above situation is unchanged.  I'd also like to use this with DreamHost.   Thanks.
