### ISSUE TITLE
Warning about invalid fully qualified hostname on Cloudflare

### ISSUE THREAD

**Issue by SpencerDub** [ddclient/ddclient#82]
I've been trying to set ddclient up to update Cloudflare. When I run `ddclient -daemon=0 -debug -verbose -noquiet`, I get four warnings, two of which are the same:

> WARNING:  skipping host: <example.com>: 'zone=' is an invalid fully qualified host name.

<example.com> is a stand-in for my actual registered domain.

The Cloudflare section of my ddclient.conf file looks like this:

```
##
## CloudFlare (www.cloudflare.com)
##
ssl=yes                     \
protocol=cloudflare,        \
server=www.cloudflare.com,  \
login=<my Cloudflare login email>     \
password=<API token>             \
<example.com>,
```
Is this warning something I should be worried about? How do I resolve it? I'm unfortunately quite clueless when it comes to administrative stuff like this, so I appreciate all the help you can provide.

Thanks!

**Comment by DaveSophoServices** [comment]
I’ve recently taken over maintaining this project. Can you try taking the \ out of the config file? I know a lot of examples have them, I’m not sure what the purpose of them is. 

Dave

**Comment by SpencerDub** [comment]
Thanks, Dave! I've done that, which means the relevant section of ddclient.conf is now:
```
##
## CloudFlare (www.cloudflare.com)
##
ssl=yes
protocol=cloudflare,
server=www.cloudflare.com,
login=<my Cloudflare login email>
password=<API token>
<example.com>,
```
I still get the same results when I run `ddclient -daemon=0 -debug -verbose -noquiet`.

**Comment by DaveSophoServices** [comment]
Your domain ends in .com and is registered with this login?

**Comment by SpencerDub** [comment]
My domain ends in .us and is registered with this login.

**Comment by cadatoiva** [comment]
I got this to work by putting "zone=<mydoman.us>"

It seems the new TLD's aren't recognized by the script just yet, so you can't use the implied zoning.

` zone=zone-where-domains-are  ## only needed if 1 or more subdomains are deeper
                               ## than 1 level in relation to  the zone where it
                               ## is defined. For example, b.foo.com in a zone
                               ## foo.com doesn't need this, but a.b.foo.com in
                               ## the same zone needs zone=foo.com`

**Comment by DaveSophoServices** [comment]
Thanks @cadatoiva, I'm glad you were able to get it working. I'll try to take a look at it soon. It'll become more of a problem. Does this work for you @SpencerDub?
I'm presuming to just put zone= before your domain name.

**Comment by SpencerDub** [comment]
Adding `zone=<mydomain.us>` did the trick. It's now throwing other errors, but they are unrelated to the scope of this issue. Thanks, @cadatoiva and @DaveSophoServices!

**Comment by tito-cr** [comment]
> I’ve recently taken over maintaining this project. Can you try taking the \ out of the config file? I know a lot of examples have them, I’m not sure what the purpose of them is. Dave

It's a sort of continuation character. You would use it in a script to break up long lines for readability.

**Comment by MKastuv** [comment]
Okay, if anyone having this issue still, here is how I fixed. I updated the ddclient from github. Use clone and follow the process of installation not from the release tgz. After that modify your ddclient.conf as follows:

```
protocol=cloudflare,
#Tell ddclient to get real ip address
use=web, web=ipinfo.io/ip
zone=<your FQDN>,
ttl=1,
login=email@domain.com, # Only needed if you are using your global API key.
password=<GLOBAL API KEY> # This is either your global API key, or an API token. If you are using an API token, it must have the permissions "Zone - DNS - Edit" and "Zone - Zo    ne - Read". The Zone resources must be "Include - All zones".
subdomain.<YOUR FQDN>
```

Cheers !
