### ISSUE TITLE
ddserver?  

### ISSUE THREAD

**Issue by egberts** [ddclient/ddclient#83]
I would love a small update to the README showing where some of us (few) can get an open-sourced DD server software (in which we can use to test the ddclient with).

**Comment by DaveSophoServices** [comment]
Sounds like a great idea. Any leads? Most of what we have a apis that companies have written to manage their dns systems. 

Dave

**Comment by q2dg** [comment]
Maybe https://github.com/nsupdate-info/nsupdate.info ?

**Comment by wimpunk** [comment]
Long time ago I started a ddserver project on sf.net but I never finished it.  It looks like someone else tried the same: https://sourceforge.net/projects/dd-server/
Currently I'm using the possibility of ddclient to update bind using nsupdate which is enough for me.

**Comment by Neustradamus** [comment]
ddserver is here: https://github.com/ddserver

**Comment by SuperSandro2000** [comment]
I am not planning to expand the README with any other project links which need maintenance.
