### ISSUE TITLE
cloudflare FAILED:   updating mydomain : No DNS record ID found.

### ISSUE THREAD

**Issue by miltosc** [ddclient/ddclient#85]
Hello!

using ddclient for cloudflare i get the error at the end 
"cloudflare FAILED:   updating mydomain : No DNS record ID found."

**Comment by libertyx82** [comment]
doe you have changed the entry "mydomain" to the name of your domain?

**Comment by miltosc** [comment]
yes

**Comment by libertyx82** [comment]
And the A Record with the same Name is existing on Cloudflare?

Could you please show your ddclient config?

**Comment by miltosc** [comment]
i did not have A record i thought it will be created automatically.
it works now.
Thank you very much!

**Comment by TrackerSB** [comment]
Having a CNAME record for the subdomain works for accessing the subdomain as well if the server (in my case nginx) is accordingly configured. However, ddclient yields the same warning when using a CNAME instead of an A record.
