### ISSUE TITLE
Ddclient gives warning "cannot connect to checkip.dyndns.org"

### ISSUE THREAD

**Issue by jgwallace3** [ddclient/ddclient#86]
My ddlclient (3.9.0) recently started kicking out an odd warning message. Site checkip.dyndns.org is definitely available. I rebooted a few times just to be sure. Ideas?
```
From SYSLOG:
Dec  4 16:53:41 MINIPC ddclient[918]: WARNING:  cannot connect to checkip.dyndns.org:80 socket: IO::Socket::INET: Bad hostname 'checkip.dyndns.org'
Dec  4 16:53:41 MINIPC ddclient[918]: WARNING:  found neither ipv4 nor ipv6 address

From BASH (IP returned IS correct):
16:55 ~ : curl checkip.dyndns.org
<html><head><title>Current IP Check</title></head><body>Current IP Address: xxx.xxx.xxx.xxx</body></html>
```

**Comment by petersjt014** [comment]
Looks like this has happened before (#41). I've added something on that issue that might fix this (by moving to a new site).

**Comment by ajm1635** [comment]
A (failover?) alternative can be found here: [https://whatismyipaddress.com/api](url)
A description of the service can be found here: [https://whatismyipaddress.com/api](url)

Oracle is making major changes at Dyn so I am not sure if the checkip.dyndns.org will continue to be available.

**Comment by SuperSandro2000** [comment]
Why can't you get your IP address from your router?

**Comment by ajm1635** [comment]
> Why can't you get your IP address from your router?

There are routers which do not make the information (easily) available so ddclient has supported external public IP retrieval since the beginning.

**Comment by jgwallace3** [comment]
As @ajm1635, indicated, my router doesn't provide the IP info. I've switched to "web=bot.whatismyipaddress.com" and that is working well.

Curiously, I still get the "WARNING:  found neither ipv4 nor ipv6 address" message.
(But NOT the "cannot connect" one now :))

**Comment by ajm1635** [comment]
> Curiously, I still get the "WARNING: found neither ipv4 nor ipv6 address" message.
> (But NOT the "cannot connect" one now :))

Are you sure that is not an old message?  Looking at the code it appears the external ip would not get set in the case where that error message is emitted.

**Comment by jgwallace3** [comment]
Sorry for a false alert. That warning is only generated when I run "ddclient -daemon=0 -query -debug". If comes right after the 'use=if' statements.

Normal operation is NOT giving those messages.
