### ISSUE TITLE
Remove dead providers

### ISSUE THREAD

**Issue by petersjt014** [ddclient/ddclient#87]
Some of DDNS providers listed are no longer operating. Removing them would clean up the code a bit. These include:

- [Hammernode](http://hn.org): site does not resolve
- [ConCont](http://dydns.za.net): does not resolve, possibly a typo for dy[n]dns.za.net?
- [DnsPark](http://dnspark.com): site seems broken, a [cached search result](https://www.google.com/search?q=site%3Adnspark.com) notes that the domain itself is for sale
- [Loopia](http://www.loopia.se): Maybe broke--Site only loads the main page title and times out
- [DTDNS](https://www.dtdns.com) (as the site itself says)

Some other sites listed may no longer be working for other reasons:
- [woima.fi](http://woima.fi): redirects to a [new site](http://planeetta.fi), and I can't tell if it offers DDNS because I can't read Finnish.
- [Yandex](https://domain.yandex.com): redirects to a page offering some kind of mail service.

**Comment by q2dg** [comment]
On the other hand, https://www.noip.com/remote-access isn't listed and it's operative (see https://medium.com/@nobuto_m/minimal-dynamic-dns-configuration-for-no-ip-com-with-ddclient-cb7c038a74be for instance)
