### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by Neustradamus** [ddclient/ddclient#88]
There are no new version since more one year, it is possible to have a new version?

**Comment by SuperSandro2000** [comment]
Just checkout master :)

**Comment by Neustradamus** [comment]
It is not a solution because for example, distros use official packages.

**Comment by wimpunk** [comment]
There will be a release soon. I hope to get it wrapped as a christmas present.

**Comment by Neustradamus** [comment]
@wimpunk: Nice :)
Please add your email address in github, look your commits ;)

**Comment by SuperSandro2000** [comment]
> It is not a solution because for example, distros use official packages.

It is a solution if you need the update right now and can't wait.
And that is wrong. Even Debian does not require a version scheme but it is really good to have one and makes the task for distributions way easier.

**Comment by SuperSandro2000** [comment]
You can keep track of https://github.com/ddclient/ddclient/projects/1 to know when 4.0.0 will release. We are going to create more issues and pr over time so it will probably take a bit more. Nevertheless I am going to close this issue.
