### ISSUE TITLE
Permissions for ddclient.conf and ddclient.cache

### ISSUE THREAD

**Issue by SpencerDub** [ddclient/ddclient#89]
I'm still trying to set up ddclient to work on an Ubuntu (18.04) server to work with Cloudflare.

When I run `ddclient -daemon=0 -debug -verbose -noquiet`, I get the following warnings and errors related to permissions:

> WARNING:  file /etc/ddclient/ddclient.conf: file /etc/ddclient/ddclient.conf must be accessible only by its owner.
> WARNING:  file /etc/ddclient/ddclient.conf: file /etc/ddclient/ddclient.conf must be accessible only by its owner.
> [...]
> FATAL:    Cannot create file '/var/cache/ddclient/ddclient.cache'. (Permission denied)

What do the permissions of `ddclient.conf` need to be to remove this warning?

And how can I fix the fatal permissions error about `ddclient.cache`?

Thanks!

**Comment by DaveSophoServices** [comment]
What user are you running ddclient as? That will be the user that needs permission for ddclient. 

It will need read access for the configuration file. Read write access isn’t a problem. 

It will need read write access to /var/cache/ddclient. 

Dave

**Comment by SpencerDub** [comment]
Hi Dave. Thanks for the answer, this set me on the right track.

When I was moving files around as part of installation, they got reset to `root:root` ownership. Their permissions were as they should be, but ownership was wrong. I went and changed the ownership on several of the key files to `spencer:spencer` and saw these permissions-related messages disappear.

Thanks for all of your help with this. It's felt like fighting a hydra, getting ddclient set up, but I think I'm really close to being done.

**Comment by planetahuevo** [comment]
Hi @SpencerDub Can you share your conf file? I am not able to connect with cloudflare to update a subdomain... 
This is the error I am getting: 
 {"success":false,"errors":[{"code":7000,"message":"No route for that URI"}],"messages":[],"result":null}

**Comment by planetahuevo** [comment]
My bad, I was using 3.8.3 version which is not updated. 
I just update to this one and it works! :) 
Thanks for the tip with the URL

**Comment by miesepeter** [comment]
Same problem occurred to me today, the ownership was accidentally set to root (also after reinstalling). Therefore I always got "Cannot open file '/etc/ddclient.conf'. (Permission denied)". Once I found the issue it was quickly solved with:
```
sudo chown username:groupname /etc/ddclient.conf  
sudo chown -R username:groupname /var/cache/ddclient
```
