### ISSUE TITLE
-bash: ddclient: command not found

### ISSUE THREAD

**Issue by SpencerDub** [ddclient/ddclient#90]
I'm trying to set up ddclient on a YunoHost server. I cloned the git repository and used the commands at the beginning of the installation guide in order to move and copy files as needed.

When I try to execute `ddclient -daemon=0 -debug -verbose -noquiet` from the terminal, I now get a bash error message:

> -bash: ddclient: command not found

How can I resolve this? Thanks!

**Comment by DaveSophoServices** [comment]
Thanks @spencerdub, I suspect something is missing from the installation guide. We’ll check it over. I suspect you’ve already checked over the steps you’ve followed?

Dave

**Comment by SpencerDub** [comment]
Thanks, @DaveSophoServices. I did indeed double-check my steps--all the files that were supposed to be copied were successfully copied, and every directory that was supposed to be created was created.

**Comment by DaveSophoServices** [comment]
@wimpunk, is there a reason that we’re putting the client into /usr/sbin?

@spencerdub, if you cp it to /usr/bin, it’ll run, does it complete all the required tasks?

**Comment by SpencerDub** [comment]
@DaveSophoServices, looks like it!

**Comment by wimpunk** [comment]
> @wimpunk, is there a reason that we’re putting the client into /usr/sbin?

@DaveSophoServices 
It's just historical.  Long time ago ddclient was always run as root because otherwise you could not run `ifconfig` or something similar to detect the IP.  Nowadays it's better to run ddclient as a separate user so it doesn't have to be in `/usr/sbin` anymore.

**Comment by SuperSandro2000** [comment]
Are you running Debian Bullseye? By default they no longer add sbin to your path standard path but only if you use sudo.

**Comment by rhansen** [comment]
FYI, `make install` installs ddclient to `/usr/bin/ddclient`.
