### ISSUE TITLE
API Tokens for cloudflare require a prefix "Bearer "

### ISSUE THREAD

**Issue by dancvrcek** [ddclient/ddclient#95]
#73 is probably on the same topic.

After some experimenting I managed to get it working with cloudflare by changing 

> $headers .= "X-Auth-Key: $config{$key}{'password'}\n";

to

> $headers .= "Authorization: Bearer $config{$key}{'password'}\n";

... it would need a protocol switch for general use

Edit: X-Auth-Key had to be changed to "Authorization". Although I would think I got it working with X-Auth-Key yesterday. :/

... I tried to add "Bearer" to the configuration file but it results in the actual key being dropped.

**Comment by LINUX3932** [comment]
Thanks!!!

**Comment by TheraNinjaCat** [comment]
I have written an patch that would allow this to happen in #102

**Comment by alivahabi2112** [comment]
Tanks mr

**Comment by alivahabi2112** [comment]
Ap send me
