### ISSUE TITLE
Support for inwx with ipv6

### ISSUE THREAD

**Issue by Technikte** [ddclient/ddclient#96]
Please add support for inwx dyndns service.

https://www.inwx.de/
Update-URL:  https://dyndns.inwx.com/nic/update?myip=(ipaddr)&myipv6=(ip6addr)

> We support the DynDNS2 protocol via HTTPS.
To update your domain, you must in many cases provide an update URL in your client (e.g. router).
With the additional "myipv6" parameter our DynDNS service is also fully IPv6 capable.

or It would be nice if some one could post a working config since for me errors out every time.
I use this following docker container -> https://hub.docker.com/r/linuxserver/ddclient

> WARNING: file /var/cache/ddclient/ddclient.cache, line 3: Invalid Value for keyword 'ip' = ''
> WARNING: cannot connect to https:443 socket: Name does not resolve IO::Socket::IP configuration failed
> FAILED: updating ddns.byteframe.de: Could not connect to https://dyndns.inwx.com.

```
daemon=150				# check every 300 seconds
syslog=yes				# log update msgs to syslog

#pid=/var/run/ddclient/ddclient.pid		# record PID in file.
ssl=yes 				# use ssl-support.  Works with

protocol=dyndns2
use=web, web=https://ipv6.nsupdate.info/myip
#use=if, if=br0
#if-skip=Scope:Link
ipv6=yes
server=https://dyndns.inwx.com
login=XXXXXXXXXX
password=XXXXXXXXXXXXX
subdomain.abc.de
```

**Comment by SuperSandro2000** [comment]
Works with https://github.com/ddclient/ddclient/pull/40

**Comment by rhansen** [comment]
Drop the `https://` from the `server` setting:

```
server=dyndns.inwx.com
```

ddclient to pass your IPv6 address via the `myip` parameter (not `myipv6`), which inwx.com may or may not accept.

Better IPv6 support is coming; see #172.

**Comment by SuperSandro2000** [comment]
This is a feature request and feature requests in the form of issues are no longer accepted.

**Comment by Starkstromkonsument** [comment]
> ddclient to pass your IPv6 address via the `myip` parameter (not `myipv6`), which inwx.com may or may not accept.

INWX does not support the URL-format `https://dyndns.inwx.com/nic/update?myip=<ipaddr>,<ip6addr>`. It only works with the URL-format `https://dyndns.inwx.com/nic/update?myip=<ipaddr>&myipv6=<ip6addr>`.

**Comment by Starkstromkonsument** [comment]
I contacted the support of INWX. They are not planing / willing to change their URL-format to comply with the dyndns2-protocol. To add full IPv4 + IPv6 support for INWX to ddclient it is necessary to implement their format `https://dyndns.inwx.com/nic/update?myip=<ipaddr>&myipv6=<ip6addr>`.

Some more caveats:
- If you try to update only IPv6 by passing an empty value for `myip` or you leave it away (e.g. `https://dyndns.inwx.com/nic/update?myipv6=<ip6addr>`), the service will respond with `nochg` but the IPv4 will be reset to `127.0.0.1`.
- If you try to update only the IPv4 (e.g. `https://dyndns.inwx.com/nic/update?myip=<ipaddr>`), the service will respond with `nochg` but delete the IPv6.
- Conclusion: if you use IPv4 and IPv6 with INWX you must always include both IPs in the URL. They told me, IPv4 can be disabled by the support to use IPv6-only though.

> This is a feature request and feature requests in the form of issues are no longer accepted.

Please tell me how / where to file feature requests now. Thank you.

**Comment by BjGoCraft** [comment]
> Conclusion: if you use IPv4 and IPv6 with INWX you must always include both IPs in the URL. They told me, IPv4 can be disabled by the support to use IPv6-only though.

if anyone is reading this on their research: This is no longer the case. The INWX support wrote that it is enough to only submit the IPv6 address like this: https://dyndns.inwx.com/nic/update?myipv6=<ip6addr> 
In this case the A record gets deleted. No need to contact support for that anymore.
The contribution from @Starkstromkonsument (#690) also seems to allow this (it worked in my case by just removing the `usev4=ifv4, ifv4=eth0` line)
