### ISSUE TITLE
Nginx + DDClient + Cloudflare

### ISSUE THREAD

**Issue by DrrAld** [ddclient/ddclient#97]
Hello All. I haven’t been able to find any help with this elsewhere, so I’m hoping someone here may have some ideas.

A bit about my setup:

1. Ubuntu 18.04 LTS server
2. Static ip and DNS set within Network Manager
3. Running several apps (Jellyfin, Calibre-Web, Sonarr etc)
4. Nginx fully installed
5. GoDaddy domain proxied through Cloudflare
6. DDClient synchronizing ip from server to Cloudflare
7. Port 80, 443 and 8096 (Jellyfin for testing) allowed in server Firewall and from router to static ip

I’ve installed DDClient and setup the connection between my server and Cloudflare to propagate the proper ip address on the domains I currently have setup (example.com and jellyfin.example.com). This connection seems to be working as when I visit the updated IP address listed on Cloudflare from the browser on the server, it opens the default Nginx landing page. If I use that ip with a port (ex: http://CloudflareIP:8096 for Jellyfin) in a browser on the server, it also opens Jellyfin, but very slowly. These links of course also work with simply localhost or 127.0.0.1 as the url on the server.

However, when attempting to visit the Cloudflare ip on another device, it doesn’t open the default index page nor any of the apps on ports. Also worth mentioning is that visiting http://staticip or http://staticip:port only works when calling the url from a device other than the server. When trying to visit the static ip from the server, it’s unable to connect. And of course, visiting the domain and subdomain listed in Cloudflare (example.com and jellyfin.example.com) don’t pick up the Nginx index page at all, but instead show a Cloudflare page with host error; again confirming that the DDClient/Cloudflare connection is working.

What I’d like to know is how do I make the domains listed on Cloudflare serve externally or in other words, work as they’re supposed to. Additionally, how do I ensure that the speed of the pages served is faster than tested. As mentioned, when visiting http://CloudflareIP:8096 from the server, the page loads but is a bit slow. I assume this is due to bandwidth (which I can deal with), but want to make sure there’s nothing I’ve done to slow this down or anything that I can do to help the speed.

Lastly, the domains hosted with Cloudflare will be the main domain and subdomains (ex: example.com, jellyfin.example.com, calibre.example.com and so on). I don’t know if this has any effect on possible configuration or misconfiguration recommendations, but wanted to include as much information as possible.

Any and all recommendations or possible scenarios are greatly appreciated. Thanks in advance.

**Comment by wimpunk** [comment]
I'm afraid this has nothing to do with ddclient.  Ddclient just makes an update of the DNS, nothing more. You should ratter check cloudflare for this kind of issue.
