### ISSUE TITLE
Exit code

### ISSUE THREAD

**Issue by modem7** [ddclient/ddclient#99]
Hey guys, 

The way I have my network setup is mostly in Docker. 

I have a Pihole with a dnscrypt upstream. 

If DDClient starts up before anything else (which is likely, with it being such a light application), I can experience issues such as "WARNING:  cannot connect to checkip.dyndns.com:80 socket: IO::Socket::INET: Bad hostname 'checkip.dyndns.com'"

If when the application saw this error, if we could get some form of exit code which either 1. indicates it to try again x number of times or 2. allowed it to mark the container/application as unhealthy, this would make sure these errors were either really errors, or more likely, an issue with when it initially checked dyndns.

Hope it makes sense!

Thanks

**Comment by wimpunk** [comment]
Sorry but it doesn't make sense.  When ddclient can't update it has to keep running trying to update another time.  Ddclient isn't made for monitoring the health of your network.
